-- ============================================================
-- GRIDIRON365 V2
-- MIGRATION 001
-- CORE LEAGUE FOUNDATION
--
-- This file establishes ONLY:
--   profiles
--   leagues
--   league_members
--   fantasy_teams
--   league_settings
--
-- Draft, rosters, scoring, waivers, trades and playoffs come later.
-- ============================================================

begin;


-- ============================================================
-- 1. PROFILES
-- ============================================================

create table public.profiles (
    user_id uuid
        primary key
        references auth.users(id)
        on delete cascade,

    first_name text,

    last_name text,

    display_name text,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now()
);


-- ============================================================
-- 2. LEAGUES
-- ============================================================

create table public.leagues (
    id uuid
        primary key
        default gen_random_uuid(),

    name text
        not null,

    league_type text
        not null,

    season integer
        not null,

    commissioner_user_id uuid
        not null
        references auth.users(id)
        on delete restrict,

    status text
        not null
        default 'setup',

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint leagues_name_check
        check (
            length(
                trim(name)
            ) between 1 and 100
        ),

    constraint leagues_type_check
        check (
            league_type in (
                'traditional',
                'salary',
                'nfl_playoffs'
            )
        ),

    constraint leagues_season_check
        check (
            season between 2000 and 2200
        ),

    constraint leagues_status_check
        check (
            status in (
                'setup',
                'pre_draft',
                'drafting',
                'regular_season',
                'playoffs',
                'completed'
            )
        )
);


-- ============================================================
-- 3. LEAGUE MEMBERS
-- ============================================================

create table public.league_members (
    id bigint
        generated by default as identity
        primary key,

    league_id uuid
        not null
        references public.leagues(id)
        on delete cascade,

    user_id uuid
        not null
        references auth.users(id)
        on delete cascade,

    role text
        not null
        default 'member',

    joined_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint league_members_unique
        unique (
            league_id,
            user_id
        ),

    constraint league_members_role_check
        check (
            role in (
                'commissioner',
                'co_commissioner',
                'member'
            )
        )
);


-- ============================================================
-- 4. FANTASY TEAMS
-- ============================================================

create table public.fantasy_teams (
    id bigint
        generated by default as identity
        primary key,

    league_id uuid
        not null
        references public.leagues(id)
        on delete cascade,

    owner_id uuid
        references auth.users(id)
        on delete set null,

    team_name text
        not null,

    active boolean
        not null
        default true,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint fantasy_teams_name_check
        check (
            length(
                trim(team_name)
            ) between 1 and 100
        ),

    constraint fantasy_teams_owner_unique
        unique (
            league_id,
            owner_id
        )
);


-- ============================================================
-- 5. LEAGUE SETTINGS
--
-- Keep this intentionally small.
--
-- Roster/scoring/waiver/trade/playoff settings will get their
-- own migrations instead of turning this into one giant table.
-- ============================================================

create table public.league_settings (
    id bigint
        generated by default as identity
        primary key,

    league_id uuid
        not null
        unique
        references public.leagues(id)
        on delete cascade,

    season integer
        not null,

    max_teams integer
        not null
        default 12,

    regular_season_weeks integer
        not null
        default 14,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint league_settings_season_check
        check (
            season between 2000 and 2200
        ),

    constraint league_settings_max_teams_check
        check (
            max_teams between 2 and 1000
        ),

    constraint league_settings_regular_weeks_check
        check (
            regular_season_weeks between 1 and 18
        )
);


-- ============================================================
-- 6. CORE INDEXES
-- ============================================================

create index
    idx_league_members_user
on public.league_members (
    user_id,
    league_id
);


create index
    idx_league_members_league
on public.league_members (
    league_id,
    user_id
);


create index
    idx_fantasy_teams_league_active
on public.fantasy_teams (
    league_id,
    active,
    id
);


create index
    idx_fantasy_teams_owner
on public.fantasy_teams (
    owner_id,
    league_id
)
where owner_id is not null;


create index
    idx_leagues_commissioner
on public.leagues (
    commissioner_user_id,
    id
);


create index
    idx_leagues_type_status
on public.leagues (
    league_type,
    status
);


commit;