-- ============================================================
-- GRIDIRON365 V2
-- MIGRATION 007
-- TRADITIONAL ROSTERS + WEEKLY LINEUPS
--
-- PURPOSE
--   team_rosters:
--     Permanent player ownership for Traditional teams.
--
--   weekly_lineups:
--     Weekly placement of rostered players into lineup slots.
--
-- IMPORTANT
--   Ownership and lineup placement are intentionally separate.
-- ============================================================

begin;


-- ============================================================
-- 1. TEAM ROSTERS
-- ============================================================

create table if not exists public.team_rosters (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    fantasy_team_id bigint not null
        references public.fantasy_teams(id)
        on delete cascade,

    player_id bigint not null,

    acquired_via text not null default 'draft',

    acquired_at timestamptz not null default now(),

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint team_rosters_acquired_via_check
        check (
            acquired_via in (
                'draft',
                'waiver',
                'free_agent',
                'trade',
                'commissioner'
            )
        ),

    constraint team_rosters_team_player_unique
        unique (
            fantasy_team_id,
            player_id
        )
);


-- ============================================================
-- 2. ONE PLAYER CANNOT BELONG TO TWO TEAMS
--    IN THE SAME TRADITIONAL LEAGUE
-- ============================================================

create unique index if not exists
    team_rosters_league_player_unique
on public.team_rosters (
    league_id,
    player_id
);


-- ============================================================
-- 3. USEFUL ROSTER INDEXES
-- ============================================================

create index if not exists
    team_rosters_league_id_idx
on public.team_rosters (
    league_id
);


create index if not exists
    team_rosters_fantasy_team_id_idx
on public.team_rosters (
    fantasy_team_id
);


create index if not exists
    team_rosters_player_id_idx
on public.team_rosters (
    player_id
);


-- ============================================================
-- 4. WEEKLY LINEUPS
--
-- One row = one player placed into one lineup slot
-- for one fantasy week.
--
-- slot_index allows multiple RB / WR / FLEX / BENCH slots.
-- ============================================================

create table if not exists public.weekly_lineups (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    fantasy_team_id bigint not null
        references public.fantasy_teams(id)
        on delete cascade,

    season integer not null,

    week integer not null,

    player_id bigint not null,

    lineup_slot text not null,

    slot_index integer not null default 1,

    is_locked boolean not null default false,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    constraint weekly_lineups_season_check
        check (
            season >= 2000
            and season <= 2200
        ),

    constraint weekly_lineups_week_check
        check (
            week >= 1
            and week <= 25
        ),

    constraint weekly_lineups_slot_index_check
        check (
            slot_index >= 1
        ),

    constraint weekly_lineups_slot_check
        check (
            lineup_slot in (
                'QB',
                'RB',
                'WR',
                'TE',
                'FLEX',
                'SUPERFLEX',
                'K',
                'DST',
                'BENCH',
                'IR'
            )
        ),

    constraint weekly_lineups_team_week_player_unique
        unique (
            fantasy_team_id,
            season,
            week,
            player_id
        ),

    constraint weekly_lineups_team_week_slot_unique
        unique (
            fantasy_team_id,
            season,
            week,
            lineup_slot,
            slot_index
        )
);


-- ============================================================
-- 5. USEFUL WEEKLY LINEUP INDEXES
-- ============================================================

create index if not exists
    weekly_lineups_league_week_idx
on public.weekly_lineups (
    league_id,
    season,
    week
);


create index if not exists
    weekly_lineups_team_week_idx
on public.weekly_lineups (
    fantasy_team_id,
    season,
    week
);


create index if not exists
    weekly_lineups_player_idx
on public.weekly_lineups (
    player_id
);


-- ============================================================
-- 6. RLS
-- ============================================================

alter table public.team_rosters
enable row level security;


alter table public.weekly_lineups
enable row level security;


-- ============================================================
-- 7. ROSTER READ POLICY
--
-- Any member of the league can see league rosters.
-- This will later support:
--   My Team
--   Matchups
--   Trades
--   Commissioner
-- ============================================================

drop policy if exists
    "League members can view team rosters"
on public.team_rosters;


create policy
    "League members can view team rosters"
on public.team_rosters
for select
to authenticated
using (
    private.is_league_member(
        league_id,
        auth.uid()
    )
);


-- ============================================================
-- 8. WEEKLY LINEUP READ POLICY
-- ============================================================

drop policy if exists
    "League members can view weekly lineups"
on public.weekly_lineups;


create policy
    "League members can view weekly lineups"
on public.weekly_lineups
for select
to authenticated
using (
    private.is_league_member(
        league_id,
        auth.uid()
    )
);


-- ============================================================
-- IMPORTANT:
--
-- We are intentionally NOT adding direct INSERT / UPDATE /
-- DELETE policies yet.
--
-- Lineup changes, waivers, trades, commissioner changes,
-- and draft ownership should go through controlled database
-- functions instead of allowing arbitrary browser writes.
-- ============================================================


commit;