-- ============================================================
-- GRIDIRON365 V2
-- MIGRATION 008
-- TRADITIONAL ROSTER SETTINGS
--
-- PURPOSE
--   Stores configurable roster requirements for Traditional
--   leagues.
--
--   These settings will drive:
--     My Team
--     Draft eligibility
--     Waivers
--     Commissioner roster editing
--     Lineup validation
-- ============================================================

begin;


-- ============================================================
-- 1. TRADITIONAL ROSTER SETTINGS
-- ============================================================

create table if not exists public.traditional_roster_settings (
    id bigint
        generated by default as identity
        primary key,

    league_id uuid
        not null
        unique
        references public.leagues(id)
        on delete cascade,

    starting_qb integer
        not null
        default 1,

    starting_rb integer
        not null
        default 2,

    starting_wr integer
        not null
        default 2,

    starting_te integer
        not null
        default 1,

    starting_flex integer
        not null
        default 2,

    starting_superflex integer
        not null
        default 0,

    starting_k integer
        not null
        default 1,

    starting_dst integer
        not null
        default 1,

    bench_slots integer
        not null
        default 6,

    ir_slots integer
        not null
        default 0,

    max_qb integer
        not null
        default 3,

    max_rb integer
        not null
        default 8,

    max_wr integer
        not null
        default 8,

    max_te integer
        not null
        default 4,

    max_k integer
        not null
        default 2,

    max_dst integer
        not null
        default 2,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),


    constraint traditional_roster_starting_qb_check
        check (
            starting_qb between 0 and 4
        ),

    constraint traditional_roster_starting_rb_check
        check (
            starting_rb between 0 and 6
        ),

    constraint traditional_roster_starting_wr_check
        check (
            starting_wr between 0 and 6
        ),

    constraint traditional_roster_starting_te_check
        check (
            starting_te between 0 and 4
        ),

    constraint traditional_roster_starting_flex_check
        check (
            starting_flex between 0 and 4
        ),

    constraint traditional_roster_starting_superflex_check
        check (
            starting_superflex between 0 and 4
        ),

    constraint traditional_roster_starting_k_check
        check (
            starting_k between 0 and 3
        ),

    constraint traditional_roster_starting_dst_check
        check (
            starting_dst between 0 and 3
        ),

    constraint traditional_roster_bench_slots_check
        check (
            bench_slots between 0 and 20
        ),

    constraint traditional_roster_ir_slots_check
        check (
            ir_slots between 0 and 10
        ),

    constraint traditional_roster_max_qb_check
        check (
            max_qb between 0 and 10
        ),

    constraint traditional_roster_max_rb_check
        check (
            max_rb between 0 and 20
        ),

    constraint traditional_roster_max_wr_check
        check (
            max_wr between 0 and 20
        ),

    constraint traditional_roster_max_te_check
        check (
            max_te between 0 and 10
        ),

    constraint traditional_roster_max_k_check
        check (
            max_k between 0 and 6
        ),

    constraint traditional_roster_max_dst_check
        check (
            max_dst between 0 and 6
        )
);


-- ============================================================
-- 2. INDEX
-- ============================================================

create index if not exists
    traditional_roster_settings_league_idx
on public.traditional_roster_settings (
    league_id
);


-- ============================================================
-- 3. RLS
-- ============================================================

alter table public.traditional_roster_settings
enable row level security;


drop policy if exists
    "League members can view traditional roster settings"
on public.traditional_roster_settings;


create policy
    "League members can view traditional roster settings"
on public.traditional_roster_settings
for select
to authenticated
using (
    private.is_league_member(
        league_id,
        auth.uid()
    )
);


drop policy if exists
    "Commissioners can update traditional roster settings"
on public.traditional_roster_settings;


create policy
    "Commissioners can update traditional roster settings"
on public.traditional_roster_settings
for update
to authenticated
using (
    exists (
        select 1
        from public.leagues l
        where l.id =
              traditional_roster_settings.league_id
          and l.commissioner_user_id =
              auth.uid()
    )
)
with check (
    exists (
        select 1
        from public.leagues l
        where l.id =
              traditional_roster_settings.league_id
          and l.commissioner_user_id =
              auth.uid()
    )
);


-- ============================================================
-- 4. CREATE DEFAULT ROSTER SETTINGS FOR EXISTING
--    TRADITIONAL LEAGUES
-- ============================================================

insert into public.traditional_roster_settings (
    league_id
)
select
    l.id
from public.leagues l
where l.league_type =
      'traditional'
on conflict (
    league_id
)
do nothing;


-- ============================================================
-- 5. AUTOMATIC DEFAULT SETTINGS FOR FUTURE
--    TRADITIONAL LEAGUES
-- ============================================================

create or replace function public.create_default_traditional_roster_settings()
returns trigger
language plpgsql
security definer
set search_path =
    pg_catalog,
    public
as $function$

begin

    if new.league_type =
       'traditional'
    then

        insert into public.traditional_roster_settings (
            league_id
        )
        values (
            new.id
        )
        on conflict (
            league_id
        )
        do nothing;

    end if;

    return new;

end;

$function$;


drop trigger if exists
    trg_create_default_traditional_roster_settings
on public.leagues;


create trigger
    trg_create_default_traditional_roster_settings
after insert
on public.leagues
for each row
execute function
    public.create_default_traditional_roster_settings();


commit;