-- ============================================================
-- GRIDIRON365 V2
-- MIGRATION 009
-- NFL PLAYER FOUNDATION
--
-- PURPOSE
--   One clean source of truth for NFL players used throughout:
--
--     Traditional
--     Weekly Salary / No Salary
--     NFL Playoffs Salary / No Salary
--
--   This table will feed:
--     Draft
--     My Team
--     Players
--     Waivers
--     Trades
--     Matchups
--     Scoring
--     Weekly contests
--     NFL Playoff contests
-- ============================================================

begin;


-- ============================================================
-- 1. NFL PLAYERS
-- ============================================================

create table if not exists public.nfl_players (
    id bigint
        generated by default as identity
        primary key,

    espn_player_id text
        unique,

    full_name text
        not null,

    first_name text,

    last_name text,

    primary_position text
        not null,

    team_abbreviation text,

    jersey_number text,

    status text
        not null
        default 'ACTIVE',

    is_active boolean
        not null
        default true,

    headshot_url text,

    bye_week integer,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),


    constraint nfl_players_name_check
        check (
            length(
                trim(
                    full_name
                )
            ) >= 1
        ),


    constraint nfl_players_position_check
        check (
            primary_position in (
                'QB',
                'RB',
                'WR',
                'TE',
                'K',
                'PK',
                'DST',
                'FB'
            )
        ),


    constraint nfl_players_bye_week_check
        check (
            bye_week is null
            or (
                bye_week >= 1
                and bye_week <= 18
            )
        )
);


-- ============================================================
-- 2. PLAYER INDEXES
-- ============================================================

create index if not exists
    nfl_players_position_active_idx
on public.nfl_players (
    primary_position,
    is_active,
    id
);


create index if not exists
    nfl_players_team_active_idx
on public.nfl_players (
    team_abbreviation,
    is_active,
    id
);


create index if not exists
    nfl_players_name_idx
on public.nfl_players (
    full_name
);


create index if not exists
    nfl_players_espn_idx
on public.nfl_players (
    espn_player_id
)
where espn_player_id is not null;


-- ============================================================
-- 3. PLAYER READ RLS
--
-- Any authenticated Gridiron365 user can read NFL player data.
-- This is shared public-football information inside the app.
-- ============================================================

alter table public.nfl_players
enable row level security;


drop policy if exists
    "Authenticated users can view NFL players"
on public.nfl_players;


create policy
    "Authenticated users can view NFL players"
on public.nfl_players
for select
to authenticated
using (
    true
);


-- ============================================================
-- 4. CONNECT TEAM ROSTERS TO NFL PLAYERS
-- ============================================================

alter table public.team_rosters
drop constraint if exists
    team_rosters_player_id_fkey;


alter table public.team_rosters
add constraint
    team_rosters_player_id_fkey
foreign key (
    player_id
)
references public.nfl_players(
    id
)
on delete restrict;


-- ============================================================
-- 5. CONNECT WEEKLY LINEUPS TO NFL PLAYERS
-- ============================================================

alter table public.weekly_lineups
drop constraint if exists
    weekly_lineups_player_id_fkey;


alter table public.weekly_lineups
add constraint
    weekly_lineups_player_id_fkey
foreign key (
    player_id
)
references public.nfl_players(
    id
)
on delete restrict;


commit;