-- ============================================================
-- GRIDIRON365 V2
-- MIGRATION 010
-- NFL TEAMS + SEASON-SPECIFIC TEAM DATA
--
-- PURPOSE
--   nfl_teams:
--     Permanent NFL team identity.
--
--   nfl_team_seasons:
--     Season-specific information such as bye week.
--
--   Players reference an NFL team abbreviation.
-- ============================================================

begin;


-- ============================================================
-- 1. NFL TEAMS
-- ============================================================

create table if not exists public.nfl_teams (
    id bigint
        generated by default as identity
        primary key,

    espn_team_id text
        unique,

    abbreviation text
        not null
        unique,

    location text,

    name text
        not null,

    display_name text
        not null,

    short_display_name text,

    color text,

    alternate_color text,

    logo_url text,

    is_active boolean
        not null
        default true,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint nfl_teams_abbreviation_check
        check (
            length(
                trim(abbreviation)
            ) between 2 and 4
        )
);


-- ============================================================
-- 2. NFL TEAM SEASONS
-- ============================================================

create table if not exists public.nfl_team_seasons (
    id bigint
        generated by default as identity
        primary key,

    nfl_team_id bigint
        not null
        references public.nfl_teams(id)
        on delete cascade,

    season integer
        not null,

    bye_week integer,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint nfl_team_seasons_unique
        unique (
            nfl_team_id,
            season
        ),

    constraint nfl_team_seasons_season_check
        check (
            season between 2000 and 2200
        ),

    constraint nfl_team_seasons_bye_week_check
        check (
            bye_week is null
            or bye_week between 1 and 18
        )
);


-- ============================================================
-- 3. INDEXES
-- ============================================================

create index if not exists
    nfl_team_seasons_season_idx
on public.nfl_team_seasons (
    season,
    nfl_team_id
);


create index if not exists
    nfl_teams_active_idx
on public.nfl_teams (
    is_active,
    abbreviation
);


-- ============================================================
-- 4. REMOVE PLAYER-LEVEL BYE WEEK
--
-- Bye week belongs to the player's NFL team for a particular
-- season, not permanently to the player.
-- ============================================================

alter table public.nfl_players
drop constraint if exists
    nfl_players_bye_week_check;


alter table public.nfl_players
drop column if exists
    bye_week;


-- ============================================================
-- 5. PLAYER TEAM INDEX
--
-- We intentionally keep team_abbreviation on nfl_players.
-- It makes common player-page filtering extremely cheap.
--
-- nfl_teams remains the authoritative team identity table.
-- ============================================================

create index if not exists
    nfl_players_team_abbreviation_idx
on public.nfl_players (
    team_abbreviation
)
where team_abbreviation is not null;


-- ============================================================
-- 6. RLS
-- ============================================================

alter table public.nfl_teams
enable row level security;


alter table public.nfl_team_seasons
enable row level security;


drop policy if exists
    "Authenticated users can view NFL teams"
on public.nfl_teams;


create policy
    "Authenticated users can view NFL teams"
on public.nfl_teams
for select
to authenticated
using (
    true
);


drop policy if exists
    "Authenticated users can view NFL team seasons"
on public.nfl_team_seasons;


create policy
    "Authenticated users can view NFL team seasons"
on public.nfl_team_seasons
for select
to authenticated
using (
    true
);


commit;