-- ============================================================
-- GRIDIRON365 V2
-- MIGRATION 011
-- NFL GAMES / SCHEDULE FOUNDATION
--
-- PURPOSE
--   Permanent season-aware NFL schedule storage.
--
--   Used later by:
--     Bye weeks
--     My Team
--     Player pages
--     Matchups
--     Lineup locking
--     Live scoring
--     Game status
--     NFL playoffs
-- ============================================================

begin;


-- ============================================================
-- 1. NFL GAMES
-- ============================================================

create table if not exists public.nfl_games (
    id bigint
        generated by default as identity
        primary key,

    espn_event_id text
        not null
        unique,

    season integer
        not null,

    season_type integer
        not null,

    week integer
        not null,

    kickoff_at timestamptz
        not null,

    home_team_id bigint
        not null
        references public.nfl_teams(id)
        on delete restrict,

    away_team_id bigint
        not null
        references public.nfl_teams(id)
        on delete restrict,

    home_score integer,

    away_score integer,

    status_type text,

    status_name text,

    status_detail text,

    status_completed boolean
        not null
        default false,

    venue_name text,

    venue_city text,

    venue_state text,

    neutral_site boolean
        not null
        default false,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),


    constraint nfl_games_season_check
        check (
            season between 2000 and 2200
        ),

    constraint nfl_games_season_type_check
        check (
            season_type in (
                1,
                2,
                3
            )
        ),

    constraint nfl_games_week_check
        check (
            week between 1 and 25
        ),

    constraint nfl_games_home_away_check
        check (
            home_team_id <> away_team_id
        ),

    constraint nfl_games_home_score_check
        check (
            home_score is null
            or home_score >= 0
        ),

    constraint nfl_games_away_score_check
        check (
            away_score is null
            or away_score >= 0
        )
);


-- ============================================================
-- 2. INDEXES
-- ============================================================

create index if not exists
    nfl_games_season_week_idx
on public.nfl_games (
    season,
    season_type,
    week
);


create index if not exists
    nfl_games_kickoff_idx
on public.nfl_games (
    kickoff_at
);


create index if not exists
    nfl_games_home_team_idx
on public.nfl_games (
    home_team_id,
    season,
    week
);


create index if not exists
    nfl_games_away_team_idx
on public.nfl_games (
    away_team_id,
    season,
    week
);


create index if not exists
    nfl_games_status_idx
on public.nfl_games (
    season,
    status_completed,
    kickoff_at
);


-- ============================================================
-- 3. RLS
--
-- NFL schedule information can be read by any authenticated
-- Gridiron365 user.
--
-- Writes will be performed only by trusted server sync code
-- using the service-role client.
-- ============================================================

alter table public.nfl_games
enable row level security;


drop policy if exists
    "Authenticated users can view NFL games"
on public.nfl_games;


create policy
    "Authenticated users can view NFL games"
on public.nfl_games
for select
to authenticated
using (
    true
);


-- ============================================================
-- 4. HELPER VIEW
--
-- Gives the application an easy schedule representation with
-- team abbreviations without repeatedly writing the joins.
-- ============================================================

create or replace view public.nfl_game_schedule
with (
    security_invoker = true
)
as

select
    g.id,

    g.espn_event_id,

    g.season,

    g.season_type,

    g.week,

    g.kickoff_at,

    away.abbreviation
        as away_team,

    home.abbreviation
        as home_team,

    g.away_score,

    g.home_score,

    g.status_type,

    g.status_name,

    g.status_detail,

    g.status_completed,

    g.venue_name,

    g.venue_city,

    g.venue_state,

    g.neutral_site,

    g.updated_at

from public.nfl_games g

join public.nfl_teams home
  on home.id =
     g.home_team_id

join public.nfl_teams away
  on away.id =
     g.away_team_id;


commit;