-- ============================================================
-- GRIDIRON365 V2
-- MIGRATION 012
-- NFL INJURY DATA FOUNDATION
--
-- PURPOSE
--   Store current and historical NFL player injury information
--   synchronized from ESPN.
--
-- USED BY
--   Players
--   My Team
--   Draft
--   Waivers
--   Matchups
--   Player cards
--   News / alerts
-- ============================================================

begin;


-- ============================================================
-- 1. NFL PLAYER INJURIES
-- ============================================================

create table if not exists public.nfl_player_injuries (
    id bigint
        generated by default as identity
        primary key,

    nfl_player_id bigint
        not null
        references public.nfl_players(id)
        on delete cascade,

    espn_player_id text
        not null,

    season integer
        not null,

    status text,

    injury_type text,

    injury_location text,

    injury_detail text,

    injury_date date,

    return_date date,

    source_updated_at timestamptz,

    is_active boolean
        not null
        default true,

    first_seen_at timestamptz
        not null
        default now(),

    last_seen_at timestamptz
        not null
        default now(),

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now(),

    constraint nfl_player_injuries_season_check
        check (
            season between 2000 and 2200
        )
);


-- ============================================================
-- 2. ONLY ONE CURRENT ACTIVE INJURY PER PLAYER / SEASON
--
-- Historical injury records can remain in the table after
-- is_active becomes false.
-- ============================================================

create unique index if not exists
    nfl_player_injuries_active_player_season_uidx
on public.nfl_player_injuries (
    nfl_player_id,
    season
)
where is_active = true;


-- ============================================================
-- 3. LOOKUP INDEXES
-- ============================================================

create index if not exists
    nfl_player_injuries_player_idx
on public.nfl_player_injuries (
    nfl_player_id
);


create index if not exists
    nfl_player_injuries_espn_player_idx
on public.nfl_player_injuries (
    espn_player_id
);


create index if not exists
    nfl_player_injuries_season_idx
on public.nfl_player_injuries (
    season,
    is_active
);


create index if not exists
    nfl_player_injuries_status_idx
on public.nfl_player_injuries (
    season,
    status
)
where is_active = true;


create index if not exists
    nfl_player_injuries_last_seen_idx
on public.nfl_player_injuries (
    last_seen_at desc
);


-- ============================================================
-- 4. RLS
--
-- All authenticated Gridiron365 users may read injury data.
--
-- Writes will come from trusted server-side synchronization
-- code using the Supabase service role.
-- ============================================================

alter table public.nfl_player_injuries
enable row level security;


drop policy if exists
    "Authenticated users can view NFL player injuries"
on public.nfl_player_injuries;


create policy
    "Authenticated users can view NFL player injuries"
on public.nfl_player_injuries
for select
to authenticated
using (
    true
);


-- ============================================================
-- 5. CURRENT INJURY VIEW
--
-- Gives the application a simple representation of the
-- current injury status for each player.
-- ============================================================

create or replace view public.current_nfl_player_injuries
with (
    security_invoker = true
)
as

select
    i.id,

    i.nfl_player_id,

    p.espn_player_id,

    p.full_name,

    p.primary_position,

    p.team_abbreviation,

    p.headshot_url,

    i.season,

    i.status,

    i.injury_type,

    i.injury_location,

    i.injury_detail,

    i.injury_date,

    i.return_date,

    i.source_updated_at,

    i.first_seen_at,

    i.last_seen_at,

    i.updated_at

from public.nfl_player_injuries i

join public.nfl_players p
  on p.id =
     i.nfl_player_id

where i.is_active = true;


commit;