begin;

create extension if not exists pgcrypto;

-- ============================================================
-- 1. Allow the new league type/mode without changing existing
--    Traditional / Season-Long / NFL Playoffs behavior.
-- ============================================================

do $$
declare
  r record;
begin
  for r in
    select conname
    from pg_constraint
    where conrelid = 'public.leagues'::regclass
      and contype = 'c'
      and (
        pg_get_constraintdef(oid) ilike '%league_type%'
        or pg_get_constraintdef(oid) ilike '%player_selection_mode%'
      )
  loop
    execute format('alter table public.leagues drop constraint %I', r.conname);
  end loop;
end
$$;

alter table public.leagues
  add constraint leagues_league_type_g365_check
  check (league_type in ('traditional','season_long','nfl_playoffs','pickem'));

alter table public.leagues
  add constraint leagues_player_selection_mode_g365_check
  check (player_selection_mode in ('draft','salary','no_salary','pickem'));

alter table public.leagues
  add constraint leagues_type_mode_g365_check
  check (
    (league_type = 'traditional' and player_selection_mode = 'draft')
    or (league_type in ('season_long','nfl_playoffs') and player_selection_mode in ('salary','no_salary'))
    or (league_type = 'pickem' and player_selection_mode = 'pickem')
  );

-- ============================================================
-- 2. League settings
-- ============================================================

create table if not exists public.pickem_settings (
  league_id uuid primary key references public.leagues(id) on delete cascade,
  season integer not null check (season between 2000 and 2200),
  football_scope text not null default 'college_nfl'
    check (football_scope in ('college_nfl','college_only','nfl_only')),
  picks_per_week integer not null default 5
    check (picks_per_week between 1 and 20),
  line_day_dow integer not null default 2
    check (line_day_dow between 0 and 6),
  line_day_hour_et integer not null default 10
    check (line_day_hour_et between 0 and 23),
  pick_lock_mode text not null default 'per_game'
    check (pick_lock_mode in ('per_game','full_card')),
  reveal_mode text not null default 'per_game_kickoff'
    check (reveal_mode = 'per_game_kickoff'),
  push_points numeric(4,2) not null default 0.50,
  win_points numeric(4,2) not null default 1.00,
  loss_points numeric(4,2) not null default 0.00,
  require_trustworthy_consensus boolean not null default true,
  minimum_source_books integer not null default 3
    check (minimum_source_books between 1 and 20),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Compatibility if an earlier Pick'em foundation was already run.
alter table public.pickem_settings
  drop constraint if exists pickem_settings_picks_per_week_check;

alter table public.pickem_settings
  add constraint pickem_settings_picks_per_week_check
  check (picks_per_week between 1 and 20);

-- ============================================================
-- 3. Weekly lifecycle
-- Week is not official until all included games are FINAL and
-- the Monday-night finalization gate has passed.
-- ============================================================

create table if not exists public.pickem_weeks (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  season integer not null,
  week integer not null check (week between 1 and 25),
  status text not null default 'setup'
    check (status in ('setup','open','in_progress','awaiting_finalization','final')),
  required_picks integer not null default 5
    check (required_picks between 1 and 20),
  opens_at timestamptz,
  line_day_at timestamptz,
  finalize_not_before timestamptz,
  finalized_at timestamptz,
  finalized_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (league_id, season, week)
);

alter table public.pickem_weeks
  add column if not exists required_picks integer not null default 5;

alter table public.pickem_weeks
  drop constraint if exists pickem_weeks_required_picks_check;

alter table public.pickem_weeks
  add constraint pickem_weeks_required_picks_check
  check (required_picks between 1 and 20);

create index if not exists pickem_weeks_league_status_idx
  on public.pickem_weeks(league_id, status, week);

-- ============================================================
-- 4. Eligible games + live ESPN state
-- g365_home_spread is always expressed from the HOME team's side.
-- Example: HOME -7.5 => -7.5; HOME +3 => +3.
-- ============================================================

create table if not exists public.pickem_games (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  pickem_week_id bigint not null references public.pickem_weeks(id) on delete cascade,
  season integer not null,
  week integer not null,
  sport text not null check (sport in ('ncaaf','nfl')),
  provider text not null default 'espn',
  provider_event_id text not null,
  kickoff_at timestamptz not null,
  away_team_name text not null,
  away_team_abbreviation text,
  home_team_name text not null,
  home_team_abbreviation text,
  away_score integer,
  home_score integer,
  status_type text,
  status_name text,
  status_detail text,
  period integer,
  display_clock text,
  is_started boolean not null default false,
  is_final boolean not null default false,
  is_eligible boolean not null default true,
  exclusion_reason text,
  g365_home_spread numeric(6,2),
  spread_status text not null default 'pending'
    check (spread_status in ('pending','published','frozen','excluded')),
  spread_published_at timestamptz,
  spread_frozen_at timestamptz,
  consensus_source_count integer,
  consensus_method text,
  last_score_sync_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (league_id, provider, provider_event_id)
);

create index if not exists pickem_games_week_idx
  on public.pickem_games(league_id, season, week, kickoff_at);
create index if not exists pickem_games_live_idx
  on public.pickem_games(is_final, kickoff_at)
  where is_eligible = true;

-- ============================================================
-- 5. Authorized sportsbook source/audit lines
-- No provider is hard-coded. The ingest route writes one row per
-- sportsbook quote, then freezes the median consensus separately.
-- ============================================================

create table if not exists public.pickem_line_sources (
  id bigint generated by default as identity primary key,
  pickem_game_id bigint not null references public.pickem_games(id) on delete cascade,
  captured_at timestamptz not null default now(),
  source_provider text not null,
  sportsbook_key text not null,
  sportsbook_name text,
  home_spread numeric(6,2) not null,
  away_spread numeric(6,2),
  source_event_id text,
  source_market_key text,
  raw_audit jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pickem_line_sources_game_captured_idx
  on public.pickem_line_sources(pickem_game_id, captured_at desc);

-- ============================================================
-- 6. Participant picks
-- Pick visibility is enforced by the member-facing RPC below:
-- own pick is always visible; another member's pick is only
-- visible when that selected game's kickoff has arrived/started.
-- ============================================================

create table if not exists public.pickem_picks (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  pickem_week_id bigint not null references public.pickem_weeks(id) on delete cascade,
  fantasy_team_id bigint not null references public.fantasy_teams(id) on delete restrict,
  pickem_game_id bigint not null references public.pickem_games(id) on delete restrict,
  selected_side text not null check (selected_side in ('home','away')),
  frozen_home_spread numeric(6,2) not null,
  submitted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  locked_at timestamptz,
  result text not null default 'pending'
    check (result in ('pending','win','loss','push','void')),
  graded_at timestamptz,
  points_awarded numeric(6,2),
  unique (pickem_week_id, fantasy_team_id, pickem_game_id)
);

create index if not exists pickem_picks_team_week_idx
  on public.pickem_picks(league_id, fantasy_team_id, pickem_week_id);

-- ============================================================
-- 7. Weekly official results / standings source
-- ============================================================

create table if not exists public.pickem_weekly_results (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  pickem_week_id bigint not null references public.pickem_weeks(id) on delete cascade,
  fantasy_team_id bigint not null references public.fantasy_teams(id) on delete restrict,
  wins integer not null default 0,
  losses integer not null default 0,
  pushes integer not null default 0,
  pending integer not null default 0,
  points numeric(8,2) not null default 0,
  is_final boolean not null default false,
  weekly_rank integer,
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (pickem_week_id, fantasy_team_id)
);

create index if not exists pickem_weekly_results_standings_idx
  on public.pickem_weekly_results(league_id, is_final, points desc, wins desc);

-- ============================================================
-- 8. Permanent Pick'em badge awards (recap/trophy room ready)
-- ============================================================

create table if not exists public.pickem_badge_awards (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  fantasy_team_id bigint not null references public.fantasy_teams(id) on delete restrict,
  season integer not null,
  week integer not null,
  badge_key text not null,
  badge_name text not null,
  badge_category text not null check (badge_category in ('ACHIEVEMENT','INFAMY','WEEKLY')),
  details jsonb,
  created_at timestamptz not null default now(),
  unique (league_id, fantasy_team_id, season, week, badge_key)
);

-- ============================================================
-- 9. Create a Pick'em league without modifying the existing
--    create_league_transaction used by the other league types.
-- ============================================================

create or replace function public.create_pickem_league_transaction(
  p_name text,
  p_season integer,
  p_entry_name text
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public, auth
as $$
declare
  v_user_id uuid := auth.uid();
  v_league_id uuid;
  v_team_id bigint;
  v_name text := trim(coalesce(p_name, ''));
  v_entry_name text := trim(coalesce(p_entry_name, ''));
begin
  if v_user_id is null then
    raise exception using errcode = '42501', message = 'You must be signed in to create a league.';
  end if;

  if length(v_name) not between 1 and 100 then
    raise exception using errcode = '22023', message = 'League name must be between 1 and 100 characters.';
  end if;

  if length(v_entry_name) not between 1 and 100 then
    raise exception using errcode = '22023', message = 'A Pick''em league requires an entry name between 1 and 100 characters.';
  end if;

  if p_season is null or p_season not between 2000 and 2200 then
    raise exception using errcode = '22023', message = 'A valid league season is required.';
  end if;

  insert into public.leagues (
    name, league_type, season, commissioner_user_id, status, player_selection_mode
  ) values (
    v_name, 'pickem', p_season, v_user_id, 'setup', 'pickem'
  ) returning id into v_league_id;

  insert into public.league_members (league_id, user_id, role)
  values (v_league_id, v_user_id, 'commissioner');

  -- Keep the shared league shell/settings expectations intact.
  insert into public.league_settings (league_id, season, max_teams, regular_season_weeks)
  values (v_league_id, p_season, null, null);

  insert into public.fantasy_teams (league_id, owner_id, team_name, active)
  values (v_league_id, v_user_id, v_entry_name, true)
  returning id into v_team_id;

  insert into public.pickem_settings (league_id, season)
  values (v_league_id, p_season);

  return jsonb_build_object(
    'success', true,
    'leagueId', v_league_id,
    'leagueType', 'pickem',
    'playerSelectionMode', 'pickem',
    'season', p_season,
    'role', 'commissioner',
    'fantasyTeamId', v_team_id
  );
end;
$$;

revoke all on function public.create_pickem_league_transaction(text,integer,text) from public;
grant execute on function public.create_pickem_league_transaction(text,integer,text) to authenticated;

-- ============================================================
-- 10. Freeze consensus spread as MEDIAN of the latest captured
--     line from each sportsbook. This is provider-neutral.
-- ============================================================

create or replace function public.freeze_pickem_g365_spread(
  p_pickem_game_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_league_id uuid;
  v_min_books integer;
  v_count integer;
  v_median numeric(6,2);
  v_user uuid := auth.uid();
begin
  select g.league_id, s.minimum_source_books
  into v_league_id, v_min_books
  from public.pickem_games g
  join public.pickem_settings s on s.league_id = g.league_id
  where g.id = p_pickem_game_id
  for update of g;

  if not found then
    raise exception 'Pick''em game could not be found.';
  end if;

  if v_user is not null and not exists (
    select 1 from public.league_members lm
    where lm.league_id = v_league_id
      and lm.user_id = v_user
      and lm.role in ('commissioner','co_commissioner')
  ) then
    raise exception using errcode = '42501', message = 'Commissioner access is required.';
  end if;

  with latest as (
    select distinct on (sportsbook_key)
      sportsbook_key, home_spread
    from public.pickem_line_sources
    where pickem_game_id = p_pickem_game_id
    order by sportsbook_key, captured_at desc, id desc
  )
  select count(*), percentile_cont(0.5) within group (order by home_spread)::numeric(6,2)
  into v_count, v_median
  from latest;

  if v_count < v_min_books then
    update public.pickem_games
    set spread_status = 'excluded',
        is_eligible = false,
        exclusion_reason = format('Only %s trustworthy source lines were available; %s required.', v_count, v_min_books),
        consensus_source_count = v_count,
        updated_at = now()
    where id = p_pickem_game_id;

    return jsonb_build_object('success', false, 'excluded', true, 'sourceCount', v_count);
  end if;

  update public.pickem_games
  set g365_home_spread = v_median,
      spread_status = 'frozen',
      spread_published_at = coalesce(spread_published_at, now()),
      spread_frozen_at = now(),
      consensus_source_count = v_count,
      consensus_method = 'median_latest_per_sportsbook',
      is_eligible = true,
      exclusion_reason = null,
      updated_at = now()
  where id = p_pickem_game_id;

  return jsonb_build_object(
    'success', true,
    'gameId', p_pickem_game_id,
    'g365HomeSpread', v_median,
    'sourceCount', v_count,
    'method', 'median_latest_per_sportsbook'
  );
end;
$$;

grant execute on function public.freeze_pickem_g365_spread(bigint) to authenticated;

-- ============================================================
-- 11. Pick grading using frozen G365 spread only.
-- ============================================================

create or replace function public.grade_pickem_game(p_pickem_game_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_game public.pickem_games%rowtype;
  v_settings public.pickem_settings%rowtype;
  v_home_ats numeric;
  v_rows integer := 0;
begin
  select * into v_game
  from public.pickem_games
  where id = p_pickem_game_id
  for update;

  if not found then
    raise exception 'Pick''em game could not be found.';
  end if;

  if not v_game.is_final then
    return jsonb_build_object('success', true, 'graded', false, 'reason', 'game_not_final');
  end if;

  if v_game.g365_home_spread is null then
    return jsonb_build_object('success', true, 'graded', false, 'reason', 'no_frozen_spread');
  end if;

  select * into v_settings from public.pickem_settings where league_id = v_game.league_id;
  v_home_ats := coalesce(v_game.home_score,0) + v_game.g365_home_spread - coalesce(v_game.away_score,0);

  update public.pickem_picks p
  set result = case
        when v_home_ats = 0 then 'push'
        when p.selected_side = 'home' and v_home_ats > 0 then 'win'
        when p.selected_side = 'away' and v_home_ats < 0 then 'win'
        else 'loss'
      end,
      points_awarded = case
        when v_home_ats = 0 then v_settings.push_points
        when p.selected_side = 'home' and v_home_ats > 0 then v_settings.win_points
        when p.selected_side = 'away' and v_home_ats < 0 then v_settings.win_points
        else v_settings.loss_points
      end,
      locked_at = coalesce(p.locked_at, v_game.kickoff_at),
      graded_at = now(),
      updated_at = now()
  where p.pickem_game_id = p_pickem_game_id
    and p.result <> 'void';

  get diagnostics v_rows = row_count;
  return jsonb_build_object('success', true, 'graded', true, 'picksGraded', v_rows);
end;
$$;

-- ============================================================
-- 12. Refresh weekly live record; finalization remains separate.
-- ============================================================

create or replace function public.refresh_pickem_week_results(p_pickem_week_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_week public.pickem_weeks%rowtype;
  v_rows integer := 0;
begin
  select * into v_week from public.pickem_weeks where id = p_pickem_week_id;
  if not found then raise exception 'Pick''em week could not be found.'; end if;

  insert into public.pickem_weekly_results (
    league_id, pickem_week_id, fantasy_team_id, wins, losses, pushes, pending, points, is_final, updated_at
  )
  select
    v_week.league_id,
    v_week.id,
    ft.id,
    count(p.id) filter (where p.result = 'win')::integer,
    count(p.id) filter (where p.result = 'loss')::integer,
    count(p.id) filter (where p.result = 'push')::integer,
    count(p.id) filter (where p.result = 'pending')::integer,
    coalesce(sum(p.points_awarded),0),
    false,
    now()
  from public.fantasy_teams ft
  left join public.pickem_picks p
    on p.fantasy_team_id = ft.id
   and p.pickem_week_id = v_week.id
  where ft.league_id = v_week.league_id
    and coalesce(ft.active,true) = true
  group by ft.id
  on conflict (pickem_week_id, fantasy_team_id)
  do update set
    wins = excluded.wins,
    losses = excluded.losses,
    pushes = excluded.pushes,
    pending = excluded.pending,
    points = excluded.points,
    updated_at = now();

  get diagnostics v_rows = row_count;
  return jsonb_build_object('success', true, 'rows', v_rows);
end;
$$;

-- ============================================================
-- 13. Finalize only AFTER Monday-night gate AND every eligible
--     game on the card is actually final.
-- ============================================================

create or replace function public.finalize_pickem_week(p_pickem_week_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_week public.pickem_weeks%rowtype;
  v_unfinished integer;
  v_user uuid := auth.uid();
begin
  select * into v_week
  from public.pickem_weeks
  where id = p_pickem_week_id
  for update;

  if not found then raise exception 'Pick''em week could not be found.'; end if;

  if v_week.status = 'final' then
    return jsonb_build_object('success', true, 'finalized', true, 'alreadyFinal', true);
  end if;

  if v_week.finalize_not_before is not null and now() < v_week.finalize_not_before then
    return jsonb_build_object('success', true, 'finalized', false, 'reason', 'monday_night_gate_not_reached');
  end if;

  select count(*) into v_unfinished
  from public.pickem_games
  where pickem_week_id = v_week.id
    and is_eligible = true
    and is_final = false;

  if v_unfinished > 0 then
    update public.pickem_weeks
      set status = 'awaiting_finalization', updated_at = now()
    where id = v_week.id;

    return jsonb_build_object('success', true, 'finalized', false, 'reason', 'games_still_unfinished', 'unfinishedGames', v_unfinished);
  end if;

  perform public.refresh_pickem_week_results(v_week.id);

  with ranked as (
    select id,
           dense_rank() over (order by points desc, wins desc, losses asc) as rnk
    from public.pickem_weekly_results
    where pickem_week_id = v_week.id
  )
  update public.pickem_weekly_results r
  set is_final = true,
      weekly_rank = ranked.rnk,
      finalized_at = now(),
      updated_at = now()
  from ranked
  where r.id = ranked.id;

  update public.pickem_weeks
  set status = 'final',
      finalized_at = now(),
      finalized_by = v_user,
      updated_at = now()
  where id = v_week.id;

  return jsonb_build_object('success', true, 'finalized', true, 'week', v_week.week);
end;
$$;

-- ============================================================
-- 14. Safe member-facing league picks view.
-- This prevents pre-kickoff leakage from direct client queries.
-- ============================================================

create or replace function public.get_pickem_league_picks(
  p_league_id uuid,
  p_season integer,
  p_week integer
)
returns table (
  fantasy_team_id bigint,
  team_name text,
  pick_id bigint,
  game_id bigint,
  sport text,
  kickoff_at timestamptz,
  away_team_name text,
  home_team_name text,
  away_score integer,
  home_score integer,
  status_type text,
  status_name text,
  status_detail text,
  period integer,
  display_clock text,
  is_final boolean,
  pick_visible boolean,
  selected_side text,
  frozen_home_spread numeric,
  pick_result text,
  points_awarded numeric
)
language sql
stable
security definer
set search_path = public, auth
as $$
  with me as (
    select auth.uid() as user_id
  ), rows as (
    select
      ft.id as fantasy_team_id,
      ft.team_name,
      ft.owner_id,
      p.id as pick_id,
      g.id as game_id,
      g.sport,
      g.kickoff_at,
      g.away_team_name,
      g.home_team_name,
      g.away_score,
      g.home_score,
      g.status_type,
      g.status_name,
      g.status_detail,
      g.period,
      g.display_clock,
      g.is_final,
      p.selected_side,
      p.frozen_home_spread,
      p.result as pick_result,
      p.points_awarded,
      (ft.owner_id = me.user_id or now() >= g.kickoff_at or g.is_started or g.is_final) as visible
    from public.fantasy_teams ft
    cross join me
    join public.league_members lm
      on lm.league_id = p_league_id
     and lm.user_id = me.user_id
    left join public.pickem_weeks w
      on w.league_id = p_league_id
     and w.season = p_season
     and w.week = p_week
    left join public.pickem_picks p
      on p.pickem_week_id = w.id
     and p.fantasy_team_id = ft.id
    left join public.pickem_games g
      on g.id = p.pickem_game_id
    where ft.league_id = p_league_id
      and coalesce(ft.active,true) = true
  )
  select
    fantasy_team_id,
    team_name,
    pick_id,
    case when visible then game_id else null end,
    case when visible then sport else null end,
    case when visible then kickoff_at else null end,
    case when visible then away_team_name else null end,
    case when visible then home_team_name else null end,
    case when visible then away_score else null end,
    case when visible then home_score else null end,
    case when visible then status_type else null end,
    case when visible then status_name else null end,
    case when visible then status_detail else null end,
    case when visible then period else null end,
    case when visible then display_clock else null end,
    case when visible then is_final else false end,
    coalesce(visible, false),
    case when visible then selected_side else null end,
    case when visible then frozen_home_spread else null end,
    case when visible then pick_result else null end,
    case when visible then points_awarded else null end
  from rows
  order by team_name,
           case when visible then kickoff_at else null end nulls last,
           pick_id;
$$;

grant execute on function public.get_pickem_league_picks(uuid,integer,integer) to authenticated;

-- ============================================================
-- 15. Commissioner settings. Picks required are configurable
--     from 1-20. Existing weeks keep their required_picks
--     snapshot; new weeks inherit the current league setting.
-- ============================================================

create or replace function public.save_pickem_settings(
  p_league_id uuid,
  p_football_scope text,
  p_picks_per_week integer,
  p_pick_lock_mode text,
  p_minimum_source_books integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user uuid := auth.uid();
  v_season integer;
begin
  if v_user is null then
    raise exception using errcode = '42501', message = 'You must be signed in.';
  end if;

  if not exists (
    select 1
    from public.league_members lm
    where lm.league_id = p_league_id
      and lm.user_id = v_user
      and lm.role in ('commissioner','co_commissioner')
  ) then
    raise exception using errcode = '42501', message = 'Commissioner access is required.';
  end if;

  select season into v_season
  from public.leagues
  where id = p_league_id
    and league_type = 'pickem';

  if not found then
    raise exception 'Pick''em league could not be found.';
  end if;

  if p_football_scope not in ('college_nfl','college_only','nfl_only') then
    raise exception using errcode = '22023', message = 'Invalid football scope.';
  end if;

  if p_picks_per_week not between 1 and 20 then
    raise exception using errcode = '22023', message = 'Picks required per week must be between 1 and 20.';
  end if;

  if p_pick_lock_mode not in ('per_game','full_card') then
    raise exception using errcode = '22023', message = 'Invalid pick lock mode.';
  end if;

  if p_minimum_source_books not between 1 and 20 then
    raise exception using errcode = '22023', message = 'Minimum sportsbook sources must be between 1 and 20.';
  end if;

  insert into public.pickem_settings (
    league_id,
    season,
    football_scope,
    picks_per_week,
    pick_lock_mode,
    minimum_source_books,
    updated_at
  ) values (
    p_league_id,
    v_season,
    p_football_scope,
    p_picks_per_week,
    p_pick_lock_mode,
    p_minimum_source_books,
    now()
  )
  on conflict (league_id)
  do update set
    football_scope = excluded.football_scope,
    picks_per_week = excluded.picks_per_week,
    pick_lock_mode = excluded.pick_lock_mode,
    minimum_source_books = excluded.minimum_source_books,
    updated_at = now();

  return jsonb_build_object(
    'success', true,
    'leagueId', p_league_id,
    'footballScope', p_football_scope,
    'picksPerWeek', p_picks_per_week,
    'pickLockMode', p_pick_lock_mode,
    'minimumSourceBooks', p_minimum_source_books
  );
end;
$$;

grant execute on function public.save_pickem_settings(uuid,text,integer,text,integer) to authenticated;


-- ============================================================
-- 16. Initialize a contest week and snapshot the current number
--     of required picks so future setting changes do not rewrite
--     a week already underway.
-- ============================================================

create or replace function public.initialize_pickem_week(
  p_league_id uuid,
  p_season integer,
  p_week integer,
  p_line_day_at timestamptz default null,
  p_finalize_not_before timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user uuid := auth.uid();
  v_required integer;
  v_week_id bigint;
begin
  if p_week not between 1 and 25 then
    raise exception using errcode = '22023', message = 'Pick''em week must be between 1 and 25.';
  end if;

  if v_user is not null and not exists (
    select 1 from public.league_members lm
    where lm.league_id = p_league_id
      and lm.user_id = v_user
      and lm.role in ('commissioner','co_commissioner')
  ) then
    raise exception using errcode = '42501', message = 'Commissioner access is required.';
  end if;

  select s.picks_per_week
  into v_required
  from public.pickem_settings s
  join public.leagues l on l.id = s.league_id
  where s.league_id = p_league_id
    and l.league_type = 'pickem'
    and l.season = p_season;

  if not found then
    raise exception 'Pick''em settings could not be found.';
  end if;

  insert into public.pickem_weeks (
    league_id, season, week, status, required_picks,
    line_day_at, finalize_not_before, updated_at
  ) values (
    p_league_id, p_season, p_week, 'setup', v_required,
    p_line_day_at, p_finalize_not_before, now()
  )
  on conflict (league_id, season, week)
  do update set
    line_day_at = coalesce(excluded.line_day_at, pickem_weeks.line_day_at),
    finalize_not_before = coalesce(excluded.finalize_not_before, pickem_weeks.finalize_not_before),
    updated_at = now()
  returning id into v_week_id;

  return jsonb_build_object(
    'success', true,
    'pickemWeekId', v_week_id,
    'requiredPicks', v_required
  );
end;
$$;

grant execute on function public.initialize_pickem_week(uuid,integer,integer,timestamptz,timestamptz) to authenticated;


-- ============================================================
-- 17. My-card status. A card is complete only when the exact
--     commissioner-configured number of picks exists.
-- ============================================================

create or replace function public.get_pickem_my_card_status(
  p_league_id uuid,
  p_season integer,
  p_week integer
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public, auth
as $$
declare
  v_user uuid := auth.uid();
  v_team_id bigint;
  v_week_id bigint;
  v_required integer;
  v_selected integer := 0;
begin
  select ft.id
  into v_team_id
  from public.fantasy_teams ft
  where ft.league_id = p_league_id
    and ft.owner_id = v_user
    and coalesce(ft.active,true) = true
  order by ft.id
  limit 1;

  if not found then
    raise exception using errcode = '42501', message = 'A Pick''em entry could not be found for this member.';
  end if;

  select w.id, w.required_picks
  into v_week_id, v_required
  from public.pickem_weeks w
  where w.league_id = p_league_id
    and w.season = p_season
    and w.week = p_week;

  if not found then
    return jsonb_build_object(
      'success', true,
      'weekReady', false,
      'selectedPicks', 0,
      'requiredPicks', coalesce((select picks_per_week from public.pickem_settings where league_id = p_league_id), 5),
      'isComplete', false
    );
  end if;

  select count(*)::integer
  into v_selected
  from public.pickem_picks p
  where p.pickem_week_id = v_week_id
    and p.fantasy_team_id = v_team_id
    and p.result <> 'void';

  return jsonb_build_object(
    'success', true,
    'weekReady', true,
    'pickemWeekId', v_week_id,
    'selectedPicks', v_selected,
    'requiredPicks', v_required,
    'remainingPicks', greatest(v_required - v_selected, 0),
    'isComplete', v_selected = v_required
  );
end;
$$;

grant execute on function public.get_pickem_my_card_status(uuid,integer,integer) to authenticated;


-- ============================================================
-- 18. Save one ATS pick. The database enforces:
--     - only the entry owner
--     - exact weekly maximum
--     - frozen official G365 spread
--     - per-game kickoff lock
--     - optional full-card lock
-- ============================================================

create or replace function public.save_pickem_pick(
  p_league_id uuid,
  p_season integer,
  p_week integer,
  p_pickem_game_id bigint,
  p_selected_side text
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user uuid := auth.uid();
  v_team_id bigint;
  v_week public.pickem_weeks%rowtype;
  v_game public.pickem_games%rowtype;
  v_lock_mode text;
  v_count integer := 0;
  v_existing_id bigint;
  v_earliest_selected_kickoff timestamptz;
begin
  if p_selected_side not in ('home','away') then
    raise exception using errcode = '22023', message = 'Pick side must be home or away.';
  end if;

  select ft.id
  into v_team_id
  from public.fantasy_teams ft
  where ft.league_id = p_league_id
    and ft.owner_id = v_user
    and coalesce(ft.active,true) = true
  order by ft.id
  limit 1;

  if not found then
    raise exception using errcode = '42501', message = 'You do not own an active entry in this Pick''em league.';
  end if;

  select * into v_week
  from public.pickem_weeks
  where league_id = p_league_id
    and season = p_season
    and week = p_week
  for update;

  if not found then
    raise exception 'Pick''em week has not been initialized.';
  end if;

  if v_week.status = 'final' then
    raise exception using errcode = '22023', message = 'This Pick''em week is already final.';
  end if;

  select * into v_game
  from public.pickem_games
  where id = p_pickem_game_id
    and league_id = p_league_id
    and pickem_week_id = v_week.id
  for update;

  if not found then
    raise exception 'Selected Pick''em game could not be found on this week''s card.';
  end if;

  if not v_game.is_eligible or v_game.spread_status <> 'frozen' or v_game.g365_home_spread is null then
    raise exception using errcode = '22023', message = 'This game does not have an eligible frozen G365 Spread.';
  end if;

  if now() >= v_game.kickoff_at or v_game.is_started or v_game.is_final then
    raise exception using errcode = '22023', message = 'This game has kicked off and the pick is locked.';
  end if;

  select s.pick_lock_mode
  into v_lock_mode
  from public.pickem_settings s
  where s.league_id = p_league_id;

  if v_lock_mode = 'full_card' then
    select min(g.kickoff_at)
    into v_earliest_selected_kickoff
    from public.pickem_picks p
    join public.pickem_games g on g.id = p.pickem_game_id
    where p.pickem_week_id = v_week.id
      and p.fantasy_team_id = v_team_id
      and p.result <> 'void';

    if v_earliest_selected_kickoff is not null and now() >= v_earliest_selected_kickoff then
      raise exception using errcode = '22023', message = 'Your full Pick''em card is locked.';
    end if;
  end if;

  select id into v_existing_id
  from public.pickem_picks
  where pickem_week_id = v_week.id
    and fantasy_team_id = v_team_id
    and pickem_game_id = v_game.id;

  if v_existing_id is null then
    select count(*)::integer into v_count
    from public.pickem_picks
    where pickem_week_id = v_week.id
      and fantasy_team_id = v_team_id
      and result <> 'void';

    if v_count >= v_week.required_picks then
      raise exception using errcode = '22023', message = format('You may select exactly %s games this week.', v_week.required_picks);
    end if;

    insert into public.pickem_picks (
      league_id,
      pickem_week_id,
      fantasy_team_id,
      pickem_game_id,
      selected_side,
      frozen_home_spread,
      submitted_at,
      updated_at
    ) values (
      p_league_id,
      v_week.id,
      v_team_id,
      v_game.id,
      p_selected_side,
      v_game.g365_home_spread,
      now(),
      now()
    );
  else
    update public.pickem_picks
    set selected_side = p_selected_side,
        frozen_home_spread = v_game.g365_home_spread,
        updated_at = now()
    where id = v_existing_id;
  end if;

  select count(*)::integer into v_count
  from public.pickem_picks
  where pickem_week_id = v_week.id
    and fantasy_team_id = v_team_id
    and result <> 'void';

  return jsonb_build_object(
    'success', true,
    'selectedPicks', v_count,
    'requiredPicks', v_week.required_picks,
    'remainingPicks', greatest(v_week.required_picks - v_count, 0),
    'isComplete', v_count = v_week.required_picks
  );
end;
$$;

grant execute on function public.save_pickem_pick(uuid,integer,integer,bigint,text) to authenticated;


create or replace function public.remove_pickem_pick(
  p_league_id uuid,
  p_season integer,
  p_week integer,
  p_pickem_game_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user uuid := auth.uid();
  v_team_id bigint;
  v_week public.pickem_weeks%rowtype;
  v_game public.pickem_games%rowtype;
  v_lock_mode text;
  v_earliest_selected_kickoff timestamptz;
  v_count integer := 0;
begin
  select ft.id into v_team_id
  from public.fantasy_teams ft
  where ft.league_id = p_league_id
    and ft.owner_id = v_user
    and coalesce(ft.active,true) = true
  order by ft.id
  limit 1;

  if not found then
    raise exception using errcode = '42501', message = 'You do not own an active entry in this Pick''em league.';
  end if;

  select * into v_week
  from public.pickem_weeks
  where league_id = p_league_id
    and season = p_season
    and week = p_week;

  if not found then raise exception 'Pick''em week has not been initialized.'; end if;

  select * into v_game
  from public.pickem_games
  where id = p_pickem_game_id
    and pickem_week_id = v_week.id;

  if not found then raise exception 'Pick''em game could not be found.'; end if;

  if now() >= v_game.kickoff_at or v_game.is_started or v_game.is_final then
    raise exception using errcode = '22023', message = 'This game has kicked off and the pick is locked.';
  end if;

  select s.pick_lock_mode into v_lock_mode
  from public.pickem_settings s
  where s.league_id = p_league_id;

  if v_lock_mode = 'full_card' then
    select min(g.kickoff_at)
    into v_earliest_selected_kickoff
    from public.pickem_picks p
    join public.pickem_games g on g.id = p.pickem_game_id
    where p.pickem_week_id = v_week.id
      and p.fantasy_team_id = v_team_id
      and p.result <> 'void';

    if v_earliest_selected_kickoff is not null and now() >= v_earliest_selected_kickoff then
      raise exception using errcode = '22023', message = 'Your full Pick''em card is locked.';
    end if;
  end if;

  delete from public.pickem_picks
  where pickem_week_id = v_week.id
    and fantasy_team_id = v_team_id
    and pickem_game_id = v_game.id;

  select count(*)::integer into v_count
  from public.pickem_picks
  where pickem_week_id = v_week.id
    and fantasy_team_id = v_team_id
    and result <> 'void';

  return jsonb_build_object(
    'success', true,
    'selectedPicks', v_count,
    'requiredPicks', v_week.required_picks,
    'remainingPicks', greatest(v_week.required_picks - v_count, 0),
    'isComplete', v_count = v_week.required_picks
  );
end;
$$;

grant execute on function public.remove_pickem_pick(uuid,integer,integer,bigint) to authenticated;


-- ============================================================
-- 15. RLS. Direct pick SELECT is owner-only; league-wide reveal
--     must go through get_pickem_league_picks() above.
-- ============================================================

alter table public.pickem_settings enable row level security;
alter table public.pickem_weeks enable row level security;
alter table public.pickem_games enable row level security;
alter table public.pickem_line_sources enable row level security;
alter table public.pickem_picks enable row level security;
alter table public.pickem_weekly_results enable row level security;
alter table public.pickem_badge_awards enable row level security;

drop policy if exists pickem_settings_member_read on public.pickem_settings;

create policy pickem_settings_member_read on public.pickem_settings
for select to authenticated using (
  exists (select 1 from public.league_members lm where lm.league_id = pickem_settings.league_id and lm.user_id = auth.uid())
);

drop policy if exists pickem_weeks_member_read on public.pickem_weeks;

create policy pickem_weeks_member_read on public.pickem_weeks
for select to authenticated using (
  exists (select 1 from public.league_members lm where lm.league_id = pickem_weeks.league_id and lm.user_id = auth.uid())
);

drop policy if exists pickem_games_member_read on public.pickem_games;

create policy pickem_games_member_read on public.pickem_games
for select to authenticated using (
  exists (select 1 from public.league_members lm where lm.league_id = pickem_games.league_id and lm.user_id = auth.uid())
);

drop policy if exists pickem_line_sources_commissioner_read on public.pickem_line_sources;

create policy pickem_line_sources_commissioner_read on public.pickem_line_sources
for select to authenticated using (
  exists (
    select 1 from public.pickem_games g
    join public.league_members lm on lm.league_id = g.league_id
    where g.id = pickem_line_sources.pickem_game_id
      and lm.user_id = auth.uid()
      and lm.role in ('commissioner','co_commissioner')
  )
);

drop policy if exists pickem_picks_owner_read on public.pickem_picks;

create policy pickem_picks_owner_read on public.pickem_picks
for select to authenticated using (
  exists (
    select 1 from public.fantasy_teams ft
    where ft.id = pickem_picks.fantasy_team_id
      and ft.owner_id = auth.uid()
  )
);

drop policy if exists pickem_picks_owner_insert on public.pickem_picks;

create policy pickem_picks_owner_insert on public.pickem_picks
for insert to authenticated with check (
  exists (
    select 1
    from public.fantasy_teams ft
    join public.pickem_games g on g.id = pickem_picks.pickem_game_id
    where ft.id = pickem_picks.fantasy_team_id
      and ft.owner_id = auth.uid()
      and ft.league_id = pickem_picks.league_id
      and g.league_id = pickem_picks.league_id
      and g.is_eligible = true
      and g.spread_status = 'frozen'
      and now() < g.kickoff_at
  )
);

drop policy if exists pickem_picks_owner_update on public.pickem_picks;

create policy pickem_picks_owner_update on public.pickem_picks
for update to authenticated
using (
  exists (
    select 1 from public.fantasy_teams ft
    join public.pickem_games g on g.id = pickem_picks.pickem_game_id
    where ft.id = pickem_picks.fantasy_team_id
      and ft.owner_id = auth.uid()
      and now() < g.kickoff_at
  )
)
with check (
  exists (
    select 1 from public.fantasy_teams ft
    join public.pickem_games g on g.id = pickem_picks.pickem_game_id
    where ft.id = pickem_picks.fantasy_team_id
      and ft.owner_id = auth.uid()
      and now() < g.kickoff_at
  )
);

drop policy if exists pickem_weekly_results_member_read on public.pickem_weekly_results;

create policy pickem_weekly_results_member_read on public.pickem_weekly_results
for select to authenticated using (
  exists (select 1 from public.league_members lm where lm.league_id = pickem_weekly_results.league_id and lm.user_id = auth.uid())
);

drop policy if exists pickem_badges_member_read on public.pickem_badge_awards;

create policy pickem_badges_member_read on public.pickem_badge_awards
for select to authenticated using (
  exists (select 1 from public.league_members lm where lm.league_id = pickem_badge_awards.league_id and lm.user_id = auth.uid())
);

-- Direct table writes are blocked for authenticated clients. Pick changes
-- go through the SECURITY DEFINER RPCs above so the weekly pick limit and
-- lock rules cannot be bypassed from the browser.
revoke insert, update, delete on public.pickem_picks from authenticated;
revoke insert, update, delete on public.pickem_settings from authenticated;

commit;
