begin;

create extension if not exists pgcrypto;

-- ============================================================
-- 1. CONTINUOUS PICK'EM HISTORY
-- ============================================================

create table if not exists public.pickem_histories (
  id uuid primary key default gen_random_uuid(),
  created_from_league_id uuid null,
  created_at timestamptz not null default now()
);

alter table public.leagues
  add column if not exists pickem_history_id uuid null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'leagues_pickem_history_id_fkey'
  ) then
    alter table public.leagues
      add constraint leagues_pickem_history_id_fkey
      foreign key (pickem_history_id)
      references public.pickem_histories(id)
      on delete set null;
  end if;
end
$$;

create index if not exists idx_leagues_pickem_history
  on public.leagues(pickem_history_id)
  where pickem_history_id is not null;


-- Every Pick'em entry keeps one permanent franchise identity.
alter table public.fantasy_teams
  add column if not exists pickem_franchise_id uuid null;

create index if not exists idx_fantasy_teams_pickem_franchise
  on public.fantasy_teams(pickem_franchise_id)
  where pickem_franchise_id is not null;


-- ============================================================
-- 2. RENEWAL LINEAGE
-- ============================================================

create table if not exists public.pickem_league_renewals (
  id bigint generated by default as identity primary key,
  source_league_id uuid not null
    references public.leagues(id)
    on delete cascade,
  target_league_id uuid not null
    references public.leagues(id)
    on delete cascade,
  source_season integer not null,
  target_season integer not null,
  renewed_by uuid null
    references auth.users(id)
    on delete set null,
  created_at timestamptz not null default now(),
  constraint pickem_league_renewals_source_target_season_unique
    unique (source_league_id, target_season),
  constraint pickem_league_renewals_target_unique
    unique (target_league_id)
);

create index if not exists idx_pickem_renewals_source
  on public.pickem_league_renewals(source_league_id);

create index if not exists idx_pickem_renewals_target
  on public.pickem_league_renewals(target_league_id);


-- ============================================================
-- 3. BACKFILL EXISTING PICK'EM LEAGUES
-- ============================================================

do $$
declare
  r record;
  v_history_id uuid;
begin
  for r in
    select l.id
    from public.leagues l
    where l.league_type = 'pickem'
      and l.pickem_history_id is null
  loop
    insert into public.pickem_histories (
      created_from_league_id
    )
    values (
      r.id
    )
    returning id into v_history_id;

    update public.leagues
    set pickem_history_id = v_history_id
    where id = r.id;
  end loop;
end
$$;

update public.fantasy_teams ft
set pickem_franchise_id = gen_random_uuid()
from public.leagues l
where l.id = ft.league_id
  and l.league_type = 'pickem'
  and ft.pickem_franchise_id is null;


-- ============================================================
-- 4. ENSURE HISTORY IDENTITY
-- ============================================================

create or replace function public.ensure_pickem_history_identity(
  p_league_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_history_id uuid;
  v_league_type text;
begin
  select
    l.league_type,
    l.pickem_history_id
  into
    v_league_type,
    v_history_id
  from public.leagues l
  where l.id = p_league_id;

  if not found then
    raise exception 'League could not be found.';
  end if;

  if v_league_type <> 'pickem' then
    raise exception 'Pick''em history identity is only available for Pick''em leagues.';
  end if;

  if v_history_id is null then
    insert into public.pickem_histories (
      created_from_league_id
    )
    values (
      p_league_id
    )
    returning id into v_history_id;

    update public.leagues
    set pickem_history_id = v_history_id
    where id = p_league_id;
  end if;

  update public.fantasy_teams
  set pickem_franchise_id = gen_random_uuid()
  where league_id = p_league_id
    and pickem_franchise_id is null;

  return v_history_id;
end;
$function$;

revoke all
on function public.ensure_pickem_history_identity(uuid)
from public, anon;

grant execute
on function public.ensure_pickem_history_identity(uuid)
to authenticated, service_role;


-- ============================================================
-- 5. CONTINUOUS TROPHY CASE
-- ============================================================
-- Returns the ORIGINAL badge rows. Nothing is copied into the new
-- season. This prevents duplicate trophies while still allowing a
-- renewed 2027 league to display 2026 + 2027 achievements.

create or replace function public.get_pickem_history_trophy_case(
  p_league_id uuid
)
returns table (
  id bigint,
  league_id uuid,
  fantasy_team_id bigint,
  franchise_id uuid,
  team_name text,
  season integer,
  week integer,
  badge_key text,
  badge_name text,
  badge_category text,
  details jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_history_id uuid;
begin
  select l.pickem_history_id
  into v_history_id
  from public.leagues l
  where l.id = p_league_id
    and l.league_type = 'pickem';

  if not found then
    raise exception 'Pick''em league could not be found.';
  end if;

  -- Members may view their league's shared trophy case.
  if auth.role() <> 'service_role'
     and not exists (
       select 1
       from public.league_members lm
       where lm.league_id = p_league_id
         and lm.user_id = auth.uid()
     )
     and not exists (
       select 1
       from public.leagues l
       where l.id = p_league_id
         and l.commissioner_user_id = auth.uid()
     )
  then
    raise exception 'League membership is required.';
  end if;

  return query
  with history_leagues as (
    select l.id, l.season
    from public.leagues l
    where
      (
        v_history_id is not null
        and l.pickem_history_id = v_history_id
      )
      or
      (
        v_history_id is null
        and l.id = p_league_id
      )
  ),
  badge_rows as (
    select
      b.id,
      b.league_id,
      b.fantasy_team_id,
      ft.pickem_franchise_id as franchise_id,
      b.season,
      b.week,
      b.badge_key,
      b.badge_name,
      b.badge_category,
      b.details,
      b.created_at
    from history_leagues hl
    join public.pickem_badge_awards b
      on b.league_id = hl.id
    join public.fantasy_teams ft
      on ft.id = b.fantasy_team_id
     and ft.league_id = b.league_id
  )
  select
    br.id,
    br.league_id,
    br.fantasy_team_id,
    br.franchise_id,
    coalesce(
      latest_team.team_name,
      source_team.team_name
    )::text as team_name,
    br.season,
    br.week,
    br.badge_key,
    br.badge_name,
    br.badge_category,
    br.details,
    br.created_at
  from badge_rows br
  join public.fantasy_teams source_team
    on source_team.id = br.fantasy_team_id
  left join lateral (
    select ft2.team_name
    from public.fantasy_teams ft2
    join public.leagues l2
      on l2.id = ft2.league_id
    where br.franchise_id is not null
      and ft2.pickem_franchise_id = br.franchise_id
      and (
        (
          v_history_id is not null
          and l2.pickem_history_id = v_history_id
        )
        or
        (
          v_history_id is null
          and l2.id = p_league_id
        )
      )
    order by l2.season desc, ft2.id desc
    limit 1
  ) latest_team on true
  order by br.season desc, br.week desc, br.id desc;
end;
$function$;

revoke all
on function public.get_pickem_history_trophy_case(uuid)
from public, anon;

grant execute
on function public.get_pickem_history_trophy_case(uuid)
to authenticated, service_role;


-- ============================================================
-- 6. RENEW PICK'EM LEAGUE — ONE DATABASE TRANSACTION
-- ============================================================

create or replace function public.renew_pickem_league(
  p_source_league_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_user_id uuid := auth.uid();
  v_source public.leagues%rowtype;
  v_history_id uuid;
  v_target_season integer;
  v_target_league_id uuid;
  v_existing_target uuid;
  v_total_weeks integer;
  v_unfinished_weeks integer;
begin
  if v_user_id is null then
    raise exception 'You must be signed in.';
  end if;

  select *
  into v_source
  from public.leagues
  where id = p_source_league_id
  for update;

  if not found then
    raise exception 'League could not be found.';
  end if;

  if v_source.league_type <> 'pickem' then
    raise exception 'This renewal function is only available for Pick''em leagues.';
  end if;

  if v_source.commissioner_user_id <> v_user_id then
    raise exception 'Commissioner access is required.';
  end if;

  v_target_season := v_source.season + 1;

  -- Idempotency: repeated clicks return the already-created next season.
  select r.target_league_id
  into v_existing_target
  from public.pickem_league_renewals r
  where r.source_league_id = p_source_league_id
    and r.target_season = v_target_season
  limit 1;

  if v_existing_target is not null then
    return jsonb_build_object(
      'success', true,
      'alreadyRenewed', true,
      'leagueId', v_existing_target,
      'season', v_target_season
    );
  end if;

  select
    count(*)::integer,
    count(*) filter (where w.status <> 'final')::integer
  into
    v_total_weeks,
    v_unfinished_weeks
  from public.pickem_weeks w
  where w.league_id = p_source_league_id
    and w.season = v_source.season;

  if v_total_weeks = 0 then
    raise exception 'The current Pick''em season has not been prepared yet.';
  end if;

  if v_unfinished_weeks > 0 then
    raise exception 'The current Pick''em season must be completely finalized before renewal.';
  end if;

  v_history_id :=
    public.ensure_pickem_history_identity(
      p_source_league_id
    );

  insert into public.leagues (
    name,
    league_type,
    season,
    commissioner_user_id,
    status,
    player_selection_mode,
    pickem_history_id
  )
  values (
    v_source.name,
    'pickem',
    v_target_season,
    v_source.commissioner_user_id,
    'setup',
    v_source.player_selection_mode,
    v_history_id
  )
  returning id into v_target_league_id;

  -- Membership carries forward.
  insert into public.league_members (
    league_id,
    user_id,
    role
  )
  select
    v_target_league_id,
    lm.user_id,
    lm.role
  from public.league_members lm
  where lm.league_id = p_source_league_id
  on conflict (league_id, user_id) do nothing;

  -- Active Pick'em entries carry forward with the SAME franchise identity.
  insert into public.fantasy_teams (
    league_id,
    owner_id,
    team_name,
    active,
    is_cpu,
    pickem_franchise_id
  )
  select
    v_target_league_id,
    ft.owner_id,
    ft.team_name,
    true,
    ft.is_cpu,
    ft.pickem_franchise_id
  from public.fantasy_teams ft
  where ft.league_id = p_source_league_id
    and ft.active = true;

  -- Commissioner settings become the defaults for the new season.
  insert into public.pickem_settings (
    league_id,
    season,
    football_scope,
    picks_per_week,
    line_day_dow,
    line_day_hour_et,
    pick_lock_mode,
    reveal_mode,
    push_points,
    win_points,
    loss_points,
    require_trustworthy_consensus,
    minimum_source_books,
    scoring_mode,
    confidence_points,
    confidence_push_multiplier,
    missing_pick_policy
  )
  select
    v_target_league_id,
    v_target_season,
    ps.football_scope,
    ps.picks_per_week,
    ps.line_day_dow,
    ps.line_day_hour_et,
    ps.pick_lock_mode,
    ps.reveal_mode,
    ps.push_points,
    ps.win_points,
    ps.loss_points,
    ps.require_trustworthy_consensus,
    ps.minimum_source_books,
    ps.scoring_mode,
    ps.confidence_points,
    ps.confidence_push_multiplier,
    ps.missing_pick_policy
  from public.pickem_settings ps
  where ps.league_id = p_source_league_id;

  if not found then
    raise exception 'Pick''em settings could not be found for the source league.';
  end if;

  insert into public.pickem_league_renewals (
    source_league_id,
    target_league_id,
    source_season,
    target_season,
    renewed_by
  )
  values (
    p_source_league_id,
    v_target_league_id,
    v_source.season,
    v_target_season,
    v_user_id
  );

  -- Intentionally NOT copied:
  --   pickem_weeks
  --   pickem_games
  --   pickem_line_sources
  --   pickem_picks
  --   pickem_weekly_results
  --   pickem_badge_awards
  --
  -- New weeks/games/lines are prepared by the normal automatic lifecycle.
  -- Historical badges remain in their original season and are surfaced through
  -- get_pickem_history_trophy_case().

  return jsonb_build_object(
    'success', true,
    'alreadyRenewed', false,
    'leagueId', v_target_league_id,
    'season', v_target_season,
    'historyId', v_history_id
  );
end;
$function$;

revoke all
on function public.renew_pickem_league(uuid)
from public, anon;

grant execute
on function public.renew_pickem_league(uuid)
to authenticated;


-- ============================================================
-- 7. HISTORY SUMMARY (USEFUL FOR QA / FUTURE UI)
-- ============================================================

create or replace function public.get_pickem_history_summary(
  p_league_id uuid
)
returns table (
  history_id uuid,
  first_season integer,
  latest_season integer,
  season_count bigint,
  total_badges bigint
)
language sql
security definer
set search_path = public
as $function$
  with target as (
    select l.pickem_history_id
    from public.leagues l
    where l.id = p_league_id
      and l.league_type = 'pickem'
  ),
  history_leagues as (
    select l.id, l.season, l.pickem_history_id
    from public.leagues l
    cross join target t
    where
      (
        t.pickem_history_id is not null
        and l.pickem_history_id = t.pickem_history_id
      )
      or
      (
        t.pickem_history_id is null
        and l.id = p_league_id
      )
  )
  select
    (
      select t.pickem_history_id
      from target t
      limit 1
    ) as history_id,
    min(hl.season)::integer as first_season,
    max(hl.season)::integer as latest_season,
    count(distinct hl.id) as season_count,
    (
      select count(*)
      from public.pickem_badge_awards b
      where b.league_id in (
        select id
        from history_leagues
      )
    ) as total_badges
  from history_leagues hl;
$function$;

revoke all
on function public.get_pickem_history_summary(uuid)
from public, anon;

grant execute
on function public.get_pickem_history_summary(uuid)
to authenticated, service_role;

notify pgrst, 'reload schema';

commit;