begin;

-- ============================================================
-- G365 NFL PLAYOFFS
-- STAGE 1B
--
-- Real NFL postseason schedule mapping
-- Active-round lifecycle
-- Real NFL bracket/game foundation
-- Surviving-team eligibility
--
-- ESPN postseason:
-- season_type 3
-- Wild Card      = week 1
-- Divisional     = week 2
-- Conference     = week 3
-- Super Bowl     = week 5
-- ============================================================


-- ============================================================
-- 1. REAL NFL PLAYOFF GAME MAP
--
-- This powers the "2026 NFL Playoffs" tab.
-- nfl_game_id points to the existing nfl_games record.
-- ============================================================

create table if not exists public.nfl_playoff_games (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    season integer not null,

    round_number integer not null,

    nfl_week integer not null,

    nfl_game_id bigint not null
        references public.nfl_games(id)
        on delete cascade,

    bracket_order integer not null default 1,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nfl_playoff_games_unique
        unique (
            league_id,
            season,
            nfl_game_id
        ),

    constraint nfl_playoff_games_round_check
        check (
            round_number between 1 and 4
        ),

    constraint nfl_playoff_games_order_check
        check (
            bracket_order >= 1
        )
);


create index if not exists
    nfl_playoff_games_round_idx
on public.nfl_playoff_games (
    league_id,
    season,
    round_number,
    bracket_order
);


-- ============================================================
-- 2. POSTSEASON WEEK MAPPING HELPER
-- ============================================================

create or replace function public.get_nfl_playoff_provider_week(
    p_round_number integer
)
returns integer
language sql
immutable
as $$
    select
        case p_round_number
            when 1 then 1
            when 2 then 2
            when 3 then 3
            when 4 then 5
            else null
        end;
$$;


-- ============================================================
-- 3. EXPECTED GAME COUNT HELPER
-- ============================================================

create or replace function public.get_nfl_playoff_expected_game_count(
    p_round_number integer
)
returns integer
language sql
immutable
as $$
    select
        case p_round_number
            when 1 then 6
            when 2 then 4
            when 3 then 2
            when 4 then 1
            else 0
        end;
$$;


-- ============================================================
-- 4. SYNC REAL NFL GAMES INTO A LEAGUE'S PLAYOFF BRACKET
-- ============================================================

create or replace function public.sync_nfl_playoff_games(
    p_league_id uuid,
    p_season integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_inserted integer := 0;
    v_total integer := 0;
begin

    if not exists (
        select 1
        from public.leagues l
        where l.id = p_league_id
          and l.league_type = 'nfl_playoffs'
          and l.season = p_season
    ) then
        raise exception
            'NFL Playoffs league could not be found.';
    end if;


    insert into public.nfl_playoff_games (
        league_id,
        season,
        round_number,
        nfl_week,
        nfl_game_id,
        bracket_order
    )
    select
        p_league_id,
        p_season,

        case g.week
            when 1 then 1
            when 2 then 2
            when 3 then 3
            when 5 then 4
        end,

        g.week,
        g.id,

        row_number() over (
            partition by g.week
            order by
                g.kickoff_at,
                g.id
        )::integer

    from public.nfl_games g

    where g.season = p_season
      and g.season_type = 3
      and g.week in (1, 2, 3, 5)

    on conflict (
        league_id,
        season,
        nfl_game_id
    )
    do update set
        round_number =
            excluded.round_number,

        nfl_week =
            excluded.nfl_week,

        bracket_order =
            excluded.bracket_order,

        updated_at =
            now();


    get diagnostics
        v_inserted = row_count;


    select count(*)
    into v_total
    from public.nfl_playoff_games pg
    where pg.league_id = p_league_id
      and pg.season = p_season;


    return jsonb_build_object(
        'success', true,
        'leagueId', p_league_id,
        'season', p_season,
        'rowsSynced', v_inserted,
        'totalBracketGames', v_total
    );
end;
$$;


-- ============================================================
-- 5. SYNC ROUND SCHEDULE METADATA
-- ============================================================

create or replace function public.sync_nfl_playoff_round_schedule(
    p_league_id uuid,
    p_season integer
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_round integer;
    v_week integer;
    v_first timestamptz;
    v_last timestamptz;
    v_games integer;
begin

    for v_round in 1..4 loop

        v_week :=
            public.get_nfl_playoff_provider_week(
                v_round
            );


        select
            min(g.kickoff_at),
            max(g.kickoff_at),
            count(*)
        into
            v_first,
            v_last,
            v_games
        from public.nfl_games g
        where g.season = p_season
          and g.season_type = 3
          and g.week = v_week;


        update public.nfl_playoff_rounds r
        set
            nfl_week = v_week,

            first_kickoff_at =
                v_first,

            last_scheduled_kickoff_at =
                v_last,

            opens_at =
                case
                    when v_first is not null
                        then v_first - interval '7 days'
                    else r.opens_at
                end,

            updated_at =
                now()

        where r.league_id = p_league_id
          and r.season = p_season
          and r.round_number = v_round;

    end loop;


    return jsonb_build_object(
        'success', true,
        'leagueId', p_league_id,
        'season', p_season
    );
end;
$$;


-- ============================================================
-- 6. CHECK WHETHER AN NFL ROUND IS FULLY FINAL
--
-- Requires:
--   correct expected number of games
--   every game status_completed = true
--
-- This prevents early fantasy-round advancement.
-- ============================================================

create or replace function public.is_nfl_playoff_round_final(
    p_season integer,
    p_round_number integer
)
returns boolean
language plpgsql
stable
set search_path = ''
as $$
declare
    v_week integer;
    v_expected integer;
    v_total integer;
    v_final integer;
begin

    v_week :=
        public.get_nfl_playoff_provider_week(
            p_round_number
        );

    v_expected :=
        public.get_nfl_playoff_expected_game_count(
            p_round_number
        );


    select
        count(*),
        count(*) filter (
            where g.status_completed = true
        )
    into
        v_total,
        v_final
    from public.nfl_games g
    where g.season = p_season
      and g.season_type = 3
      and g.week = v_week;


    return
        v_total = v_expected
        and v_final = v_expected;
end;
$$;


-- ============================================================
-- 7. GET TEAMS PARTICIPATING IN A ROUND
--
-- These are REAL NFL teams, not fantasy teams.
-- This becomes the eligibility foundation for the player pool.
-- ============================================================

create or replace function public.get_nfl_playoff_round_team_ids(
    p_season integer,
    p_round_number integer
)
returns table (
    nfl_team_id bigint
)
language sql
stable
set search_path = ''
as $$
    with round_games as (
        select
            g.home_team_id,
            g.away_team_id
        from public.nfl_games g
        where g.season = p_season
          and g.season_type = 3
          and g.week =
              public.get_nfl_playoff_provider_week(
                  p_round_number
              )
    )

    select home_team_id
    from round_games

    union

    select away_team_id
    from round_games;
$$;


-- ============================================================
-- 8. INITIALIZE / PREPARE POSTSEASON
--
-- Runs the Stage 1A initializer first, then maps actual
-- postseason games and schedule.
-- ============================================================

create or replace function public.prepare_nfl_playoff_season(
    p_league_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_league public.leagues%rowtype;
    v_game_sync jsonb;
begin

    select *
    into v_league
    from public.leagues l
    where l.id = p_league_id;


    if not found then
        raise exception
            'League could not be found.';
    end if;


    if v_league.league_type <> 'nfl_playoffs' then
        raise exception
            'League is not an NFL Playoffs league.';
    end if;


    perform
        public.initialize_nfl_playoff_league(
            p_league_id
        );


    v_game_sync :=
        public.sync_nfl_playoff_games(
            p_league_id,
            v_league.season
        );


    perform
        public.sync_nfl_playoff_round_schedule(
            p_league_id,
            v_league.season
        );


    -- Wild Card is the initial active round.
    update public.nfl_playoff_rounds r
    set
        status =
            case
                when r.round_number = 1
                    then 'open'
                else 'pending'
            end,

        updated_at =
            now()

    where r.league_id = p_league_id
      and r.season = v_league.season
      and r.finalized_at is null;


    update public.nfl_playoff_league_state s
    set
        active_round = 1,
        status = 'active',
        updated_at = now()
    where s.league_id = p_league_id;


    return jsonb_build_object(
        'success', true,
        'leagueId', p_league_id,
        'season', v_league.season,
        'activeRound', 1,
        'activeRoundName', 'Wild Card',
        'gameSync', v_game_sync
    );
end;
$$;


-- ============================================================
-- 9. MARK ROUND LIVE
-- ============================================================

create or replace function public.refresh_nfl_playoff_round_status(
    p_league_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_season integer;
    v_round integer;
    v_first timestamptz;
    v_final boolean;
    v_status text;
begin

    select
        s.season,
        s.active_round
    into
        v_season,
        v_round
    from public.nfl_playoff_league_state s
    where s.league_id = p_league_id;


    if not found then
        raise exception
            'NFL Playoffs league state could not be found.';
    end if;


    select r.first_kickoff_at
    into v_first
    from public.nfl_playoff_rounds r
    where r.league_id = p_league_id
      and r.season = v_season
      and r.round_number = v_round;


    v_final :=
        public.is_nfl_playoff_round_final(
            v_season,
            v_round
        );


    if v_final then
        v_status := 'finalizing';

    elsif v_first is not null
      and now() >= v_first then
        v_status := 'live';

    else
        v_status := 'open';
    end if;


    update public.nfl_playoff_rounds r
    set
        status = v_status,
        updated_at = now()
    where r.league_id = p_league_id
      and r.season = v_season
      and r.round_number = v_round
      and r.status <> 'final';


    return jsonb_build_object(
        'success', true,
        'leagueId', p_league_id,
        'season', v_season,
        'round', v_round,
        'roundName',
            public.get_nfl_playoff_round_name(
                v_round
            ),
        'status', v_status,
        'allNflGamesFinal', v_final
    );
end;
$$;


-- ============================================================
-- 10. ADVANCE A COMPLETED ROUND
--
-- IMPORTANT:
-- This function does NOT calculate fantasy scoring.
--
-- Stage 3 scoring finalization will call this only AFTER:
--   fantasy scores refreshed
--   standings rebuilt
--   recap/badges completed
--
-- For now it establishes safe round advancement.
-- ============================================================

create or replace function public.advance_nfl_playoff_round(
    p_league_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_season integer;
    v_round integer;
    v_next_round integer;
    v_is_final boolean;
begin

    select
        s.season,
        s.active_round
    into
        v_season,
        v_round
    from public.nfl_playoff_league_state s
    where s.league_id = p_league_id
    for update;


    if not found then
        raise exception
            'NFL Playoffs league state could not be found.';
    end if;


    v_is_final :=
        public.is_nfl_playoff_round_final(
            v_season,
            v_round
        );


    if not v_is_final then
        return jsonb_build_object(
            'success', true,
            'advanced', false,
            'leagueId', p_league_id,
            'season', v_season,
            'round', v_round,
            'reason',
                'NFL playoff round is not final.'
        );
    end if;


    update public.nfl_playoff_rounds r
    set
        status = 'final',
        finalized_at =
            coalesce(
                r.finalized_at,
                now()
            ),
        updated_at = now()
    where r.league_id = p_league_id
      and r.season = v_season
      and r.round_number = v_round;


    -- Super Bowl completed.
    if v_round = 4 then

        update public.nfl_playoff_league_state s
        set
            status = 'complete',
            completed_at =
                coalesce(
                    s.completed_at,
                    now()
                ),
            updated_at = now()
        where s.league_id = p_league_id;


        return jsonb_build_object(
            'success', true,
            'advanced', false,
            'completed', true,
            'leagueId', p_league_id,
            'season', v_season,
            'completedRound', 4,
            'completedRoundName', 'Super Bowl'
        );

    end if;


    v_next_round :=
        v_round + 1;


    -- Refresh schedule because the next NFL matchups may only
    -- have become available after the prior round completed.
    perform
        public.sync_nfl_playoff_games(
            p_league_id,
            v_season
        );

    perform
        public.sync_nfl_playoff_round_schedule(
            p_league_id,
            v_season
        );


    update public.nfl_playoff_rounds r
    set
        status = 'open',
        updated_at = now()
    where r.league_id = p_league_id
      and r.season = v_season
      and r.round_number = v_next_round;


    update public.nfl_playoff_league_state s
    set
        active_round = v_next_round,
        status = 'active',
        updated_at = now()
    where s.league_id = p_league_id;


    return jsonb_build_object(
        'success', true,
        'advanced', true,
        'leagueId', p_league_id,
        'season', v_season,
        'completedRound', v_round,
        'activeRound', v_next_round,
        'activeRoundName',
            public.get_nfl_playoff_round_name(
                v_next_round
            )
    );
end;
$$;


commit;