-- ============================================================
-- GRIDIRON365
-- NHL SHARED DATA FOUNDATION — MIGRATION 1
--
-- Shared by:
--   1. G365 NHL Pick'em
--   2. NHL Season-Long Salary
--   3. NHL Season-Long No-Salary
--   4. NHL Traditional
--
-- This migration intentionally does NOT modify any NFL tables,
-- Football Pick'em tables, or existing fantasy league records.
-- ============================================================


-- ============================================================
-- 1. NHL TEAMS
-- ============================================================

create table if not exists public.nhl_teams (
    id bigint generated by default as identity primary key,

    espn_team_id text unique,

    abbreviation text not null,
    name text not null,
    display_name text not null,
    short_name text,

    location text,

    conference text,
    division text,

    logo_url text,

    active boolean not null default true,

    provider_data jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);


create unique index if not exists nhl_teams_abbreviation_unique
    on public.nhl_teams (
        upper(abbreviation)
    );


create index if not exists nhl_teams_active_idx
    on public.nhl_teams (
        active
    );


create index if not exists nhl_teams_conference_division_idx
    on public.nhl_teams (
        conference,
        division
    );


-- ============================================================
-- 2. NHL PLAYERS
-- ============================================================

create table if not exists public.nhl_players (
    id bigint generated by default as identity primary key,

    espn_athlete_id text unique,

    team_id bigint
        references public.nhl_teams(id)
        on delete set null,

    first_name text,
    last_name text,

    display_name text not null,
    short_name text,

    jersey_number text,

    position text,

    /*
     * Normalized G365 position group.
     *
     * Expected values:
     *   FORWARD
     *   DEFENSE
     *   GOALIE
     *
     * position retains the player's more specific position:
     *   C
     *   LW
     *   RW
     *   D
     *   G
     *
     * This allows NHL Season-Long leagues to support:
     *
     * Default:
     *   C / LW / RW / D / G
     *
     * Commissioner flexible mode:
     *   Forward / Defense / Goalie
     */
    position_group text,

    shoots_catches text,

    active boolean not null default true,

    status text,
    injury_status text,

    headshot_url text,

    provider_data jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nhl_players_position_group_check
        check (
            position_group is null
            or position_group in (
                'FORWARD',
                'DEFENSE',
                'GOALIE'
            )
        )
);


create index if not exists nhl_players_team_id_idx
    on public.nhl_players (
        team_id
    );


create index if not exists nhl_players_position_idx
    on public.nhl_players (
        position
    );


create index if not exists nhl_players_position_group_idx
    on public.nhl_players (
        position_group
    );


create index if not exists nhl_players_active_idx
    on public.nhl_players (
        active
    );


create index if not exists nhl_players_team_active_idx
    on public.nhl_players (
        team_id,
        active
    );


-- ============================================================
-- 3. NHL GAMES
-- ============================================================

create table if not exists public.nhl_games (
    id bigint generated by default as identity primary key,

    espn_event_id text unique,

    season integer not null,

    /*
     * Normalized season stage.
     *
     * Expected values initially:
     *   preseason
     *   regular
     *   postseason
     *
     * Provider-specific values remain in provider_data.
     */
    season_type text not null default 'regular',

    game_date date,

    kickoff_at timestamptz not null,

    away_team_id bigint
        references public.nhl_teams(id)
        on delete restrict,

    home_team_id bigint
        references public.nhl_teams(id)
        on delete restrict,

    away_score integer not null default 0,
    home_score integer not null default 0,

    status_type text,
    status_name text,
    status_detail text,

    /*
     * NHL period:
     *   1
     *   2
     *   3
     *   overtime periods as supplied by provider
     */
    period integer,

    display_clock text,

    status_completed boolean not null default false,

    /*
     * Hockey-specific game state.
     */
    is_overtime boolean not null default false,
    is_shootout boolean not null default false,

    venue_name text,

    provider_data jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nhl_games_different_teams_check
        check (
            home_team_id is null
            or away_team_id is null
            or home_team_id <> away_team_id
        )
);


create index if not exists nhl_games_season_idx
    on public.nhl_games (
        season
    );


create index if not exists nhl_games_season_type_idx
    on public.nhl_games (
        season,
        season_type
    );


create index if not exists nhl_games_kickoff_at_idx
    on public.nhl_games (
        kickoff_at
    );


create index if not exists nhl_games_home_team_idx
    on public.nhl_games (
        home_team_id
    );


create index if not exists nhl_games_away_team_idx
    on public.nhl_games (
        away_team_id
    );


create index if not exists nhl_games_status_completed_idx
    on public.nhl_games (
        status_completed
    );


create index if not exists nhl_games_live_lookup_idx
    on public.nhl_games (
        season,
        status_completed,
        kickoff_at
    );


-- ============================================================
-- 4. NHL PLAYER GAME STATS
-- ============================================================

create table if not exists public.nhl_player_game_stats (
    id bigint generated by default as identity primary key,

    nhl_game_id bigint not null
        references public.nhl_games(id)
        on delete cascade,

    nhl_player_id bigint not null
        references public.nhl_players(id)
        on delete cascade,

    team_id bigint
        references public.nhl_teams(id)
        on delete set null,

    season integer not null,

    season_type text not null default 'regular',

    position text,
    position_group text,

    /*
     * ========================================================
     * SKATER STATS
     * ========================================================
     */

    goals numeric not null default 0,
    assists numeric not null default 0,

    points numeric not null default 0,

    plus_minus numeric not null default 0,

    penalty_minutes numeric not null default 0,

    power_play_goals numeric not null default 0,
    power_play_assists numeric not null default 0,
    power_play_points numeric not null default 0,

    short_handed_goals numeric not null default 0,
    short_handed_assists numeric not null default 0,
    short_handed_points numeric not null default 0,

    game_winning_goals numeric not null default 0,

    shots_on_goal numeric not null default 0,

    hits numeric not null default 0,

    blocked_shots numeric not null default 0,

    takeaways numeric not null default 0,
    giveaways numeric not null default 0,

    faceoff_wins numeric not null default 0,
    faceoff_losses numeric not null default 0,

    shifts numeric not null default 0,

    /*
     * Store time on ice as seconds for clean scoring,
     * sorting and aggregation.
     */
    time_on_ice_seconds integer not null default 0,


    /*
     * ========================================================
     * GOALIE STATS
     * ========================================================
     */

    goalie_started boolean not null default false,

    goalie_decision text,

    saves numeric not null default 0,

    shots_against numeric not null default 0,

    goals_against numeric not null default 0,

    save_percentage numeric,

    goalie_minutes_seconds integer not null default 0,

    goalie_win numeric not null default 0,
    goalie_loss numeric not null default 0,
    goalie_overtime_loss numeric not null default 0,

    shutout numeric not null default 0,


    /*
     * ========================================================
     * PROVIDER / LIVE STATE
     * ========================================================
     */

    is_final boolean not null default false,

    raw_stats jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nhl_player_game_stats_unique_player_game
        unique (
            nhl_game_id,
            nhl_player_id
        ),

    constraint nhl_player_game_stats_position_group_check
        check (
            position_group is null
            or position_group in (
                'FORWARD',
                'DEFENSE',
                'GOALIE'
            )
        ),

    constraint nhl_player_game_stats_goalie_decision_check
        check (
            goalie_decision is null
            or goalie_decision in (
                'W',
                'L',
                'OTL',
                'ND'
            )
        )
);


create index if not exists nhl_player_game_stats_game_idx
    on public.nhl_player_game_stats (
        nhl_game_id
    );


create index if not exists nhl_player_game_stats_player_idx
    on public.nhl_player_game_stats (
        nhl_player_id
    );


create index if not exists nhl_player_game_stats_team_idx
    on public.nhl_player_game_stats (
        team_id
    );


create index if not exists nhl_player_game_stats_season_idx
    on public.nhl_player_game_stats (
        season
    );


create index if not exists nhl_player_game_stats_player_season_idx
    on public.nhl_player_game_stats (
        nhl_player_id,
        season
    );


create index if not exists nhl_player_game_stats_game_final_idx
    on public.nhl_player_game_stats (
        nhl_game_id,
        is_final
    );


-- ============================================================
-- 5. NHL TEAM GAME STATS
--
-- Useful for:
--   Pick'em
--   live game cards
--   future team-based scoring
--   standings/tiebreak context
-- ============================================================

create table if not exists public.nhl_team_game_stats (
    id bigint generated by default as identity primary key,

    nhl_game_id bigint not null
        references public.nhl_games(id)
        on delete cascade,

    team_id bigint not null
        references public.nhl_teams(id)
        on delete cascade,

    opponent_team_id bigint
        references public.nhl_teams(id)
        on delete set null,

    season integer not null,
    season_type text not null default 'regular',

    is_home boolean not null default false,

    goals numeric not null default 0,

    shots_on_goal numeric not null default 0,

    power_play_goals numeric not null default 0,
    power_play_opportunities numeric not null default 0,

    penalty_minutes numeric not null default 0,

    hits numeric not null default 0,

    blocked_shots numeric not null default 0,

    faceoff_wins numeric not null default 0,

    takeaways numeric not null default 0,
    giveaways numeric not null default 0,

    goalie_saves numeric not null default 0,

    is_final boolean not null default false,

    raw_stats jsonb not null default '{}'::jsonb,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nhl_team_game_stats_unique_team_game
        unique (
            nhl_game_id,
            team_id
        )
);


create index if not exists nhl_team_game_stats_game_idx
    on public.nhl_team_game_stats (
        nhl_game_id
    );


create index if not exists nhl_team_game_stats_team_idx
    on public.nhl_team_game_stats (
        team_id
    );


-- ============================================================
-- 6. UPDATED_AT TRIGGER
--
-- NHL-specific function so we do not touch any shared/NFL
-- timestamp trigger behavior.
-- ============================================================

create or replace function private.touch_nhl_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public, private
as $$
begin
    new.updated_at := now();

    return new;
end;
$$;


drop trigger if exists trg_nhl_teams_updated_at
on public.nhl_teams;

create trigger trg_nhl_teams_updated_at
before update
on public.nhl_teams
for each row
execute function private.touch_nhl_updated_at();


drop trigger if exists trg_nhl_players_updated_at
on public.nhl_players;

create trigger trg_nhl_players_updated_at
before update
on public.nhl_players
for each row
execute function private.touch_nhl_updated_at();


drop trigger if exists trg_nhl_games_updated_at
on public.nhl_games;

create trigger trg_nhl_games_updated_at
before update
on public.nhl_games
for each row
execute function private.touch_nhl_updated_at();


drop trigger if exists trg_nhl_player_game_stats_updated_at
on public.nhl_player_game_stats;

create trigger trg_nhl_player_game_stats_updated_at
before update
on public.nhl_player_game_stats
for each row
execute function private.touch_nhl_updated_at();


drop trigger if exists trg_nhl_team_game_stats_updated_at
on public.nhl_team_game_stats;

create trigger trg_nhl_team_game_stats_updated_at
before update
on public.nhl_team_game_stats
for each row
execute function private.touch_nhl_updated_at();


-- ============================================================
-- 7. ROW LEVEL SECURITY
--
-- NHL sports data is shared reference/game data.
-- Authenticated G365 members can read it.
--
-- Server/service-role synchronization will perform writes.
-- ============================================================

alter table public.nhl_teams
enable row level security;

alter table public.nhl_players
enable row level security;

alter table public.nhl_games
enable row level security;

alter table public.nhl_player_game_stats
enable row level security;

alter table public.nhl_team_game_stats
enable row level security;


drop policy if exists
    "Authenticated users can read NHL teams"
on public.nhl_teams;

create policy
    "Authenticated users can read NHL teams"
on public.nhl_teams
for select
to authenticated
using (true);


drop policy if exists
    "Authenticated users can read NHL players"
on public.nhl_players;

create policy
    "Authenticated users can read NHL players"
on public.nhl_players
for select
to authenticated
using (true);


drop policy if exists
    "Authenticated users can read NHL games"
on public.nhl_games;

create policy
    "Authenticated users can read NHL games"
on public.nhl_games
for select
to authenticated
using (true);


drop policy if exists
    "Authenticated users can read NHL player game stats"
on public.nhl_player_game_stats;

create policy
    "Authenticated users can read NHL player game stats"
on public.nhl_player_game_stats
for select
to authenticated
using (true);


drop policy if exists
    "Authenticated users can read NHL team game stats"
on public.nhl_team_game_stats;

create policy
    "Authenticated users can read NHL team game stats"
on public.nhl_team_game_stats
for select
to authenticated
using (true);


-- ============================================================
-- 8. SUPABASE REALTIME
--
-- This gives us the same live-update foundation we established
-- for NFL.
-- ============================================================

do $$
begin

    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'nhl_teams'
    ) then
        execute
            'alter publication supabase_realtime add table public.nhl_teams';
    end if;


    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'nhl_players'
    ) then
        execute
            'alter publication supabase_realtime add table public.nhl_players';
    end if;


    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'nhl_games'
    ) then
        execute
            'alter publication supabase_realtime add table public.nhl_games';
    end if;


    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'nhl_player_game_stats'
    ) then
        execute
            'alter publication supabase_realtime add table public.nhl_player_game_stats';
    end if;


    if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = 'nhl_team_game_stats'
    ) then
        execute
            'alter publication supabase_realtime add table public.nhl_team_game_stats';
    end if;

end
$$;


-- ============================================================
-- 9. BASIC ACCESS GRANTS
-- ============================================================

grant select
on public.nhl_teams
to authenticated;

grant select
on public.nhl_players
to authenticated;

grant select
on public.nhl_games
to authenticated;

grant select
on public.nhl_player_game_stats
to authenticated;

grant select
on public.nhl_team_game_stats
to authenticated;


-- ============================================================
-- 10. FOUNDATION VERIFICATION
-- ============================================================

with expected_tables as (
    select *
    from (
        values
            ('nhl_teams'),
            ('nhl_players'),
            ('nhl_games'),
            ('nhl_player_game_stats'),
            ('nhl_team_game_stats')
    ) as x(table_name)
),

table_checks as (
    select
        e.table_name,

        exists (
            select 1
            from information_schema.tables t
            where t.table_schema = 'public'
              and t.table_name = e.table_name
        ) as table_exists,

        exists (
            select 1
            from pg_publication_tables p
            where p.pubname = 'supabase_realtime'
              and p.schemaname = 'public'
              and p.tablename = e.table_name
        ) as realtime_enabled

    from expected_tables e
)

select
    table_name,

    case
        when table_exists
        then 'PASS'
        else 'FAIL'
    end as table_result,

    case
        when realtime_enabled
        then 'PASS'
        else 'FAIL'
    end as realtime_result

from table_checks

order by
    table_name;