-- Gridiron365 / G365 NHL Pick'em foundation
-- Migration: 20260906_002_nhl_pickem_foundation.sql
-- Purpose: isolated NHL Pick'em backend foundation without modifying existing Football Pick'em.

begin;

create extension if not exists pgcrypto;

-- -----------------------------------------------------------------------------
-- Shared identity extensions
-- -----------------------------------------------------------------------------

alter table public.leagues
  add column if not exists nhl_pickem_history_id uuid;

alter table public.fantasy_teams
  add column if not exists nhl_pickem_franchise_id uuid;

-- -----------------------------------------------------------------------------
-- Histories / franchises
-- -----------------------------------------------------------------------------

create table if not exists public.nhl_pickem_histories (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.nhl_pickem_franchises (
  id uuid primary key default gen_random_uuid(),
  history_id uuid not null references public.nhl_pickem_histories(id) on delete cascade,
  owner_id uuid,
  display_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_nhl_pickem_franchises_history_id
  on public.nhl_pickem_franchises(history_id);
create index if not exists idx_nhl_pickem_franchises_owner_id
  on public.nhl_pickem_franchises(owner_id);

-- -----------------------------------------------------------------------------
-- Settings
-- -----------------------------------------------------------------------------

create table if not exists public.nhl_pickem_settings (
  league_id uuid primary key references public.leagues(id) on delete cascade,
  picks_per_period integer not null default 5 check (picks_per_period > 0),
  market_mode text not null default 'puck_line_and_total'
    check (market_mode in ('puck_line_only','total_only','puck_line_and_total')),
  allow_same_game_multiple_markets boolean not null default false,
  pick_lock_mode text not null default 'game'
    check (pick_lock_mode in ('game')),
  minimum_source_books integer not null default 2 check (minimum_source_books > 0),
  scoring_mode text not null default 'record_only'
    check (scoring_mode in ('record_only','standard','confidence')),
  win_points numeric not null default 1,
  push_points numeric not null default 0.5,
  loss_points numeric not null default 0,
  confidence_points numeric[] not null default array[50,40,30,20,10]::numeric[],
  confidence_push_multiplier numeric not null default 0.5,
  missing_pick_policy text not null default 'ungraded'
    check (missing_pick_policy in ('loss','ungraded')),
  contest_timezone text not null default 'America/New_York',
  line_freeze_local_time time not null default time '11:00:00',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- -----------------------------------------------------------------------------
-- Contest periods (Monday-Sunday Eastern)
-- -----------------------------------------------------------------------------

create table if not exists public.nhl_pickem_periods (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  season integer not null,
  period_number integer not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  line_day_at timestamptz,
  finalize_not_before timestamptz,
  status text not null default 'open'
    check (status in ('upcoming','open','locked','finalizing','final')),
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (league_id, season, period_number),
  check (ends_at > starts_at)
);

create index if not exists idx_nhl_pickem_periods_league_season
  on public.nhl_pickem_periods(league_id, season, period_number);
create index if not exists idx_nhl_pickem_periods_status
  on public.nhl_pickem_periods(status, starts_at, ends_at);

-- -----------------------------------------------------------------------------
-- Eligible NHL games + frozen official G365 markets
-- -----------------------------------------------------------------------------

create table if not exists public.nhl_pickem_games (
  id bigint generated by default as identity primary key,
  nhl_pickem_period_id bigint not null references public.nhl_pickem_periods(id) on delete cascade,
  nhl_game_id bigint not null references public.nhl_games(id) on delete cascade,
  league_id uuid not null references public.leagues(id) on delete cascade,
  season integer not null,
  eligible boolean not null default true,
  excluded_reason text,

  consensus_favorite_team_id bigint,
  consensus_favorite_moneyline numeric,
  consensus_underdog_team_id bigint,

  official_home_puck_line numeric,
  official_away_puck_line numeric,
  official_total numeric,

  puck_line_source_count integer not null default 0,
  total_source_count integer not null default 0,

  freeze_scheduled_at timestamptz,
  frozen_at timestamptz,
  is_frozen boolean not null default false,

  final_home_score integer,
  final_away_score integer,
  graded_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (league_id, nhl_pickem_period_id, nhl_game_id),
  check (
    (is_frozen = false)
    or (
      frozen_at is not null
      and official_home_puck_line is not null
      and official_away_puck_line is not null
      and official_total is not null
    )
  )
);

create index if not exists idx_nhl_pickem_games_period
  on public.nhl_pickem_games(nhl_pickem_period_id);
create index if not exists idx_nhl_pickem_games_nhl_game
  on public.nhl_pickem_games(nhl_game_id);
create index if not exists idx_nhl_pickem_games_freeze
  on public.nhl_pickem_games(is_frozen, freeze_scheduled_at);

-- -----------------------------------------------------------------------------
-- Source sportsbook audit
-- -----------------------------------------------------------------------------

create table if not exists public.nhl_pickem_line_sources (
  id bigint generated by default as identity primary key,
  nhl_pickem_game_id bigint not null references public.nhl_pickem_games(id) on delete cascade,
  source_provider text not null,
  sportsbook_key text,
  sportsbook_name text,
  source_event_id text,
  source_market_key text,
  home_moneyline numeric,
  away_moneyline numeric,
  home_puck_line numeric,
  away_puck_line numeric,
  total numeric,
  collected_at timestamptz not null default now(),
  raw_audit jsonb not null default '{}'::jsonb
);

create index if not exists idx_nhl_pickem_line_sources_game
  on public.nhl_pickem_line_sources(nhl_pickem_game_id, collected_at desc);

-- -----------------------------------------------------------------------------
-- Entries / picks / standings
-- -----------------------------------------------------------------------------

create table if not exists public.nhl_pickem_entries (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  fantasy_team_id bigint not null references public.fantasy_teams(id) on delete cascade,
  user_id uuid,
  franchise_id uuid references public.nhl_pickem_franchises(id) on delete set null,
  season integer not null,
  entry_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (league_id, season, fantasy_team_id)
);

create index if not exists idx_nhl_pickem_entries_user
  on public.nhl_pickem_entries(league_id, season, user_id);

create table if not exists public.nhl_pickem_picks (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  nhl_pickem_period_id bigint not null references public.nhl_pickem_periods(id) on delete cascade,
  nhl_pickem_game_id bigint not null references public.nhl_pickem_games(id) on delete cascade,
  entry_id bigint not null references public.nhl_pickem_entries(id) on delete cascade,
  fantasy_team_id bigint not null references public.fantasy_teams(id) on delete cascade,
  user_id uuid,

  market_type text not null check (market_type in ('puck_line','total')),
  selected_side text not null,

  snapshot_home_puck_line numeric,
  snapshot_away_puck_line numeric,
  snapshot_total numeric,

  confidence_value numeric,
  locked_at timestamptz,

  result text check (result is null or result in ('win','push','loss','ungraded')),
  points_awarded numeric not null default 0,
  graded_at timestamptz,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (entry_id, nhl_pickem_period_id, nhl_pickem_game_id, market_type)
);

create index if not exists idx_nhl_pickem_picks_period_entry
  on public.nhl_pickem_picks(nhl_pickem_period_id, entry_id);
create index if not exists idx_nhl_pickem_picks_game
  on public.nhl_pickem_picks(nhl_pickem_game_id);

create table if not exists public.nhl_pickem_standings (
  league_id uuid not null references public.leagues(id) on delete cascade,
  season integer not null,
  entry_id bigint not null references public.nhl_pickem_entries(id) on delete cascade,
  fantasy_team_id bigint not null references public.fantasy_teams(id) on delete cascade,
  wins integer not null default 0,
  pushes integer not null default 0,
  losses integer not null default 0,
  missing_picks integer not null default 0,
  points numeric not null default 0,
  periods_won integer not null default 0,
  periods_played integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key (league_id, season, entry_id)
);

-- -----------------------------------------------------------------------------
-- Utility / touch trigger
-- -----------------------------------------------------------------------------

create or replace function private.touch_nhl_pickem_updated_at()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

DO $$
declare
  t text;
begin
  foreach t in array array[
    'nhl_pickem_histories',
    'nhl_pickem_franchises',
    'nhl_pickem_settings',
    'nhl_pickem_periods',
    'nhl_pickem_games',
    'nhl_pickem_entries',
    'nhl_pickem_picks'
  ]
  loop
    execute format('drop trigger if exists trg_%I_touch_updated_at on public.%I', t, t);
    execute format(
      'create trigger trg_%I_touch_updated_at before update on public.%I for each row execute function private.touch_nhl_pickem_updated_at()',
      t, t
    );
  end loop;
end $$;

-- -----------------------------------------------------------------------------
-- G365 Puck Line formula
-- -----------------------------------------------------------------------------

create or replace function public.get_g365_nhl_favorite_puck_line(
  p_favorite_moneyline numeric
)
returns numeric
language plpgsql
immutable
security invoker
set search_path = public, pg_temp
as $$
begin
  if p_favorite_moneyline is null then
    return null;
  elsif p_favorite_moneyline <= -300 then
    return -2.5;
  elsif p_favorite_moneyline <= -250 then
    return -2.0;
  elsif p_favorite_moneyline <= -200 then
    return -1.5;
  elsif p_favorite_moneyline <= -150 then
    return -1.0;
  elsif p_favorite_moneyline <= -100 then
    return -0.5;
  else
    return null;
  end if;
end;
$$;

-- -----------------------------------------------------------------------------
-- History identity
-- -----------------------------------------------------------------------------

create or replace function public.ensure_nhl_pickem_history_identity(
  p_league_id uuid
)
returns uuid
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_history_id uuid;
begin
  select nhl_pickem_history_id
    into v_history_id
  from public.leagues
  where id = p_league_id
  for update;

  if not found then
    raise exception 'League could not be found.';
  end if;

  if v_history_id is null then
    insert into public.nhl_pickem_histories default values
    returning id into v_history_id;

    update public.leagues
    set nhl_pickem_history_id = v_history_id,
        updated_at = now()
    where id = p_league_id;
  end if;

  return v_history_id;
end;
$$;

-- -----------------------------------------------------------------------------
-- Frozen-line immutability
-- Once a contest game is frozen, official lines and frozen audit identity cannot
-- be altered by ordinary UPDATE statements.
-- -----------------------------------------------------------------------------

create or replace function private.enforce_nhl_pickem_frozen_game_immutability()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
begin
  if old.is_frozen then
    if new.is_frozen is distinct from old.is_frozen
       or new.frozen_at is distinct from old.frozen_at
       or new.consensus_favorite_team_id is distinct from old.consensus_favorite_team_id
       or new.consensus_favorite_moneyline is distinct from old.consensus_favorite_moneyline
       or new.consensus_underdog_team_id is distinct from old.consensus_underdog_team_id
       or new.official_home_puck_line is distinct from old.official_home_puck_line
       or new.official_away_puck_line is distinct from old.official_away_puck_line
       or new.official_total is distinct from old.official_total
       or new.puck_line_source_count is distinct from old.puck_line_source_count
       or new.total_source_count is distinct from old.total_source_count
    then
      raise exception 'Frozen G365 NHL Pick''em lines are immutable.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_nhl_pickem_games_frozen_immutability
  on public.nhl_pickem_games;
create trigger trg_nhl_pickem_games_frozen_immutability
before update on public.nhl_pickem_games
for each row
execute function private.enforce_nhl_pickem_frozen_game_immutability();

-- -----------------------------------------------------------------------------
-- Same-game market restriction
-- -----------------------------------------------------------------------------

create or replace function private.enforce_nhl_pickem_same_game_market_rule()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_allow boolean;
begin
  select s.allow_same_game_multiple_markets
    into v_allow
  from public.nhl_pickem_settings s
  where s.league_id = new.league_id;

  if coalesce(v_allow, false) = false then
    if exists (
      select 1
      from public.nhl_pickem_picks p
      where p.entry_id = new.entry_id
        and p.nhl_pickem_period_id = new.nhl_pickem_period_id
        and p.nhl_pickem_game_id = new.nhl_pickem_game_id
        and p.id <> coalesce(new.id, -1)
    ) then
      raise exception 'This league allows only one market pick per NHL game.';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_nhl_pickem_same_game_market_rule
  on public.nhl_pickem_picks;
create trigger trg_nhl_pickem_same_game_market_rule
before insert or update on public.nhl_pickem_picks
for each row
execute function private.enforce_nhl_pickem_same_game_market_rule();

-- -----------------------------------------------------------------------------
-- Prevent picks after puck drop; snapshot frozen official lines.
-- -----------------------------------------------------------------------------

create or replace function private.prepare_nhl_pickem_pick()
returns trigger
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_game record;
begin
  select
    pg.id,
    pg.is_frozen,
    pg.official_home_puck_line,
    pg.official_away_puck_line,
    pg.official_total,
    ng.kickoff_at
  into v_game
  from public.nhl_pickem_games pg
  join public.nhl_games ng on ng.id = pg.nhl_game_id
  where pg.id = new.nhl_pickem_game_id;

  if not found then
    raise exception 'NHL Pick''em game could not be found.';
  end if;

  if not v_game.is_frozen then
    raise exception 'G365 NHL Pick''em lines are not frozen for this game yet.';
  end if;

  if now() >= v_game.kickoff_at then
    raise exception 'This NHL Pick''em game has already locked at puck drop.';
  end if;

  new.snapshot_home_puck_line := v_game.official_home_puck_line;
  new.snapshot_away_puck_line := v_game.official_away_puck_line;
  new.snapshot_total := v_game.official_total;

  return new;
end;
$$;

drop trigger if exists trg_nhl_pickem_prepare_pick
  on public.nhl_pickem_picks;
create trigger trg_nhl_pickem_prepare_pick
before insert or update of nhl_pickem_game_id, market_type, selected_side
on public.nhl_pickem_picks
for each row
execute function private.prepare_nhl_pickem_pick();

-- -----------------------------------------------------------------------------
-- RLS helpers
-- -----------------------------------------------------------------------------

create or replace function private.is_nhl_pickem_league_member(
  p_league_id uuid,
  p_user_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public, private, pg_temp
as $$
  select exists (
    select 1
    from public.league_members lm
    where lm.league_id = p_league_id
      and lm.user_id = p_user_id
  );
$$;

create or replace function private.is_nhl_pickem_commissioner(
  p_league_id uuid,
  p_user_id uuid
)
returns boolean
language sql
stable
security definer
set search_path = public, private, pg_temp
as $$
  select exists (
    select 1
    from public.leagues l
    where l.id = p_league_id
      and l.commissioner_user_id = p_user_id
  );
$$;

-- -----------------------------------------------------------------------------
-- RLS
-- -----------------------------------------------------------------------------

alter table public.nhl_pickem_histories enable row level security;
alter table public.nhl_pickem_franchises enable row level security;
alter table public.nhl_pickem_settings enable row level security;
alter table public.nhl_pickem_periods enable row level security;
alter table public.nhl_pickem_games enable row level security;
alter table public.nhl_pickem_line_sources enable row level security;
alter table public.nhl_pickem_entries enable row level security;
alter table public.nhl_pickem_picks enable row level security;
alter table public.nhl_pickem_standings enable row level security;

-- Drop policies idempotently.
DO $$
declare
  r record;
begin
  for r in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename like 'nhl_pickem_%'
  loop
    execute format('drop policy if exists %I on %I.%I', r.policyname, r.schemaname, r.tablename);
  end loop;
end $$;

create policy nhl_pickem_settings_member_read
on public.nhl_pickem_settings
for select to authenticated
using (private.is_nhl_pickem_league_member(league_id, auth.uid()));

create policy nhl_pickem_settings_commissioner_write
on public.nhl_pickem_settings
for all to authenticated
using (private.is_nhl_pickem_commissioner(league_id, auth.uid()))
with check (private.is_nhl_pickem_commissioner(league_id, auth.uid()));

create policy nhl_pickem_periods_member_read
on public.nhl_pickem_periods
for select to authenticated
using (private.is_nhl_pickem_league_member(league_id, auth.uid()));

create policy nhl_pickem_games_member_read
on public.nhl_pickem_games
for select to authenticated
using (private.is_nhl_pickem_league_member(league_id, auth.uid()));

create policy nhl_pickem_line_sources_member_read
on public.nhl_pickem_line_sources
for select to authenticated
using (
  exists (
    select 1
    from public.nhl_pickem_games g
    where g.id = nhl_pickem_line_sources.nhl_pickem_game_id
      and private.is_nhl_pickem_league_member(g.league_id, auth.uid())
  )
);

create policy nhl_pickem_entries_member_read
on public.nhl_pickem_entries
for select to authenticated
using (private.is_nhl_pickem_league_member(league_id, auth.uid()));

create policy nhl_pickem_entries_owner_update
on public.nhl_pickem_entries
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

-- Picks are visible to their owner before lock, and to league members after that game locks.
create policy nhl_pickem_picks_visibility
on public.nhl_pickem_picks
for select to authenticated
using (
  user_id = auth.uid()
  or (
    private.is_nhl_pickem_league_member(league_id, auth.uid())
    and exists (
      select 1
      from public.nhl_pickem_games pg
      join public.nhl_games ng on ng.id = pg.nhl_game_id
      where pg.id = nhl_pickem_picks.nhl_pickem_game_id
        and now() >= ng.kickoff_at
    )
  )
);

create policy nhl_pickem_picks_owner_insert
on public.nhl_pickem_picks
for insert to authenticated
with check (
  user_id = auth.uid()
  and private.is_nhl_pickem_league_member(league_id, auth.uid())
);

create policy nhl_pickem_picks_owner_update
on public.nhl_pickem_picks
for update to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

create policy nhl_pickem_picks_owner_delete
on public.nhl_pickem_picks
for delete to authenticated
using (user_id = auth.uid());

create policy nhl_pickem_standings_member_read
on public.nhl_pickem_standings
for select to authenticated
using (private.is_nhl_pickem_league_member(league_id, auth.uid()));

-- History/franchise visibility through league links/teams.
create policy nhl_pickem_histories_member_read
on public.nhl_pickem_histories
for select to authenticated
using (
  exists (
    select 1
    from public.leagues l
    where l.nhl_pickem_history_id = nhl_pickem_histories.id
      and private.is_nhl_pickem_league_member(l.id, auth.uid())
  )
);

create policy nhl_pickem_franchises_member_read
on public.nhl_pickem_franchises
for select to authenticated
using (
  exists (
    select 1
    from public.leagues l
    where l.nhl_pickem_history_id = nhl_pickem_franchises.history_id
      and private.is_nhl_pickem_league_member(l.id, auth.uid())
  )
);

-- -----------------------------------------------------------------------------
-- Grants
-- -----------------------------------------------------------------------------

grant select on public.nhl_pickem_histories to authenticated;
grant select on public.nhl_pickem_franchises to authenticated;
grant select, insert, update, delete on public.nhl_pickem_settings to authenticated;
grant select on public.nhl_pickem_periods to authenticated;
grant select on public.nhl_pickem_games to authenticated;
grant select on public.nhl_pickem_line_sources to authenticated;
grant select, update on public.nhl_pickem_entries to authenticated;
grant select, insert, update, delete on public.nhl_pickem_picks to authenticated;
grant select on public.nhl_pickem_standings to authenticated;

grant usage, select on all sequences in schema public to authenticated;

grant execute on function public.get_g365_nhl_favorite_puck_line(numeric) to authenticated;
grant execute on function public.ensure_nhl_pickem_history_identity(uuid) to authenticated;

-- -----------------------------------------------------------------------------
-- Realtime publication (idempotent)
-- -----------------------------------------------------------------------------

DO $$
declare
  t text;
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    foreach t in array array[
      'nhl_pickem_periods',
      'nhl_pickem_games',
      'nhl_pickem_entries',
      'nhl_pickem_picks',
      'nhl_pickem_standings'
    ]
    loop
      if not exists (
        select 1
        from pg_publication_tables
        where pubname = 'supabase_realtime'
          and schemaname = 'public'
          and tablename = t
      ) then
        execute format('alter publication supabase_realtime add table public.%I', t);
      end if;
    end loop;
  end if;
end $$;

commit;

-- -----------------------------------------------------------------------------
-- Verification (safe to run as part of the migration output)
-- -----------------------------------------------------------------------------

select
  'nhl_pickem_foundation_tables' as check_name,
  count(*) = 9 as pass,
  count(*) as found_count
from information_schema.tables
where table_schema = 'public'
  and table_name in (
    'nhl_pickem_histories',
    'nhl_pickem_franchises',
    'nhl_pickem_settings',
    'nhl_pickem_periods',
    'nhl_pickem_games',
    'nhl_pickem_line_sources',
    'nhl_pickem_entries',
    'nhl_pickem_picks',
    'nhl_pickem_standings'
  );

select
  'nhl_pickem_shared_columns' as check_name,
  (
    exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name='leagues' and column_name='nhl_pickem_history_id'
    )
    and exists (
      select 1 from information_schema.columns
      where table_schema='public' and table_name='fantasy_teams' and column_name='nhl_pickem_franchise_id'
    )
  ) as pass;

select
  'g365_puck_line_formula' as check_name,
  public.get_g365_nhl_favorite_puck_line(-120) = -0.5
  and public.get_g365_nhl_favorite_puck_line(-175) = -1.0
  and public.get_g365_nhl_favorite_puck_line(-225) = -1.5
  and public.get_g365_nhl_favorite_puck_line(-275) = -2.0
  and public.get_g365_nhl_favorite_puck_line(-325) = -2.5
  as pass;

select
  'nhl_pickem_realtime' as check_name,
  count(*) = 5 as pass,
  count(*) as found_count
from pg_publication_tables
where pubname = 'supabase_realtime'
  and schemaname = 'public'
  and tablename in (
    'nhl_pickem_periods',
    'nhl_pickem_games',
    'nhl_pickem_entries',
    'nhl_pickem_picks',
    'nhl_pickem_standings'
  );