begin;

-- ------------------------------------------------------------
-- 1. League competition settings
-- ------------------------------------------------------------

alter table public.season_long_settings
  add column if not exists competition_format text not null default 'total_points',
  add column if not exists regular_season_weeks integer not null default 14,
  add column if not exists playoffs_enabled boolean not null default true,
  add column if not exists playoff_team_count integer not null default 6,
  add column if not exists reseed_playoffs boolean not null default true;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'season_long_settings_competition_format_check'
  ) then
    alter table public.season_long_settings
      add constraint season_long_settings_competition_format_check
      check (competition_format in ('total_points', 'head_to_head'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'season_long_settings_regular_season_weeks_check'
  ) then
    alter table public.season_long_settings
      add constraint season_long_settings_regular_season_weeks_check
      check (regular_season_weeks between 1 and 18);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'season_long_settings_playoff_team_count_check'
  ) then
    alter table public.season_long_settings
      add constraint season_long_settings_playoff_team_count_check
      check (playoff_team_count between 2 and 16);
  end if;
end
$$;

comment on column public.season_long_settings.competition_format is
  'Season-Long competition format: total_points or head_to_head.';

-- ------------------------------------------------------------
-- 2. Weekly H2H matchup table
-- ------------------------------------------------------------

create table if not exists public.season_long_matchups (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  season integer not null,
  week integer not null check (week between 1 and 18),

  home_fantasy_team_id bigint not null references public.fantasy_teams(id) on delete cascade,
  away_fantasy_team_id bigint references public.fantasy_teams(id) on delete cascade,

  home_points numeric(12,2) not null default 0,
  away_points numeric(12,2) not null default 0,

  home_score_final boolean not null default false,
  away_score_final boolean not null default false,
  is_final boolean not null default false,

  winner_fantasy_team_id bigint references public.fantasy_teams(id) on delete set null,
  is_tie boolean not null default false,

  matchup_type text not null default 'regular_season',
  playoff_round integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint season_long_matchups_type_check
    check (matchup_type in ('regular_season', 'playoff', 'consolation')),

  constraint season_long_matchups_distinct_teams_check
    check (
      away_fantasy_team_id is null
      or home_fantasy_team_id <> away_fantasy_team_id
    )
);

create unique index if not exists season_long_matchups_unique_week_home
  on public.season_long_matchups (
    league_id,
    season,
    week,
    home_fantasy_team_id
  );

create unique index if not exists season_long_matchups_unique_week_away
  on public.season_long_matchups (
    league_id,
    season,
    week,
    away_fantasy_team_id
  )
  where away_fantasy_team_id is not null;

create index if not exists season_long_matchups_lookup
  on public.season_long_matchups (league_id, season, week);

-- ------------------------------------------------------------
-- 3. H2H standings table
-- ------------------------------------------------------------

create table if not exists public.season_long_h2h_standings (
  league_id uuid not null references public.leagues(id) on delete cascade,
  fantasy_team_id bigint not null references public.fantasy_teams(id) on delete cascade,
  season integer not null,

  wins integer not null default 0,
  losses integer not null default 0,
  ties integer not null default 0,

  points_for numeric(14,2) not null default 0,
  points_against numeric(14,2) not null default 0,

  games_played integer not null default 0,
  win_percentage numeric(8,6) not null default 0,

  current_rank integer,
  streak_type text,
  streak_count integer not null default 0,

  updated_at timestamptz not null default now(),

  primary key (league_id, fantasy_team_id, season),

  constraint season_long_h2h_streak_type_check
    check (
      streak_type is null
      or streak_type in ('W', 'L', 'T')
    )
);

create index if not exists season_long_h2h_standings_rank_lookup
  on public.season_long_h2h_standings (
    league_id,
    season,
    current_rank
  );

-- ------------------------------------------------------------
-- 4. Build/replace regular-season round-robin schedule
--    Odd team counts receive a bye.
-- ------------------------------------------------------------

create or replace function public.build_season_long_h2h_schedule(
  p_league_id uuid,
  p_season integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_format text;
  v_regular_weeks integer;
  v_team_ids bigint[];
  v_team_count integer;
  v_slots bigint[];
  v_round integer;
  v_rounds_per_cycle integer;
  v_week integer;
  v_pair integer;
  v_home bigint;
  v_away bigint;
  v_temp bigint;
  v_inserted integer := 0;
begin
  select
    coalesce(s.competition_format, 'total_points'),
    coalesce(s.regular_season_weeks, 14)
  into
    v_format,
    v_regular_weeks
  from public.season_long_settings s
  where s.league_id = p_league_id;

  if v_format <> 'head_to_head' then
    raise exception 'Season-Long league is not configured for Head-to-Head.';
  end if;

  select array_agg(ft.id order by ft.id)
  into v_team_ids
  from public.fantasy_teams ft
  where ft.league_id = p_league_id
    and ft.active = true;

  v_team_count := coalesce(array_length(v_team_ids, 1), 0);

  if v_team_count < 2 then
    raise exception 'At least two active teams are required to build a Head-to-Head schedule.';
  end if;

  -- Add a null bye slot when team count is odd.
  v_slots := v_team_ids;

  if mod(v_team_count, 2) = 1 then
    v_slots := array_append(v_slots, null::bigint);
    v_team_count := v_team_count + 1;
  end if;

  v_rounds_per_cycle := v_team_count - 1;

  delete from public.season_long_matchups
  where league_id = p_league_id
    and season = p_season
    and matchup_type = 'regular_season'
    and is_final = false;

  -- Circle-method schedule. Repeat cycles if commissioner has more
  -- regular-season weeks than one full round robin.
  for v_week in 1..v_regular_weeks loop
    v_round := ((v_week - 1) % v_rounds_per_cycle) + 1;

    -- Reset the circle at the beginning of each cycle.
    if v_round = 1 then
      v_slots := v_team_ids;

      if mod(array_length(v_team_ids, 1), 2) = 1 then
        v_slots := array_append(v_slots, null::bigint);
      end if;
    end if;

    for v_pair in 1..(array_length(v_slots, 1) / 2) loop
      v_home := v_slots[v_pair];
      v_away := v_slots[array_length(v_slots, 1) - v_pair + 1];

      -- Alternate home/away for balance.
      if mod(v_week + v_pair, 2) = 0 then
        v_temp := v_home;
        v_home := v_away;
        v_away := v_temp;
      end if;

      -- A null side represents a bye; no matchup row needed.
      if v_home is not null and v_away is not null then
        insert into public.season_long_matchups (
          league_id,
          season,
          week,
          home_fantasy_team_id,
          away_fantasy_team_id,
          matchup_type
        )
        values (
          p_league_id,
          p_season,
          v_week,
          v_home,
          v_away,
          'regular_season'
        )
        on conflict do nothing;

        if found then
          v_inserted := v_inserted + 1;
        end if;
      end if;
    end loop;

    -- Rotate all slots except the first.
    if array_length(v_slots, 1) > 2 then
      v_temp := v_slots[array_length(v_slots, 1)];

      for v_pair in reverse array_length(v_slots, 1)..3 loop
        v_slots[v_pair] := v_slots[v_pair - 1];
      end loop;

      v_slots[2] := v_temp;
    end if;
  end loop;

  return v_inserted;
end;
$function$;

-- ------------------------------------------------------------
-- 5. Sync one week's finalized Season-Long fantasy scores into H2H
-- ------------------------------------------------------------

create or replace function public.sync_season_long_h2h_week(
  p_league_id uuid,
  p_season integer,
  p_week integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_updated integer := 0;
begin
  update public.season_long_matchups m
  set
    home_points = coalesce(h.fantasy_points, 0),
    away_points = coalesce(a.fantasy_points, 0),
    home_score_final = coalesce(h.is_final, false),
    away_score_final = coalesce(a.is_final, false),
    is_final =
      coalesce(h.is_final, false)
      and coalesce(a.is_final, false),
    winner_fantasy_team_id =
      case
        when not (
          coalesce(h.is_final, false)
          and coalesce(a.is_final, false)
        ) then null
        when coalesce(h.fantasy_points, 0) > coalesce(a.fantasy_points, 0)
          then m.home_fantasy_team_id
        when coalesce(a.fantasy_points, 0) > coalesce(h.fantasy_points, 0)
          then m.away_fantasy_team_id
        else null
      end,
    is_tie =
      case
        when not (
          coalesce(h.is_final, false)
          and coalesce(a.is_final, false)
        ) then false
        else coalesce(h.fantasy_points, 0) = coalesce(a.fantasy_points, 0)
      end,
    updated_at = now()
  from public.season_long_weekly_scores h,
       public.season_long_weekly_scores a
  where m.league_id = p_league_id
    and m.season = p_season
    and m.week = p_week
    and m.matchup_type = 'regular_season'
    and h.league_id = m.league_id
    and h.season = m.season
    and h.week = m.week
    and h.fantasy_team_id = m.home_fantasy_team_id
    and a.league_id = m.league_id
    and a.season = m.season
    and a.week = m.week
    and a.fantasy_team_id = m.away_fantasy_team_id;

  get diagnostics v_updated = row_count;

  return v_updated;
end;
$function$;

-- ------------------------------------------------------------
-- 6. Rebuild W-L-T H2H standings from finalized matchups
-- ------------------------------------------------------------

create or replace function public.rebuild_season_long_h2h_standings(
  p_league_id uuid,
  p_season integer
)
returns integer
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_count integer := 0;
begin
  delete from public.season_long_h2h_standings
  where league_id = p_league_id
    and season = p_season;

  with active_teams as (
    select
      ft.id as fantasy_team_id
    from public.fantasy_teams ft
    where ft.league_id = p_league_id
      and ft.active = true
  ),
  results as (
    select
      m.home_fantasy_team_id as fantasy_team_id,
      case
        when m.is_tie then 0
        when m.winner_fantasy_team_id = m.home_fantasy_team_id then 1
        else 0
      end as wins,
      case
        when m.is_tie then 0
        when m.winner_fantasy_team_id = m.away_fantasy_team_id then 1
        else 0
      end as losses,
      case when m.is_tie then 1 else 0 end as ties,
      m.home_points as points_for,
      m.away_points as points_against,
      m.week
    from public.season_long_matchups m
    where m.league_id = p_league_id
      and m.season = p_season
      and m.matchup_type = 'regular_season'
      and m.is_final = true

    union all

    select
      m.away_fantasy_team_id as fantasy_team_id,
      case
        when m.is_tie then 0
        when m.winner_fantasy_team_id = m.away_fantasy_team_id then 1
        else 0
      end as wins,
      case
        when m.is_tie then 0
        when m.winner_fantasy_team_id = m.home_fantasy_team_id then 1
        else 0
      end as losses,
      case when m.is_tie then 1 else 0 end as ties,
      m.away_points as points_for,
      m.home_points as points_against,
      m.week
    from public.season_long_matchups m
    where m.league_id = p_league_id
      and m.season = p_season
      and m.matchup_type = 'regular_season'
      and m.is_final = true
      and m.away_fantasy_team_id is not null
  ),
  aggregated as (
    select
      t.fantasy_team_id,
      coalesce(sum(r.wins), 0)::integer as wins,
      coalesce(sum(r.losses), 0)::integer as losses,
      coalesce(sum(r.ties), 0)::integer as ties,
      coalesce(sum(r.points_for), 0)::numeric(14,2) as points_for,
      coalesce(sum(r.points_against), 0)::numeric(14,2) as points_against
    from active_teams t
    left join results r
      on r.fantasy_team_id = t.fantasy_team_id
    group by t.fantasy_team_id
  ),
  ranked as (
    select
      a.*,
      (a.wins + a.losses + a.ties) as games_played,
      case
        when (a.wins + a.losses + a.ties) = 0 then 0::numeric
        else (
          (a.wins + (a.ties * 0.5))
          / (a.wins + a.losses + a.ties)::numeric
        )
      end as win_percentage,
      row_number() over (
        order by
          case
            when (a.wins + a.losses + a.ties) = 0 then 0::numeric
            else (
              (a.wins + (a.ties * 0.5))
              / (a.wins + a.losses + a.ties)::numeric
            )
          end desc,
          a.points_for desc,
          (a.points_for - a.points_against) desc,
          a.fantasy_team_id
      )::integer as current_rank
    from aggregated a
  )
  insert into public.season_long_h2h_standings (
    league_id,
    fantasy_team_id,
    season,
    wins,
    losses,
    ties,
    points_for,
    points_against,
    games_played,
    win_percentage,
    current_rank,
    updated_at
  )
  select
    p_league_id,
    r.fantasy_team_id,
    p_season,
    r.wins,
    r.losses,
    r.ties,
    r.points_for,
    r.points_against,
    r.games_played,
    r.win_percentage,
    r.current_rank,
    now()
  from ranked r;

  get diagnostics v_count = row_count;

  return v_count;
end;
$function$;

-- ------------------------------------------------------------
-- 7. Convenience function: sync matchup results + rebuild standings
-- ------------------------------------------------------------

create or replace function public.finalize_season_long_h2h_week(
  p_league_id uuid,
  p_season integer,
  p_week integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$
declare
  v_matchups integer;
  v_standings integer;
begin
  v_matchups :=
    public.sync_season_long_h2h_week(
      p_league_id,
      p_season,
      p_week
    );

  v_standings :=
    public.rebuild_season_long_h2h_standings(
      p_league_id,
      p_season
    );

  return jsonb_build_object(
    'success', true,
    'leagueId', p_league_id,
    'season', p_season,
    'week', p_week,
    'matchupsUpdated', v_matchups,
    'standingsRows', v_standings
  );
end;
$function$;

-- ------------------------------------------------------------
-- 8. Permissions
-- ------------------------------------------------------------

grant select on public.season_long_matchups to authenticated;
grant select on public.season_long_h2h_standings to authenticated;

grant execute on function public.build_season_long_h2h_schedule(uuid, integer)
  to authenticated;

grant execute on function public.sync_season_long_h2h_week(uuid, integer, integer)
  to authenticated;

grant execute on function public.rebuild_season_long_h2h_standings(uuid, integer)
  to authenticated;

grant execute on function public.finalize_season_long_h2h_week(uuid, integer, integer)
  to authenticated;

commit;

-- ============================================================
-- QUICK VERIFICATION
-- ============================================================

select
  column_name,
  data_type,
  column_default
from information_schema.columns
where table_schema = 'public'
  and table_name = 'season_long_settings'
  and column_name in (
    'competition_format',
    'regular_season_weeks',
    'playoffs_enabled',
    'playoff_team_count',
    'reseed_playoffs'
  )
order by column_name;

select
  routine_name
from information_schema.routines
where routine_schema = 'public'
  and routine_name in (
    'build_season_long_h2h_schedule',
    'sync_season_long_h2h_week',
    'rebuild_season_long_h2h_standings',
    'finalize_season_long_h2h_week'
  )
order by routine_name;
