-- ============================================================================
-- GRIDIRON365
-- NFL PLAYOFFS
-- STAGE 2 - PLAYOFF PROJECTIONS + SALARY ENGINE
--
-- Core rules:
--
-- 1. NFL Playoffs use CURRENT-SEASON information.
-- 2. Prior-season historical weighting is NOT used for playoff pricing.
-- 3. Wild Card begins with the completed current regular season.
-- 4. Later playoff rounds allow completed playoff games into RECENT FORM.
-- 5. Full regular-season performance remains the stable baseline.
-- 6. Actual playoff opponent / home-away / kickoff are used.
-- 7. Salary publication is Thursday 10:00 PM America/New_York.
-- 8. Published salaries immediately become frozen for the round.
-- 9. Player injury status can continue changing after publication.
-- 10. Frozen salaries themselves cannot be repriced.
-- 11. OUT / IR / PUP / suspended players are not placed in the salary pool.
-- 12. Salary curve preserves the Season-Long G365 cap-relative model.
-- ============================================================================


-- ============================================================================
-- 1. PLAYOFF PLAYER PROJECTIONS
-- ============================================================================

create table if not exists public.nfl_playoff_player_projections (

    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    season integer not null,

    round_number integer not null
        check (round_number between 1 and 4),

    nfl_player_id bigint not null,

    team_abbreviation text,

    position text,

    opponent_abbreviation text,

    home_or_away text,

    kickoff_at timestamptz,

    injury_status text,

    is_available boolean not null default true,

    regular_season_games integer not null default 0,

    recent_games integer not null default 0,

    baseline_projection numeric not null default 0,

    recent_form_projection numeric not null default 0,

    usage_projection numeric not null default 0,

    matchup_multiplier numeric not null default 1,

    injury_multiplier numeric not null default 1,

    home_away_multiplier numeric not null default 1,

    replacement_opportunity_multiplier numeric not null default 1,

    projected_points numeric not null default 0,

    calculation_details jsonb not null default '{}'::jsonb,

    calculated_at timestamptz not null default now(),

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    unique (
        league_id,
        season,
        round_number,
        nfl_player_id
    )
);


create index if not exists
    nfl_playoff_player_projections_round_idx
on public.nfl_playoff_player_projections (
    league_id,
    season,
    round_number
);


create index if not exists
    nfl_playoff_player_projections_player_idx
on public.nfl_playoff_player_projections (
    nfl_player_id
);


-- ============================================================================
-- 2. HELPER - NORMALIZE FANTASY POSITION
-- ============================================================================

create or replace function public.normalize_nfl_playoff_position(
    p_position text
)
returns text
language sql
immutable
as $function$

    select
        case

            when upper(
                coalesce(
                    p_position,
                    ''
                )
            ) = 'PK'
            then 'K'

            when upper(
                coalesce(
                    p_position,
                    ''
                )
            ) in (
                'DEF',
                'D/ST'
            )
            then 'DST'

            else upper(
                coalesce(
                    p_position,
                    ''
                )
            )

        end;

$function$;


-- ============================================================================
-- 3. HELPER - PLAYER UNAVAILABLE STATUS
-- ============================================================================

create or replace function public.is_nfl_playoff_player_unavailable(
    p_status text
)
returns boolean
language sql
immutable
as $function$

    select
        case

            when upper(
                coalesce(
                    p_status,
                    ''
                )
            ) like '%OUT%'
            then true

            when upper(
                coalesce(
                    p_status,
                    ''
                )
            ) like '%INJURED RESERVE%'
            then true

            when upper(
                coalesce(
                    p_status,
                    ''
                )
            ) = 'IR'
            then true

            when upper(
                coalesce(
                    p_status,
                    ''
                )
            ) like '%PUP%'
            then true

            when upper(
                coalesce(
                    p_status,
                    ''
                )
            ) like '%NFI%'
            then true

            when upper(
                coalesce(
                    p_status,
                    ''
                )
            ) like '%SUSPEND%'
            then true

            when upper(
                coalesce(
                    p_status,
                    ''
                )
            ) in (
                'SUSP',
                'INACTIVE',
                'RESERVE-DNR',
                'RESERVE-SUS'
            )
            then true

            else false

        end;

$function$;


-- ============================================================================
-- 4. PLAYOFF ROUND PLAYER PROJECTIONS
-- ============================================================================

create or replace function public.refresh_nfl_playoff_round_projections(
    p_league_id uuid,
    p_season integer,
    p_round_number integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$

declare

    v_selection_mode text;

    v_expected_games integer;

    v_actual_games integer;

    v_first_kickoff timestamptz;

    v_rows_written integer := 0;

    v_available_rows integer := 0;

    v_unavailable_rows integer := 0;

begin

    -- ========================================================================
    -- VALIDATION
    -- ========================================================================

    if p_round_number not between 1 and 4 then
        raise exception
            'NFL Playoffs round number must be between 1 and 4.';
    end if;


    if p_season < 2000
       or p_season > 2200
    then
        raise exception
            'A valid NFL season is required.';
    end if;


    select
        l.player_selection_mode
    into
        v_selection_mode
    from public.leagues l
    where l.id = p_league_id;


    if not found then
        raise exception
            'League could not be found.';
    end if;


    if v_selection_mode not in (
        'salary',
        'no_salary'
    )
    then
        raise exception
            'NFL Playoffs must use Salary or No Salary mode.';
    end if;


    if not exists (
        select 1
        from public.nfl_playoff_settings s
        where s.league_id = p_league_id
          and s.season = p_season
    )
    then
        raise exception
            'NFL Playoffs settings were not found.';
    end if;


    if not exists (
        select 1
        from public.league_scoring_settings s
        where s.league_id = p_league_id
    )
    then
        raise exception
            'Scoring settings were not found for league %.',
            p_league_id;
    end if;


    -- ========================================================================
    -- VERIFY POSTSEASON SCHEDULE IS COMPLETE
    -- ========================================================================

    v_expected_games :=
        public.get_nfl_playoff_expected_game_count(
            p_round_number
        );


    select
        count(*),
        min(g.kickoff_at)

    into
        v_actual_games,
        v_first_kickoff

    from public.nfl_playoff_games pg

    join public.nfl_games g
        on g.id = pg.nfl_game_id

    where pg.league_id = p_league_id
      and pg.season = p_season
      and pg.round_number = p_round_number;


    if coalesce(
        v_actual_games,
        0
    ) <> v_expected_games
    then
        raise exception
            'NFL Playoffs round % schedule is incomplete. Expected % games, found %.',
            p_round_number,
            v_expected_games,
            coalesce(
                v_actual_games,
                0
            );
    end if;


    if v_first_kickoff is null then
        raise exception
            'NFL Playoffs round kickoff time could not be determined.';
    end if;


    -- ========================================================================
    -- BUILD CURRENT-SEASON PLAYOFF PROJECTIONS
    -- ========================================================================
    --
    -- IMPORTANT:
    --
    -- BASELINE:
    --     Full completed CURRENT regular season.
    --
    -- RECENT FORM:
    --     Most recent 3 completed games in current season.
    --     This includes completed earlier playoff rounds.
    --
    -- MATCHUP:
    --     Current-season production allowed by actual playoff opponent.
    --
    -- HISTORICAL PRIOR-SEASON WEIGHT:
    --     ZERO.
    --
    -- ========================================================================

    with


    -- ------------------------------------------------------------------------
    -- ACTUAL TEAMS / OPPONENTS IN THIS PLAYOFF ROUND
    -- ------------------------------------------------------------------------

    round_teams as (

        select

            upper(
                ht.abbreviation
            ) as team_abbreviation,

            upper(
                at.abbreviation
            ) as opponent_abbreviation,

            'home'::text as home_or_away,

            g.kickoff_at

        from public.nfl_playoff_games pg

        join public.nfl_games g
            on g.id = pg.nfl_game_id

        join public.nfl_teams ht
            on ht.id = g.home_team_id

        join public.nfl_teams at
            on at.id = g.away_team_id

        where pg.league_id = p_league_id
          and pg.season = p_season
          and pg.round_number = p_round_number


        union all


        select

            upper(
                at.abbreviation
            ) as team_abbreviation,

            upper(
                ht.abbreviation
            ) as opponent_abbreviation,

            'away'::text as home_or_away,

            g.kickoff_at

        from public.nfl_playoff_games pg

        join public.nfl_games g
            on g.id = pg.nfl_game_id

        join public.nfl_teams ht
            on ht.id = g.home_team_id

        join public.nfl_teams at
            on at.id = g.away_team_id

        where pg.league_id = p_league_id
          and pg.season = p_season
          and pg.round_number = p_round_number
    ),


    -- ------------------------------------------------------------------------
    -- CURRENT INJURY RECORD
    -- ------------------------------------------------------------------------

    current_injury as (

        select distinct on (
            i.nfl_player_id
        )

            i.nfl_player_id,

            upper(
                coalesce(
                    i.team_abbreviation,
                    ''
                )
            ) as team_abbreviation,

            upper(
                coalesce(
                    i.primary_position,
                    ''
                )
            ) as primary_position,

            upper(
                trim(
                    coalesce(
                        i.status,
                        ''
                    )
                )
            ) as injury_status

        from public.current_nfl_player_injuries i

        where i.season = p_season

        order by
            i.nfl_player_id,
            i.updated_at desc
    ),


    -- ------------------------------------------------------------------------
    -- ALL PLAYERS ON NFL TEAMS PLAYING THIS ROUND
    -- ------------------------------------------------------------------------

    player_pool as (

        select

            p.id as nfl_player_id,

            upper(
                coalesce(
                    p.team_abbreviation,
                    ''
                )
            ) as team_abbreviation,

            public.normalize_nfl_playoff_position(
                p.primary_position
            ) as position,

            rt.opponent_abbreviation,

            rt.home_or_away,

            rt.kickoff_at,

            ci.injury_status,

            public.is_nfl_playoff_player_unavailable(
                ci.injury_status
            ) as unavailable

        from public.nfl_players p

        join round_teams rt
            on rt.team_abbreviation =
               upper(
                   coalesce(
                       p.team_abbreviation,
                       ''
                   )
               )

        left join current_injury ci
            on ci.nfl_player_id = p.id

        where p.is_active = true

          and public.normalize_nfl_playoff_position(
              p.primary_position
          ) in (
              'QB',
              'RB',
              'WR',
              'TE',
              'K',
              'DST'
          )
    ),


    -- ------------------------------------------------------------------------
    -- FULL CURRENT REGULAR-SEASON FANTASY PRODUCTION
    --
    -- Uses the league's actual scoring system.
    -- ------------------------------------------------------------------------

    regular_game_rows as (

        select

            pool.nfl_player_id,

            gs.id as player_game_stat_id,

            g.id as nfl_game_id,

            g.kickoff_at,

            greatest(
                0::numeric,
                coalesce(
                    public.calculate_fantasy_points(
                        p_league_id,
                        gs.id
                    ),
                    0
                )
            ) as fantasy_points

        from player_pool pool

        join public.nfl_player_game_stats gs
            on gs.nfl_player_id =
               pool.nfl_player_id

        join public.nfl_games g
            on g.id = gs.nfl_game_id

        where gs.season = p_season
          and gs.season_type = 2
          and gs.is_final = true
          and g.status_completed = true
    ),


    regular_summary as (

        select

            r.nfl_player_id,

            count(*)::integer
                as regular_season_games,

            avg(
                r.fantasy_points
            ) as regular_season_average

        from regular_game_rows r

        group by
            r.nfl_player_id
    ),


    -- ------------------------------------------------------------------------
    -- CURRENT-SEASON RECENT FORM
    --
    -- Includes:
    --     regular season
    --     completed earlier playoff rounds
    --
    -- Excludes:
    --     current round
    --     future games
    -- ------------------------------------------------------------------------

    recent_game_rows_raw as (

        select

            pool.nfl_player_id,

            pool.position,

            gs.id as player_game_stat_id,

            g.id as nfl_game_id,

            g.kickoff_at,

            greatest(
                0::numeric,
                coalesce(
                    public.calculate_fantasy_points(
                        p_league_id,
                        gs.id
                    ),
                    0
                )
            ) as fantasy_points,

            case

                when pool.position = 'QB'
                then
                    coalesce(
                        gs.passing_attempts,
                        0
                    )::numeric
                    +
                    coalesce(
                        gs.rushing_attempts,
                        0
                    )::numeric


                when pool.position = 'RB'
                then
                    coalesce(
                        gs.rushing_attempts,
                        0
                    )::numeric
                    +
                    coalesce(
                        gs.receiving_targets,
                        0
                    )::numeric


                when pool.position in (
                    'WR',
                    'TE'
                )
                then
                    coalesce(
                        gs.receiving_targets,
                        0
                    )::numeric
                    +
                    coalesce(
                        gs.rushing_attempts,
                        0
                    )::numeric


                when pool.position = 'K'
                then
                    coalesce(
                        gs.field_goals_attempted,
                        0
                    )::numeric
                    +
                    coalesce(
                        gs.extra_points_attempted,
                        0
                    )::numeric


                when pool.position = 'DST'
                then
                    coalesce(
                        gs.dst_sacks,
                        0
                    )::numeric
                    +
                    coalesce(
                        gs.dst_interceptions,
                        0
                    )::numeric
                    +
                    coalesce(
                        gs.dst_fumble_recoveries,
                        0
                    )::numeric
                    +
                    coalesce(
                        gs.dst_blocked_kicks,
                        0
                    )::numeric


                else
                    0::numeric

            end as usage_opportunities

        from player_pool pool

        join public.nfl_player_game_stats gs
            on gs.nfl_player_id =
               pool.nfl_player_id

        join public.nfl_games g
            on g.id = gs.nfl_game_id

        where gs.season = p_season
          and gs.is_final = true
          and g.status_completed = true

          and (
              gs.season_type = 2

              or (
                  gs.season_type = 3
                  and g.kickoff_at <
                      v_first_kickoff
              )
          )
    ),


    recent_game_rows as (

        select

            r.*,

            row_number() over (
                partition by
                    r.nfl_player_id
                order by
                    r.kickoff_at desc,
                    r.nfl_game_id desc
            ) as game_rank

        from recent_game_rows_raw r
    ),


    recent_three as (

        select *

        from recent_game_rows

        where game_rank <= 3
    ),


    recent_summary as (

        select

            r.nfl_player_id,

            count(*)::integer
                as recent_games,

            avg(
                r.fantasy_points
            ) as recent_fantasy_points,

            avg(
                r.usage_opportunities
            ) as average_usage

        from recent_three r

        group by
            r.nfl_player_id
    ),


    -- ------------------------------------------------------------------------
    -- MAXIMUM USAGE BY POSITION
    -- ------------------------------------------------------------------------

    usage_position_max as (

        select

            pool.position,

            max(
                coalesce(
                    rs.average_usage,
                    0
                )
            ) as maximum_usage

        from player_pool pool

        left join recent_summary rs
            on rs.nfl_player_id =
               pool.nfl_player_id

        group by
            pool.position
    ),


    -- ========================================================================
    -- CURRENT-SEASON OPPONENT MATCHUP BOARD
    --
    -- Same G365 philosophy:
    --
    -- lower production allowed = tougher defense
    -- #1 toughest
    -- #32 easiest
    --
    -- Uses:
    --     full regular-season production
    --     65% recent-three / 35% regular-season blend
    --
    -- Completed prior playoff rounds can enter recent-three.
    --
    -- ========================================================================

    allowed_player_rows_raw as (

        select

            g.id as nfl_game_id,

            g.kickoff_at,

            gs.season_type,

            public.normalize_nfl_playoff_position(
                p.primary_position
            ) as position,

            upper(
                case

                    when upper(
                        coalesce(
                            gs.team_abbreviation,
                            ''
                        )
                    ) =
                    upper(
                        coalesce(
                            ht.abbreviation,
                            ''
                        )
                    )
                    then at.abbreviation

                    else ht.abbreviation

                end
            ) as opponent_abbreviation,

            case

                when public.normalize_nfl_playoff_position(
                    p.primary_position
                ) = 'QB'
                then
                    coalesce(
                        gs.passing_yards,
                        0
                    )::numeric / 25.0

                    +
                    coalesce(
                        gs.passing_touchdowns,
                        0
                    )::numeric * 4.0

                    -
                    coalesce(
                        gs.passing_interceptions,
                        0
                    )::numeric * 1.5

                    +
                    coalesce(
                        gs.rushing_yards,
                        0
                    )::numeric / 10.0

                    +
                    coalesce(
                        gs.rushing_touchdowns,
                        0
                    )::numeric * 6.0


                when public.normalize_nfl_playoff_position(
                    p.primary_position
                ) = 'RB'
                then
                    coalesce(
                        gs.rushing_yards,
                        0
                    )::numeric / 10.0

                    +
                    coalesce(
                        gs.rushing_touchdowns,
                        0
                    )::numeric * 6.0

                    +
                    coalesce(
                        gs.receptions,
                        0
                    )::numeric * 0.50

                    +
                    coalesce(
                        gs.receiving_yards,
                        0
                    )::numeric / 10.0

                    +
                    coalesce(
                        gs.receiving_touchdowns,
                        0
                    )::numeric * 6.0


                when public.normalize_nfl_playoff_position(
                    p.primary_position
                ) = 'WR'
                then
                    coalesce(
                        gs.receiving_targets,
                        0
                    )::numeric * 0.20

                    +
                    coalesce(
                        gs.receptions,
                        0
                    )::numeric * 0.50

                    +
                    coalesce(
                        gs.receiving_yards,
                        0
                    )::numeric / 10.0

                    +
                    coalesce(
                        gs.receiving_touchdowns,
                        0
                    )::numeric * 6.0

                    +
                    coalesce(
                        gs.rushing_yards,
                        0
                    )::numeric / 10.0

                    +
                    coalesce(
                        gs.rushing_touchdowns,
                        0
                    )::numeric * 6.0


                when public.normalize_nfl_playoff_position(
                    p.primary_position
                ) = 'TE'
                then
                    coalesce(
                        gs.receiving_targets,
                        0
                    )::numeric * 0.20

                    +
                    coalesce(
                        gs.receptions,
                        0
                    )::numeric * 0.50

                    +
                    coalesce(
                        gs.receiving_yards,
                        0
                    )::numeric / 10.0

                    +
                    coalesce(
                        gs.receiving_touchdowns,
                        0
                    )::numeric * 6.0


                when public.normalize_nfl_playoff_position(
                    p.primary_position
                ) = 'K'
                then
                    coalesce(
                        gs.field_goals_attempted,
                        0
                    )::numeric * 1.00

                    +
                    coalesce(
                        gs.field_goals_made,
                        0
                    )::numeric * 2.00

                    +
                    coalesce(
                        gs.extra_points_attempted,
                        0
                    )::numeric * 0.25

                    +
                    coalesce(
                        gs.extra_points_made,
                        0
                    )::numeric * 0.75


                else
                    0::numeric

            end as production_score

        from public.nfl_player_game_stats gs

        join public.nfl_players p
            on p.id = gs.nfl_player_id

        join public.nfl_games g
            on g.id = gs.nfl_game_id

        join public.nfl_teams ht
            on ht.id = g.home_team_id

        join public.nfl_teams at
            on at.id = g.away_team_id

        where gs.season = p_season
          and gs.is_final = true
          and g.status_completed = true

          and public.normalize_nfl_playoff_position(
              p.primary_position
          ) in (
              'QB',
              'RB',
              'WR',
              'TE',
              'K'
          )

          and (
              gs.season_type = 2

              or (
                  gs.season_type = 3
                  and g.kickoff_at <
                      v_first_kickoff
              )
          )
    ),


    allowed_game_totals as (

        select

            a.nfl_game_id,

            a.kickoff_at,

            a.season_type,

            a.position,

            a.opponent_abbreviation,

            sum(
                a.production_score
            ) as position_points

        from allowed_player_rows_raw a

        where a.opponent_abbreviation
              is not null

        group by
            a.nfl_game_id,
            a.kickoff_at,
            a.season_type,
            a.position,
            a.opponent_abbreviation
    ),


    allowed_ranked as (

        select

            a.*,

            row_number() over (
                partition by
                    a.position,
                    a.opponent_abbreviation

                order by
                    a.kickoff_at desc,
                    a.nfl_game_id desc
            ) as recency_rank

        from allowed_game_totals a
    ),


    allowed_summary as (

        select

            a.position,

            a.opponent_abbreviation,

            avg(
                a.position_points
            ) filter (
                where a.season_type = 2
            ) as regular_season_allowed,

            avg(
                a.position_points
            ) filter (
                where a.recency_rank <= 3
            ) as recent_three_allowed

        from allowed_ranked a

        group by
            a.position,
            a.opponent_abbreviation
    ),


    allowed_blend as (

        select

            s.position,

            s.opponent_abbreviation,

            case

                when s.recent_three_allowed
                     is not null
                 and s.regular_season_allowed
                     is not null

                then
                    0.65
                    * s.recent_three_allowed

                    +
                    0.35
                    * s.regular_season_allowed


                when s.recent_three_allowed
                     is not null

                then
                    s.recent_three_allowed


                else
                    s.regular_season_allowed

            end as actual_allowed_score

        from allowed_summary s
    ),


    allowed_percentile as (

        select

            a.*,

            (
                percent_rank() over (
                    partition by
                        a.position

                    order by
                        a.actual_allowed_score desc,
                        a.opponent_abbreviation asc
                )
                * 100.0
            )::numeric
                as toughness_percentile

        from allowed_blend a

        where a.actual_allowed_score
              is not null
    ),


    skill_matchup as (

        select

            a.position,

            a.opponent_abbreviation,

            greatest(
                0.8800::numeric,

                least(
                    1.1200::numeric,

                    1.0000::numeric
                    +
                    (
                        50.0000::numeric
                        -
                        a.toughness_percentile
                    )
                    * 0.0024::numeric
                )
            ) as matchup_multiplier

        from allowed_percentile a
    ),


    -- ========================================================================
    -- DST OPPOSING OFFENSE STRENGTH
    -- ========================================================================

    offense_player_rows as (

        select

            g.id as nfl_game_id,

            g.kickoff_at,

            gs.season_type,

            upper(
                coalesce(
                    gs.team_abbreviation,
                    ''
                )
            ) as team_abbreviation,

            case

                when public.normalize_nfl_playoff_position(
                    p.primary_position
                ) = 'QB'
                then
                    coalesce(
                        gs.passing_yards,
                        0
                    )::numeric / 25.0

                    +
                    coalesce(
                        gs.passing_touchdowns,
                        0
                    )::numeric * 4.0

                    -
                    coalesce(
                        gs.passing_interceptions,
                        0
                    )::numeric * 1.5


                when public.normalize_nfl_playoff_position(
                    p.primary_position
                ) = 'RB'
                then
                    coalesce(
                        gs.rushing_yards,
                        0
                    )::numeric / 10.0

                    +
                    coalesce(
                        gs.rushing_touchdowns,
                        0
                    )::numeric * 6.0

                    +
                    coalesce(
                        gs.receiving_yards,
                        0
                    )::numeric / 10.0

                    +
                    coalesce(
                        gs.receiving_touchdowns,
                        0
                    )::numeric * 6.0


                when public.normalize_nfl_playoff_position(
                    p.primary_position
                ) in (
                    'WR',
                    'TE'
                )
                then
                    coalesce(
                        gs.receiving_yards,
                        0
                    )::numeric / 10.0

                    +
                    coalesce(
                        gs.receiving_touchdowns,
                        0
                    )::numeric * 6.0


                else
                    0::numeric

            end as offense_score

        from public.nfl_player_game_stats gs

        join public.nfl_players p
            on p.id = gs.nfl_player_id

        join public.nfl_games g
            on g.id = gs.nfl_game_id

        where gs.season = p_season
          and gs.is_final = true
          and g.status_completed = true

          and public.normalize_nfl_playoff_position(
              p.primary_position
          ) in (
              'QB',
              'RB',
              'WR',
              'TE'
          )

          and (
              gs.season_type = 2

              or (
                  gs.season_type = 3
                  and g.kickoff_at <
                      v_first_kickoff
              )
          )
    ),


    offense_game_totals as (

        select

            o.nfl_game_id,

            o.kickoff_at,

            o.season_type,

            o.team_abbreviation,

            sum(
                o.offense_score
            ) as offense_score

        from offense_player_rows o

        where o.team_abbreviation <> ''

        group by
            o.nfl_game_id,
            o.kickoff_at,
            o.season_type,
            o.team_abbreviation
    ),


    offense_ranked as (

        select

            o.*,

            row_number() over (
                partition by
                    o.team_abbreviation

                order by
                    o.kickoff_at desc,
                    o.nfl_game_id desc
            ) as recency_rank

        from offense_game_totals o
    ),


    offense_summary as (

        select

            o.team_abbreviation,

            avg(
                o.offense_score
            ) filter (
                where o.season_type = 2
            ) as regular_season_offense,

            avg(
                o.offense_score
            ) filter (
                where o.recency_rank <= 3
            ) as recent_three_offense

        from offense_ranked o

        group by
            o.team_abbreviation
    ),


    offense_blend as (

        select

            o.team_abbreviation,

            case

                when o.recent_three_offense
                     is not null
                 and o.regular_season_offense
                     is not null

                then
                    0.65
                    * o.recent_three_offense

                    +
                    0.35
                    * o.regular_season_offense


                when o.recent_three_offense
                     is not null

                then
                    o.recent_three_offense


                else
                    o.regular_season_offense

            end as offense_strength

        from offense_summary o
    ),


    offense_percentile as (

        select

            o.*,

            (
                percent_rank() over (
                    order by
                        o.offense_strength asc,
                        o.team_abbreviation asc
                )
                * 100.0
            )::numeric
                as strength_percentile

        from offense_blend o

        where o.offense_strength
              is not null
    ),


    dst_matchup as (

        select

            o.team_abbreviation
                as opponent_abbreviation,

            greatest(
                0.8800::numeric,

                least(
                    1.1200::numeric,

                    1.0000::numeric
                    +
                    (
                        50.0000::numeric
                        -
                        o.strength_percentile
                    )
                    * 0.0024::numeric
                )
            ) as matchup_multiplier

        from offense_percentile o
    ),


    -- ========================================================================
    -- CURRENT INJURY / PERSONNEL EFFECT ON THE OPPONENT
    --
    -- This is deliberately CURRENT-SEASON and current-status only.
    -- No prior-season personnel weighting.
    -- ========================================================================

    opponent_defensive_injury_adjustment as (

        select

            ci.team_abbreviation,

            least(
                0.1000::numeric,

                sum(

                    case

                        when ci.injury_status like '%OUT%'
                          or ci.injury_status like '%INJURED RESERVE%'
                          or ci.injury_status = 'IR'
                          or ci.injury_status like '%PUP%'
                          or ci.injury_status like '%NFI%'
                          or ci.injury_status like '%SUSPEND%'
                        then 0.0200::numeric

                        when ci.injury_status like '%DOUBT%'
                        then 0.0125::numeric

                        when ci.injury_status like '%QUESTION%'
                        then 0.0050::numeric

                        else 0::numeric

                    end
                )
            ) as adjustment

        from current_injury ci

        where ci.primary_position in (
            'CB',
            'DB',
            'S',
            'FS',
            'SS',
            'LB',
            'ILB',
            'OLB',
            'MLB',
            'DE',
            'DL',
            'DT',
            'NT',
            'EDGE'
        )

        group by
            ci.team_abbreviation
    ),


    opponent_offensive_injury_adjustment as (

        select

            ci.team_abbreviation,

            least(
                0.1000::numeric,

                sum(

                    case

                        when ci.injury_status like '%OUT%'
                          or ci.injury_status like '%INJURED RESERVE%'
                          or ci.injury_status = 'IR'
                          or ci.injury_status like '%PUP%'
                          or ci.injury_status like '%NFI%'
                          or ci.injury_status like '%SUSPEND%'
                        then

                            case
                                when ci.primary_position = 'QB'
                                    then 0.0550::numeric
                                when ci.primary_position = 'RB'
                                    then 0.0250::numeric
                                when ci.primary_position = 'WR'
                                    then 0.0220::numeric
                                when ci.primary_position = 'TE'
                                    then 0.0180::numeric
                                else 0::numeric
                            end


                        when ci.injury_status like '%DOUBT%'
                        then

                            case
                                when ci.primary_position = 'QB'
                                    then 0.0350::numeric
                                when ci.primary_position = 'RB'
                                    then 0.0160::numeric
                                when ci.primary_position = 'WR'
                                    then 0.0140::numeric
                                when ci.primary_position = 'TE'
                                    then 0.0120::numeric
                                else 0::numeric
                            end


                        when ci.injury_status like '%QUESTION%'
                        then

                            case
                                when ci.primary_position = 'QB'
                                    then 0.0150::numeric
                                when ci.primary_position = 'RB'
                                    then 0.0075::numeric
                                when ci.primary_position = 'WR'
                                    then 0.0065::numeric
                                when ci.primary_position = 'TE'
                                    then 0.0050::numeric
                                else 0::numeric
                            end


                        else
                            0::numeric

                    end
                )
            ) as adjustment

        from current_injury ci

        where ci.primary_position in (
            'QB',
            'RB',
            'WR',
            'TE'
        )

        group by
            ci.team_abbreviation
    ),


    -- ------------------------------------------------------------------------
    -- PLAYER OWN INJURY MULTIPLIER
    -- ------------------------------------------------------------------------

    player_components as (

        select

            pool.*,

            coalesce(
                reg.regular_season_games,
                0
            ) as regular_season_games,

            coalesce(
                recent.recent_games,
                0
            ) as recent_games,

            greatest(
                0::numeric,

                coalesce(
                    reg.regular_season_average,

                    recent.recent_fantasy_points,

                    0
                )
            ) as baseline_projection,


            greatest(
                0::numeric,

                coalesce(
                    recent.recent_fantasy_points,

                    reg.regular_season_average,

                    0
                )
            ) as recent_form_projection,


            coalesce(
                recent.average_usage,
                0
            ) as average_usage,


            case

                when pool.position = 'DST'
                then
                    greatest(
                        0.8500::numeric,

                        least(
                            1.1500::numeric,

                            coalesce(
                                dstm.matchup_multiplier,
                                1.0000
                            )
                            *
                            (
                                1.0000
                                +
                                coalesce(
                                    oia.adjustment,
                                    0
                                )
                            )
                        )
                    )


                else
                    greatest(
                        0.8500::numeric,

                        least(
                            1.1500::numeric,

                            coalesce(
                                sm.matchup_multiplier,
                                1.0000
                            )
                            *
                            (
                                1.0000
                                +
                                coalesce(
                                    dia.adjustment,
                                    0
                                )
                            )
                        )
                    )

            end as matchup_multiplier,


            case

                when pool.unavailable
                then 0.0000::numeric

                when upper(
                    coalesce(
                        pool.injury_status,
                        ''
                    )
                ) like '%DOUBT%'
                then 0.7500::numeric

                when upper(
                    coalesce(
                        pool.injury_status,
                        ''
                    )
                ) like '%QUESTION%'
                then 0.9500::numeric

                else 1.0000::numeric

            end as injury_multiplier,


            case

                when pool.home_or_away = 'home'
                then 1.0200::numeric

                when pool.home_or_away = 'away'
                then 0.9800::numeric

                else 1.0000::numeric

            end as home_away_multiplier


        from player_pool pool

        left join regular_summary reg
            on reg.nfl_player_id =
               pool.nfl_player_id

        left join recent_summary recent
            on recent.nfl_player_id =
               pool.nfl_player_id

        left join skill_matchup sm
            on sm.position =
               pool.position
           and sm.opponent_abbreviation =
               pool.opponent_abbreviation

        left join dst_matchup dstm
            on dstm.opponent_abbreviation =
               pool.opponent_abbreviation

        left join opponent_defensive_injury_adjustment dia
            on dia.team_abbreviation =
               pool.opponent_abbreviation

        left join opponent_offensive_injury_adjustment oia
            on oia.team_abbreviation =
               pool.opponent_abbreviation
    ),


    usage_components as (

        select

            pc.*,

            case

                when coalesce(
                    pc.regular_season_games,
                    0
                ) = 0
                then pc.baseline_projection


                when coalesce(
                    upm.maximum_usage,
                    0
                ) > 0
                then

                    pc.baseline_projection

                    *

                    greatest(
                        0::numeric,

                        least(
                            pc.average_usage
                            /
                            nullif(
                                upm.maximum_usage,
                                0
                            ),
                            1.25::numeric
                        )
                    )


                else
                    pc.baseline_projection

            end as usage_projection

        from player_components pc

        left join usage_position_max upm
            on upm.position =
               pc.position
    ),


    -- ------------------------------------------------------------------------
    -- UNAVAILABLE TEAMMATE OPPORTUNITY
    -- ------------------------------------------------------------------------

    unavailable_team_position as (

        select

            u.team_abbreviation,

            u.position,

            sum(
                greatest(
                    u.baseline_projection,
                    0
                )
            ) as unavailable_projection

        from usage_components u

        where u.unavailable = true

        group by
            u.team_abbreviation,
            u.position
    ),


    active_position_rank as (

        select

            u.nfl_player_id,

            u.team_abbreviation,

            u.position,

            row_number() over (
                partition by
                    u.team_abbreviation,
                    u.position

                order by
                    u.baseline_projection desc,
                    u.nfl_player_id
            ) as role_rank

        from usage_components u

        where u.unavailable = false
    ),


    final_components as (

        select

            u.*,

            case

                when coalesce(
                    utp.unavailable_projection,
                    0
                ) <= 0
                then 1.0000::numeric


                when u.position = 'QB'
                 and apr.role_rank = 1
                then
                    least(
                        1.3000::numeric,

                        1.0000
                        +
                        (
                            utp.unavailable_projection
                            /
                            nullif(
                                greatest(
                                    u.baseline_projection,
                                    1
                                ),
                                0
                            )
                        )
                        * 0.40
                    )


                when u.position = 'RB'
                 and apr.role_rank = 1
                then
                    least(
                        1.2200::numeric,

                        1.0000
                        +
                        (
                            utp.unavailable_projection
                            /
                            nullif(
                                greatest(
                                    u.baseline_projection,
                                    1
                                ),
                                0
                            )
                        )
                        * 0.32
                    )


                when u.position = 'RB'
                 and apr.role_rank = 2
                then
                    least(
                        1.1000::numeric,

                        1.0000
                        +
                        (
                            utp.unavailable_projection
                            /
                            nullif(
                                greatest(
                                    u.baseline_projection,
                                    1
                                ),
                                0
                            )
                        )
                        * 0.16
                    )


                when u.position = 'WR'
                 and apr.role_rank <= 2
                then
                    least(
                        1.1200::numeric,

                        1.0000
                        +
                        (
                            utp.unavailable_projection
                            /
                            nullif(
                                greatest(
                                    u.baseline_projection,
                                    1
                                ),
                                0
                            )
                        )
                        * 0.18
                    )


                when u.position = 'WR'
                 and apr.role_rank = 3
                then
                    least(
                        1.0600::numeric,

                        1.0000
                        +
                        (
                            utp.unavailable_projection
                            /
                            nullif(
                                greatest(
                                    u.baseline_projection,
                                    1
                                ),
                                0
                            )
                        )
                        * 0.09
                    )


                when u.position = 'TE'
                 and apr.role_rank = 1
                then
                    least(
                        1.1800::numeric,

                        1.0000
                        +
                        (
                            utp.unavailable_projection
                            /
                            nullif(
                                greatest(
                                    u.baseline_projection,
                                    1
                                ),
                                0
                            )
                        )
                        * 0.26
                    )


                when u.position = 'K'
                 and apr.role_rank = 1
                then
                    least(
                        1.1500::numeric,

                        1.0000
                        +
                        (
                            utp.unavailable_projection
                            /
                            nullif(
                                greatest(
                                    u.baseline_projection,
                                    1
                                ),
                                0
                            )
                        )
                        * 0.22
                    )


                else
                    1.0000::numeric

            end as replacement_opportunity_multiplier

        from usage_components u

        left join unavailable_team_position utp
            on utp.team_abbreviation =
               u.team_abbreviation
           and utp.position =
               u.position

        left join active_position_rank apr
            on apr.nfl_player_id =
               u.nfl_player_id
    ),


    upserted as (

        insert into public.nfl_playoff_player_projections (

            league_id,
            season,
            round_number,

            nfl_player_id,

            team_abbreviation,
            position,
            opponent_abbreviation,
            home_or_away,
            kickoff_at,

            injury_status,
            is_available,

            regular_season_games,
            recent_games,

            baseline_projection,
            recent_form_projection,
            usage_projection,

            matchup_multiplier,
            injury_multiplier,
            home_away_multiplier,
            replacement_opportunity_multiplier,

            projected_points,

            calculation_details,

            calculated_at,
            updated_at
        )

        select

            p_league_id,
            p_season,
            p_round_number,

            fc.nfl_player_id,

            fc.team_abbreviation,
            fc.position,
            fc.opponent_abbreviation,
            fc.home_or_away,
            fc.kickoff_at,

            fc.injury_status,

            not fc.unavailable,

            fc.regular_season_games,
            fc.recent_games,

            round(
                fc.baseline_projection,
                2
            ),

            round(
                fc.recent_form_projection,
                2
            ),

            round(
                fc.usage_projection,
                2
            ),

            round(
                fc.matchup_multiplier,
                4
            ),

            round(
                fc.injury_multiplier,
                4
            ),

            round(
                fc.home_away_multiplier,
                4
            ),

            round(
                fc.replacement_opportunity_multiplier,
                4
            ),

            case

                when fc.unavailable
                then 0::numeric

                else round(

                    greatest(
                        0::numeric,

                        (
                            fc.baseline_projection
                            * 0.55
                        )

                        +

                        (
                            fc.recent_form_projection
                            * 0.30
                        )

                        +

                        (
                            fc.usage_projection
                            * 0.15
                        )
                    )

                    *

                    fc.matchup_multiplier

                    *

                    fc.injury_multiplier

                    *

                    fc.home_away_multiplier

                    *

                    fc.replacement_opportunity_multiplier,

                    2
                )

            end,

            jsonb_build_object(

                'engine',
                    'g365_nfl_playoffs_current_season_v1',

                'historicalPriorSeasonWeight',
                    0.00,

                'regularSeasonBaselineWeight',
                    0.55,

                'recentFormWeight',
                    0.30,

                'usageWeight',
                    0.15,

                'matchupActualRecentBlend',
                    0.65,

                'matchupActualSeasonBlend',
                    0.35,

                'team',
                    fc.team_abbreviation,

                'opponent',
                    fc.opponent_abbreviation,

                'homeOrAway',
                    fc.home_or_away,

                'injuryStatus',
                    fc.injury_status,

                'available',
                    not fc.unavailable,

                'regularSeasonGames',
                    fc.regular_season_games,

                'recentGames',
                    fc.recent_games,

                'baselineProjection',
                    round(
                        fc.baseline_projection,
                        2
                    ),

                'recentFormProjection',
                    round(
                        fc.recent_form_projection,
                        2
                    ),

                'usageProjection',
                    round(
                        fc.usage_projection,
                        2
                    ),

                'matchupMultiplier',
                    round(
                        fc.matchup_multiplier,
                        4
                    ),

                'injuryMultiplier',
                    round(
                        fc.injury_multiplier,
                        4
                    ),

                'homeAwayMultiplier',
                    round(
                        fc.home_away_multiplier,
                        4
                    ),

                'replacementOpportunityMultiplier',
                    round(
                        fc.replacement_opportunity_multiplier,
                        4
                    ),

                'currentSeasonOnly',
                    true,

                'priorSeasonFallbackUsed',
                    false
            ),

            now(),
            now()

        from final_components fc

        on conflict (
            league_id,
            season,
            round_number,
            nfl_player_id
        )

        do update
        set

            team_abbreviation =
                excluded.team_abbreviation,

            position =
                excluded.position,

            opponent_abbreviation =
                excluded.opponent_abbreviation,

            home_or_away =
                excluded.home_or_away,

            kickoff_at =
                excluded.kickoff_at,

            injury_status =
                excluded.injury_status,

            is_available =
                excluded.is_available,

            regular_season_games =
                excluded.regular_season_games,

            recent_games =
                excluded.recent_games,

            baseline_projection =
                excluded.baseline_projection,

            recent_form_projection =
                excluded.recent_form_projection,

            usage_projection =
                excluded.usage_projection,

            matchup_multiplier =
                excluded.matchup_multiplier,

            injury_multiplier =
                excluded.injury_multiplier,

            home_away_multiplier =
                excluded.home_away_multiplier,

            replacement_opportunity_multiplier =
                excluded.replacement_opportunity_multiplier,

            projected_points =
                excluded.projected_points,

            calculation_details =
                excluded.calculation_details,

            calculated_at =
                excluded.calculated_at,

            updated_at =
                excluded.updated_at

        returning
            nfl_player_id,
            is_available
    )


    select

        count(*),

        count(*) filter (
            where is_available = true
        ),

        count(*) filter (
            where is_available = false
        )

    into
        v_rows_written,
        v_available_rows,
        v_unavailable_rows

    from upserted;


    -- ========================================================================
    -- REMOVE PLAYERS WHO ARE NO LONGER ON A TEAM IN THIS ROUND
    -- ========================================================================

    delete from public.nfl_playoff_player_projections pp

    where pp.league_id = p_league_id
      and pp.season = p_season
      and pp.round_number = p_round_number

      and not exists (

          select 1

          from player_pool pool

          where pool.nfl_player_id =
                pp.nfl_player_id
      );


    return jsonb_build_object(

        'success',
            true,

        'leagueId',
            p_league_id,

        'season',
            p_season,

        'roundNumber',
            p_round_number,

        'roundName',
            public.get_nfl_playoff_round_name(
                p_round_number
            ),

        'rowsWritten',
            v_rows_written,

        'availablePlayers',
            v_available_rows,

        'unavailablePlayers',
            v_unavailable_rows,

        'historicalPriorSeasonWeight',
            0.00,

        'baselineSource',
            'completed_current_regular_season',

        'recentFormSource',
            'latest_three_completed_current_season_games_including_prior_playoff_rounds',

        'matchupSource',
            'current_season_actual_plus_current_injury_personnel',

        'engine',
            'g365_nfl_playoffs_current_season_v1'
    );

end;

$function$;


-- ============================================================================
-- 5. SALARY FREEZE PROTECTION
-- ============================================================================

create or replace function public.prevent_locked_nfl_playoff_salary_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $function$

declare

    v_league_id uuid;

    v_season integer;

    v_round_number integer;

    v_locked boolean := false;

begin

    v_league_id :=
        coalesce(
            new.league_id,
            old.league_id
        );

    v_season :=
        coalesce(
            new.season,
            old.season
        );

    v_round_number :=
        coalesce(
            new.round_number,
            old.round_number
        );


    select
        coalesce(
            s.is_locked,
            false
        )

    into
        v_locked

    from public.nfl_playoff_salary_round_state s

    where s.league_id = v_league_id
      and s.season = v_season
      and s.round_number = v_round_number;


    if coalesce(
        v_locked,
        false
    )
    then
        raise exception
            'NFL Playoffs salaries for this round are published and frozen.';
    end if;


    return
        case
            when tg_op = 'DELETE'
                then old
            else new
        end;

end;

$function$;


drop trigger if exists
    trg_prevent_locked_nfl_playoff_salary_change
on public.nfl_playoff_player_salaries;


create trigger
    trg_prevent_locked_nfl_playoff_salary_change

before insert
    or update
    or delete

on public.nfl_playoff_player_salaries

for each row

execute function
    public.prevent_locked_nfl_playoff_salary_change();


-- ============================================================================
-- 6. GENERATE + PUBLISH + FREEZE ROUND SALARIES
-- ============================================================================

create or replace function public.generate_nfl_playoff_round_salaries(
    p_league_id uuid,
    p_season integer,
    p_round_number integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$

declare

    v_selection_mode text;

    v_weekly_salary_cap numeric;

    v_reference_salary_cap constant numeric :=
        65000.0;

    v_salary_scale numeric;

    v_min_salary numeric;

    v_max_salary numeric;

    v_increment numeric := 100;

    v_projection_weight numeric := 1;

    v_qb_multiplier numeric := 0.95;

    v_rb_multiplier numeric := 1.08;

    v_wr_multiplier numeric := 1.05;

    v_te_multiplier numeric := 1.08;

    v_k_multiplier numeric := 0.70;

    v_dst_multiplier numeric := 0.75;

    v_max_increase numeric := 1500;

    v_max_decrease numeric := 1500;

    v_min_projection numeric := 0;

    v_max_projection numeric := 0;

    v_players_priced integer := 0;

    v_removed_unavailable integer := 0;

    v_projection_result jsonb;

begin

    -- ========================================================================
    -- VALIDATION
    -- ========================================================================

    if p_round_number not between 1 and 4 then
        raise exception
            'NFL Playoffs round number must be between 1 and 4.';
    end if;


    select
        l.player_selection_mode

    into
        v_selection_mode

    from public.leagues l

    where l.id = p_league_id;


    if not found then
        raise exception
            'League could not be found.';
    end if;


    if v_selection_mode <> 'salary' then
        raise exception
            'NFL Playoffs salaries are only generated for Salary leagues.';
    end if;


    -- ========================================================================
    -- HARD FREEZE GUARD
    -- ========================================================================

    if exists (

        select 1

        from public.nfl_playoff_salary_round_state s

        where s.league_id = p_league_id
          and s.season = p_season
          and s.round_number = p_round_number
          and s.is_locked = true
    )
    then
        raise exception
            'NFL Playoffs salaries for this round are already published and frozen.';
    end if;


    -- ========================================================================
    -- SALARY CAP
    -- ========================================================================

    select
        s.weekly_salary_cap

    into
        v_weekly_salary_cap

    from public.nfl_playoff_settings s

    where s.league_id = p_league_id
      and s.season = p_season;


    if v_weekly_salary_cap is null
       or v_weekly_salary_cap <= 0
    then
        raise exception
            'NFL Playoffs salary cap must be greater than zero.';
    end if;


    v_salary_scale :=
        v_weekly_salary_cap
        /
        v_reference_salary_cap;


    -- ========================================================================
    -- SALARY SETTINGS
    -- ========================================================================

    select

        coalesce(
            s.projection_weight,
            1
        ),

        coalesce(
            s.qb_multiplier,
            0.95
        ),

        coalesce(
            s.rb_multiplier,
            1.08
        ),

        coalesce(
            s.wr_multiplier,
            1.05
        ),

        coalesce(
            s.te_multiplier,
            1.08
        ),

        coalesce(
            s.k_multiplier,
            0.70
        ),

        coalesce(
            s.dst_multiplier,
            0.75
        ),

        coalesce(
            s.maximum_weekly_increase,
            1500
        ),

        coalesce(
            s.maximum_weekly_decrease,
            1500
        )

    into

        v_projection_weight,

        v_qb_multiplier,
        v_rb_multiplier,
        v_wr_multiplier,
        v_te_multiplier,
        v_k_multiplier,
        v_dst_multiplier,

        v_max_increase,
        v_max_decrease

    from public.nfl_playoff_salary_settings s

    where s.league_id = p_league_id;


    -- Scale movement guardrails with commissioner salary cap.

    v_max_increase :=
        round(
            v_max_increase
            * v_salary_scale
        );


    v_max_decrease :=
        round(
            v_max_decrease
            * v_salary_scale
        );


    -- ========================================================================
    -- G365 SALARY CURVE
    --
    -- Same cap-relative philosophy as Season-Long.
    --
    -- minimum ≈ 3% of cap
    -- maximum ≈ 15% of cap
    -- increment = $100
    -- ========================================================================

    v_min_salary :=
        greatest(
            v_increment,

            round(
                (
                    v_weekly_salary_cap
                    * 0.03
                )
                /
                v_increment
            )
            *
            v_increment
        );


    v_max_salary :=
        greatest(
            v_min_salary,

            round(
                (
                    v_weekly_salary_cap
                    * 0.15
                )
                /
                v_increment
            )
            *
            v_increment
        );


    -- ========================================================================
    -- REFRESH FINAL THURSDAY PROJECTIONS
    -- ========================================================================

    v_projection_result :=
        public.refresh_nfl_playoff_round_projections(
            p_league_id,
            p_season,
            p_round_number
        );


    -- ========================================================================
    -- REMOVE UNAVAILABLE SALARY ROWS
    -- ========================================================================

    delete from public.nfl_playoff_player_salaries s

    where s.league_id = p_league_id
      and s.season = p_season
      and s.round_number = p_round_number

      and not exists (

          select 1

          from public.nfl_playoff_player_projections p

          where p.league_id = s.league_id
            and p.season = s.season
            and p.round_number = s.round_number
            and p.nfl_player_id = s.nfl_player_id
            and p.is_available = true
      );


    get diagnostics
        v_removed_unavailable = row_count;


    -- ========================================================================
    -- PROJECTION RANGE
    -- ========================================================================

    select

        coalesce(
            min(
                p.projected_points
            ) filter (
                where p.projected_points > 0
                  and p.is_available = true
            ),
            0
        ),

        coalesce(
            max(
                p.projected_points
            ) filter (
                where p.projected_points > 0
                  and p.is_available = true
            ),
            0
        )

    into
        v_min_projection,
        v_max_projection

    from public.nfl_playoff_player_projections p

    where p.league_id = p_league_id
      and p.season = p_season
      and p.round_number = p_round_number;


    -- ========================================================================
    -- UPSERT FINAL ROUND SALARIES
    -- ========================================================================

    with priced as (

        select

            p.nfl_player_id,

            p.position,

            p.projected_points,

            previous.salary
                as previous_round_salary,


            case
                when p.position = 'QB'
                    then v_qb_multiplier

                when p.position = 'RB'
                    then v_rb_multiplier

                when p.position = 'WR'
                    then v_wr_multiplier

                when p.position = 'TE'
                    then v_te_multiplier

                when p.position = 'K'
                    then v_k_multiplier

                when p.position = 'DST'
                    then v_dst_multiplier

                else 1.0000::numeric
            end
                as position_multiplier


        from public.nfl_playoff_player_projections p

        left join public.nfl_playoff_player_salaries previous

            on previous.league_id =
               p.league_id

           and previous.season =
               p.season

           and previous.round_number =
               p.round_number - 1

           and previous.nfl_player_id =
               p.nfl_player_id


        where p.league_id = p_league_id
          and p.season = p_season
          and p.round_number = p_round_number
          and p.is_available = true
          and p.projected_points > 0
    ),


    raw_salary as (

        select

            priced.*,

            case

                when v_max_projection <=
                     v_min_projection

                then
                    (
                        v_min_salary
                        +
                        v_max_salary
                    )
                    / 2.0


                else

                    v_min_salary

                    +

                    (
                        (
                            priced.projected_points
                            -
                            v_min_projection
                        )

                        /

                        nullif(
                            v_max_projection
                            -
                            v_min_projection,
                            0
                        )
                    )

                    *

                    (
                        v_max_salary
                        -
                        v_min_salary
                    )

            end

            *

            v_projection_weight

            *

            priced.position_multiplier

                as calculated_salary

        from priced
    ),


    rounded_salary as (

        select

            r.*,

            greatest(
                v_min_salary,

                least(
                    v_max_salary,

                    round(
                        r.calculated_salary
                        /
                        v_increment
                    )
                    *
                    v_increment
                )
            ) as bounded_salary

        from raw_salary r
    ),


    guarded_salary as (

        select

            r.*,

            case

                when r.previous_round_salary
                     is null

                then
                    r.bounded_salary


                else

                    greatest(
                        v_min_salary,

                        least(
                            v_max_salary,

                            greatest(
                                r.previous_round_salary
                                -
                                v_max_decrease,

                                least(
                                    r.previous_round_salary
                                    +
                                    v_max_increase,

                                    r.bounded_salary
                                )
                            )
                        )
                    )

            end as final_salary

        from rounded_salary r
    ),


    upserted as (

        insert into public.nfl_playoff_player_salaries (

            league_id,
            season,
            round_number,

            nfl_player_id,

            salary,

            projected_points,

            previous_round_salary,

            salary_change,

            salary_change_percent,

            source,

            pricing_details,

            calculated_at,
            updated_at
        )

        select

            p_league_id,
            p_season,
            p_round_number,

            g.nfl_player_id,

            g.final_salary,

            round(
                g.projected_points,
                2
            ),

            g.previous_round_salary,

            case

                when g.previous_round_salary
                     is null

                then null

                else
                    g.final_salary
                    -
                    g.previous_round_salary

            end,

            case

                when g.previous_round_salary
                     is null

                  or g.previous_round_salary = 0

                then null

                else

                    round(
                        (
                            (
                                g.final_salary
                                -
                                g.previous_round_salary
                            )
                            /
                            g.previous_round_salary
                        )
                        * 100,
                        4
                    )

            end,

            'g365_nfl_playoffs_current_season_salary_v1',

            jsonb_build_object(

                'engine',
                    'g365_nfl_playoffs_current_season_salary_v1',

                'roundNumber',
                    p_round_number,

                'roundName',
                    public.get_nfl_playoff_round_name(
                        p_round_number
                    ),

                'historicalPriorSeasonWeight',
                    0.00,

                'weeklySalaryCap',
                    v_weekly_salary_cap,

                'salaryScale',
                    round(
                        v_salary_scale,
                        6
                    ),

                'minimumSalary',
                    v_min_salary,

                'maximumSalary',
                    v_max_salary,

                'salaryIncrement',
                    v_increment,

                'projectionWeight',
                    v_projection_weight,

                'positionMultiplier',
                    g.position_multiplier,

                'projectedPoints',
                    round(
                        g.projected_points,
                        2
                    ),

                'previousRoundSalary',
                    g.previous_round_salary,

                'maximumRoundIncrease',
                    v_max_increase,

                'maximumRoundDecrease',
                    v_max_decrease,

                'salaryBeforeGuardrail',
                    g.bounded_salary,

                'finalSalary',
                    g.final_salary,

                'publishedAt',
                    now(),

                'salaryFrozenAfterPublication',
                    true
            ),

            now(),
            now()

        from guarded_salary g

        on conflict (
            league_id,
            season,
            round_number,
            nfl_player_id
        )

        do update
        set

            salary =
                excluded.salary,

            projected_points =
                excluded.projected_points,

            previous_round_salary =
                excluded.previous_round_salary,

            salary_change =
                excluded.salary_change,

            salary_change_percent =
                excluded.salary_change_percent,

            source =
                excluded.source,

            pricing_details =
                excluded.pricing_details,

            calculated_at =
                excluded.calculated_at,

            updated_at =
                excluded.updated_at

        returning
            nfl_player_id
    )


    select
        count(*)

    into
        v_players_priced

    from upserted;


    -- ========================================================================
    -- PUBLISH + FREEZE IMMEDIATELY
    -- ========================================================================

    insert into public.nfl_playoff_salary_round_state (

        league_id,
        season,
        round_number,

        is_locked,

        generated_at,
        locked_at,

        created_at,
        updated_at
    )

    values (

        p_league_id,
        p_season,
        p_round_number,

        true,

        now(),
        now(),

        now(),
        now()
    )

    on conflict (
        league_id,
        season,
        round_number
    )

    do update
    set

        is_locked =
            true,

        generated_at =
            excluded.generated_at,

        locked_at =
            excluded.locked_at,

        updated_at =
            excluded.updated_at;


    return jsonb_build_object(

        'success',
            true,

        'leagueId',
            p_league_id,

        'season',
            p_season,

        'roundNumber',
            p_round_number,

        'roundName',
            public.get_nfl_playoff_round_name(
                p_round_number
            ),

        'playersPriced',
            v_players_priced,

        'unavailablePlayersRemoved',
            v_removed_unavailable,

        'weeklySalaryCap',
            v_weekly_salary_cap,

        'minimumSalary',
            v_min_salary,

        'maximumSalary',
            v_max_salary,

        'salaryIncrement',
            v_increment,

        'salaryScale',
            round(
                v_salary_scale,
                6
            ),

        'minimumPositiveProjection',
            v_min_projection,

        'maximumProjection',
            v_max_projection,

        'historicalPriorSeasonWeight',
            0.00,

        'currentSeasonOnly',
            true,

        'published',
            true,

        'frozen',
            true,

        'projectionRefresh',
            v_projection_result,

        'source',
            'g365_nfl_playoffs_current_season_salary_v1'
    );

end;

$function$;


-- ============================================================================
-- 7. SALARY PUBLICATION STATUS
-- ============================================================================

create or replace function public.get_nfl_playoff_salary_publication_status(
    p_league_id uuid,
    p_season integer,
    p_round_number integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$

declare

    v_expected_games integer;

    v_actual_games integer;

    v_first_kickoff timestamptz;

    v_first_local_date date;

    v_publish_local_date date;

    v_publish_at timestamptz;

    v_is_locked boolean := false;

    v_generated_at timestamptz;

    v_locked_at timestamptz;

begin

    v_expected_games :=
        public.get_nfl_playoff_expected_game_count(
            p_round_number
        );


    select

        count(*),

        min(
            g.kickoff_at
        )

    into

        v_actual_games,

        v_first_kickoff

    from public.nfl_playoff_games pg

    join public.nfl_games g
        on g.id = pg.nfl_game_id

    where pg.league_id =
          p_league_id

      and pg.season =
          p_season

      and pg.round_number =
          p_round_number;


    if v_first_kickoff is not null then

        v_first_local_date :=
            (
                v_first_kickoff
                at time zone
                'America/New_York'
            )::date;


        v_publish_local_date :=
            v_first_local_date

            -

            (
                (
                    extract(
                        isodow
                        from v_first_local_date
                    )::integer
                    -
                    4
                    +
                    7
                )
                %
                7
            );


        v_publish_at :=
            (
                v_publish_local_date::timestamp
                +
                time '22:00'
            )
            at time zone
            'America/New_York';

    end if;


    select

        coalesce(
            s.is_locked,
            false
        ),

        s.generated_at,

        s.locked_at

    into

        v_is_locked,

        v_generated_at,

        v_locked_at

    from public.nfl_playoff_salary_round_state s

    where s.league_id =
          p_league_id

      and s.season =
          p_season

      and s.round_number =
          p_round_number;


    return jsonb_build_object(

        'leagueId',
            p_league_id,

        'season',
            p_season,

        'roundNumber',
            p_round_number,

        'roundName',
            public.get_nfl_playoff_round_name(
                p_round_number
            ),

        'expectedGames',
            v_expected_games,

        'mappedGames',
            coalesce(
                v_actual_games,
                0
            ),

        'scheduleComplete',
            coalesce(
                v_actual_games,
                0
            ) =
            v_expected_games,

        'firstKickoff',
            v_first_kickoff,

        'scheduledPublicationAt',
            v_publish_at,

        'publicationTimezone',
            'America/New_York',

        'publicationRule',
            'Thursday 10:00 PM ET before first game of round',

        'isPublished',
            coalesce(
                v_is_locked,
                false
            ),

        'isFrozen',
            coalesce(
                v_is_locked,
                false
            ),

        'generatedAt',
            v_generated_at,

        'lockedAt',
            v_locked_at
    );

end;

$function$;


-- ============================================================================
-- 8. AUTOMATED THURSDAY 10 PM ET SALARY PUBLICATION
-- ============================================================================

create or replace function public.run_nfl_playoff_salary_schedule()
returns jsonb
language plpgsql
security definer
set search_path = public
as $function$

declare

    rec record;

    v_expected_games integer;

    v_actual_games integer;

    v_first_kickoff timestamptz;

    v_first_local_date date;

    v_publish_local_date date;

    v_publish_at timestamptz;

    v_result jsonb;

    v_published jsonb :=
        '[]'::jsonb;

    v_skipped jsonb :=
        '[]'::jsonb;

begin

    for rec in

        select

            l.id as league_id,

            l.season,

            r.round_number

        from public.leagues l

        join public.nfl_playoff_settings s
            on s.league_id = l.id
           and s.season = l.season

        cross join (
            values
                (1),
                (2),
                (3),
                (4)
        ) as r(round_number)

        where l.player_selection_mode = 'salary'

          and l.status in (
              'setup',
              'active'
          )

          and not exists (

              select 1

              from public.nfl_playoff_salary_round_state st

              where st.league_id =
                    l.id

                and st.season =
                    l.season

                and st.round_number =
                    r.round_number

                and st.is_locked =
                    true
          )

        order by
            l.id,
            r.round_number

    loop


        v_expected_games :=
            public.get_nfl_playoff_expected_game_count(
                rec.round_number
            );


        select

            count(*),

            min(
                g.kickoff_at
            )

        into

            v_actual_games,

            v_first_kickoff

        from public.nfl_playoff_games pg

        join public.nfl_games g
            on g.id = pg.nfl_game_id

        where pg.league_id =
              rec.league_id

          and pg.season =
              rec.season

          and pg.round_number =
              rec.round_number;


        -- ---------------------------------------------------------------
        -- WAIT UNTIL ALL EXPECTED PLAYOFF MATCHUPS EXIST
        -- ---------------------------------------------------------------

        if coalesce(
            v_actual_games,
            0
        ) <> v_expected_games
           or v_first_kickoff is null
        then

            v_skipped :=
                v_skipped
                ||
                jsonb_build_array(
                    jsonb_build_object(

                        'leagueId',
                            rec.league_id,

                        'season',
                            rec.season,

                        'roundNumber',
                            rec.round_number,

                        'reason',
                            'round_schedule_incomplete',

                        'expectedGames',
                            v_expected_games,

                        'mappedGames',
                            coalesce(
                                v_actual_games,
                                0
                            )
                    )
                );

            continue;

        end if;


        -- ---------------------------------------------------------------
        -- THURSDAY BEFORE FIRST KICKOFF
        -- ---------------------------------------------------------------

        v_first_local_date :=
            (
                v_first_kickoff
                at time zone
                'America/New_York'
            )::date;


        v_publish_local_date :=
            v_first_local_date

            -

            (
                (
                    extract(
                        isodow
                        from v_first_local_date
                    )::integer
                    -
                    4
                    +
                    7
                )
                %
                7
            );


        v_publish_at :=
            (
                v_publish_local_date::timestamp
                +
                time '22:00'
            )
            at time zone
            'America/New_York';


        -- ---------------------------------------------------------------
        -- DO NOT PUBLISH EARLY
        -- ---------------------------------------------------------------

        if now() < v_publish_at then

            v_skipped :=
                v_skipped
                ||
                jsonb_build_array(
                    jsonb_build_object(

                        'leagueId',
                            rec.league_id,

                        'season',
                            rec.season,

                        'roundNumber',
                            rec.round_number,

                        'reason',
                            'publication_window_not_reached',

                        'scheduledPublicationAt',
                            v_publish_at
                    )
                );

            continue;

        end if;


        -- ---------------------------------------------------------------
        -- NEVER CREATE A NEW SALARY BOARD AFTER ROUND HAS STARTED
        -- ---------------------------------------------------------------

        if now() >= v_first_kickoff then

            v_skipped :=
                v_skipped
                ||
                jsonb_build_array(
                    jsonb_build_object(

                        'leagueId',
                            rec.league_id,

                        'season',
                            rec.season,

                        'roundNumber',
                            rec.round_number,

                        'reason',
                            'round_already_started',

                        'firstKickoff',
                            v_first_kickoff
                    )
                );

            continue;

        end if;


        -- ---------------------------------------------------------------
        -- PUBLISH + FREEZE
        -- ---------------------------------------------------------------

        begin

            v_result :=
                public.generate_nfl_playoff_round_salaries(
                    rec.league_id,
                    rec.season,
                    rec.round_number
                );


            v_published :=
                v_published
                ||
                jsonb_build_array(
                    v_result
                );


        exception
            when others then

                v_skipped :=
                    v_skipped
                    ||
                    jsonb_build_array(
                        jsonb_build_object(

                            'leagueId',
                                rec.league_id,

                            'season',
                                rec.season,

                            'roundNumber',
                                rec.round_number,

                            'reason',
                                'salary_generation_error',

                            'error',
                                sqlerrm
                        )
                    );

        end;

    end loop;


    return jsonb_build_object(

        'success',
            true,

        'runAt',
            now(),

        'timezone',
            'America/New_York',

        'publicationRule',
            'Thursday 10:00 PM ET',

        'published',
            v_published,

        'skipped',
            v_skipped
    );

end;

$function$;