begin;

-- ============================================================
-- G365 NFL PLAYOFFS
-- STAGE 1A — FOUNDATION
--
-- NFL Playoffs is a cumulative Total Points contest.
-- Salary / No-Salary is controlled by leagues.player_selection_mode.
-- Existing league_scoring_settings + league_scoring_rules remain
-- authoritative for fantasy scoring.
-- ============================================================


-- ============================================================
-- 1. NFL PLAYOFF LEAGUE SETTINGS
-- ============================================================

create table if not exists public.nfl_playoff_settings (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    season integer not null,

    weekly_salary_cap numeric,

    starting_qb integer not null default 1,
    starting_rb integer not null default 2,
    starting_wr integer not null default 2,
    starting_te integer not null default 1,
    starting_flex integer not null default 2,
    starting_superflex integer not null default 0,
    starting_k integer not null default 1,
    starting_dst integer not null default 1,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nfl_playoff_settings_league_unique
        unique (league_id),

    constraint nfl_playoff_settings_season_positive
        check (season >= 2000),

    constraint nfl_playoff_settings_salary_cap_positive
        check (
            weekly_salary_cap is null
            or weekly_salary_cap > 0
        ),

    constraint nfl_playoff_settings_lineup_nonnegative
        check (
            starting_qb >= 0
            and starting_rb >= 0
            and starting_wr >= 0
            and starting_te >= 0
            and starting_flex >= 0
            and starting_superflex >= 0
            and starting_k >= 0
            and starting_dst >= 0
        )
);


create index if not exists
    nfl_playoff_settings_league_idx
on public.nfl_playoff_settings (league_id);


-- ============================================================
-- 2. POSTSEASON ROUND STATE
--
-- round_number:
-- 1 = Wild Card
-- 2 = Divisional
-- 3 = Conference Championships
-- 4 = Super Bowl
--
-- nfl_week is intentionally nullable. We will map it from the
-- actual ESPN postseason schedule in Stage 1B rather than
-- hard-code provider week numbering here.
-- ============================================================

create table if not exists public.nfl_playoff_rounds (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    season integer not null,

    round_number integer not null,

    round_key text not null,

    round_name text not null,

    nfl_week integer,

    status text not null default 'pending',

    opens_at timestamptz,
    first_kickoff_at timestamptz,
    last_scheduled_kickoff_at timestamptz,

    finalized_at timestamptz,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nfl_playoff_rounds_unique
        unique (
            league_id,
            season,
            round_number
        ),

    constraint nfl_playoff_rounds_round_number_check
        check (
            round_number between 1 and 4
        ),

    constraint nfl_playoff_rounds_round_key_check
        check (
            round_key in (
                'wild_card',
                'divisional',
                'conference',
                'super_bowl'
            )
        ),

    constraint nfl_playoff_rounds_status_check
        check (
            status in (
                'pending',
                'open',
                'live',
                'finalizing',
                'final'
            )
        )
);


create index if not exists
    nfl_playoff_rounds_active_idx
on public.nfl_playoff_rounds (
    league_id,
    season,
    status
);


-- ============================================================
-- 3. FANTASY TEAM ROUND ENTRIES
-- ============================================================

create table if not exists public.nfl_playoff_round_entries (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    fantasy_team_id bigint not null,

    season integer not null,

    round_number integer not null,

    status text not null default 'building',

    salary_used numeric,

    projected_points numeric not null default 0,

    submitted_at timestamptz,

    last_modified_at timestamptz not null default now(),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nfl_playoff_round_entries_unique
        unique (
            league_id,
            fantasy_team_id,
            season,
            round_number
        ),

    constraint nfl_playoff_round_entries_round_check
        check (
            round_number between 1 and 4
        ),

    constraint nfl_playoff_round_entries_status_check
        check (
            status in (
                'building',
                'submitted',
                'partially_locked',
                'locked',
                'final'
            )
        ),

    constraint nfl_playoff_round_entries_salary_nonnegative
        check (
            salary_used is null
            or salary_used >= 0
        )
);


create index if not exists
    nfl_playoff_round_entries_lookup_idx
on public.nfl_playoff_round_entries (
    league_id,
    season,
    round_number
);


-- ============================================================
-- 4. ROUND LINEUPS
--
-- Mirrors the proven Season-Long weekly lineup model.
-- Salary and projection are frozen at selection.
-- Each player can lock independently at kickoff.
-- ============================================================

create table if not exists public.nfl_playoff_round_lineups (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    fantasy_team_id bigint not null,

    season integer not null,

    round_number integer not null,

    player_id bigint not null,

    lineup_slot text not null,

    slot_index integer not null default 1,

    salary_at_selection numeric,

    projected_points_at_selection numeric,

    is_locked boolean not null default false,

    locked_at timestamptz,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nfl_playoff_round_lineups_slot_unique
        unique (
            league_id,
            fantasy_team_id,
            season,
            round_number,
            lineup_slot,
            slot_index
        ),

    constraint nfl_playoff_round_lineups_player_unique
        unique (
            league_id,
            fantasy_team_id,
            season,
            round_number,
            player_id
        ),

    constraint nfl_playoff_round_lineups_round_check
        check (
            round_number between 1 and 4
        ),

    constraint nfl_playoff_round_lineups_slot_index_check
        check (
            slot_index >= 1
        )
);


create index if not exists
    nfl_playoff_round_lineups_lookup_idx
on public.nfl_playoff_round_lineups (
    league_id,
    fantasy_team_id,
    season,
    round_number
);


create index if not exists
    nfl_playoff_round_lineups_player_idx
on public.nfl_playoff_round_lineups (
    player_id
);


-- ============================================================
-- 5. PLAYER SALARIES BY POSTSEASON ROUND
--
-- pricing_details provides the complete salary audit trail.
-- Stage 2 will populate it using the Season-Long salary model
-- adapted to full regular-season + postseason data.
-- ============================================================

create table if not exists public.nfl_playoff_player_salaries (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    season integer not null,

    round_number integer not null,

    nfl_player_id bigint not null,

    salary numeric not null,

    projected_points numeric,

    previous_round_salary numeric,

    salary_change numeric,

    salary_change_percent numeric,

    source text not null default 'gridiron365',

    pricing_details jsonb not null default '{}'::jsonb,

    calculated_at timestamptz not null default now(),

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nfl_playoff_player_salaries_unique
        unique (
            league_id,
            season,
            round_number,
            nfl_player_id
        ),

    constraint nfl_playoff_player_salaries_round_check
        check (
            round_number between 1 and 4
        ),

    constraint nfl_playoff_player_salaries_salary_check
        check (
            salary >= 0
        )
);


create index if not exists
    nfl_playoff_player_salaries_lookup_idx
on public.nfl_playoff_player_salaries (
    league_id,
    season,
    round_number
);


create index if not exists
    nfl_playoff_player_salaries_player_idx
on public.nfl_playoff_player_salaries (
    nfl_player_id
);


-- ============================================================
-- 6. SALARY SETTINGS
--
-- Starts with the exact Season-Long salary configuration.
-- The salary-generation function itself comes later.
-- ============================================================

create table if not exists public.nfl_playoff_salary_settings (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    minimum_salary numeric not null default 3000,
    maximum_salary numeric not null default 12000,
    salary_increment numeric not null default 100,

    projection_weight numeric not null default 1.0000,

    qb_multiplier numeric not null default 0.9500,
    rb_multiplier numeric not null default 1.0800,
    wr_multiplier numeric not null default 1.0500,
    te_multiplier numeric not null default 1.0800,
    k_multiplier numeric not null default 0.7000,
    dst_multiplier numeric not null default 0.7500,

    recent_form_weight numeric not null default 0.30,
    usage_weight numeric not null default 0.15,

    maximum_round_increase numeric not null default 1500,
    maximum_round_decrease numeric not null default 1500,

    questionable_multiplier numeric not null default 0.95,
    doubtful_multiplier numeric not null default 0.75,
    out_multiplier numeric not null default 0.00,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nfl_playoff_salary_settings_unique
        unique (league_id),

    constraint nfl_playoff_salary_range_check
        check (
            minimum_salary >= 0
            and maximum_salary >= minimum_salary
            and salary_increment > 0
        )
);


-- ============================================================
-- 7. SALARY ROUND STATE
-- ============================================================

create table if not exists public.nfl_playoff_salary_round_state (
    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    season integer not null,

    round_number integer not null,

    is_locked boolean not null default false,

    generated_at timestamptz,

    locked_at timestamptz,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    primary key (
        league_id,
        season,
        round_number
    ),

    constraint nfl_playoff_salary_round_state_round_check
        check (
            round_number between 1 and 4
        )
);


-- ============================================================
-- 8. ROUND SCORES
--
-- Final scoring implementation will use the same league scoring
-- settings/rules as the rest of G365.
-- ============================================================

create table if not exists public.nfl_playoff_round_scores (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    fantasy_team_id bigint not null,

    season integer not null,

    round_number integer not null,

    fantasy_points numeric not null default 0,

    projected_points numeric not null default 0,

    lineup_players integer not null default 0,

    is_final boolean not null default false,

    finalized_at timestamptz,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nfl_playoff_round_scores_unique
        unique (
            league_id,
            fantasy_team_id,
            season,
            round_number
        ),

    constraint nfl_playoff_round_scores_round_check
        check (
            round_number between 1 and 4
        )
);


create index if not exists
    nfl_playoff_round_scores_lookup_idx
on public.nfl_playoff_round_scores (
    league_id,
    season,
    round_number
);


-- ============================================================
-- 9. CUMULATIVE STANDINGS
-- ============================================================

create table if not exists public.nfl_playoff_standings (
    id bigint generated by default as identity primary key,

    league_id uuid not null
        references public.leagues(id)
        on delete cascade,

    fantasy_team_id bigint not null,

    season integer not null,

    total_points numeric not null default 0,

    rounds_scored integer not null default 0,

    highest_round_score numeric not null default 0,

    lowest_round_score numeric,

    average_round_score numeric not null default 0,

    current_rank integer,

    updated_at timestamptz not null default now(),

    constraint nfl_playoff_standings_unique
        unique (
            league_id,
            fantasy_team_id,
            season
        )
);


create index if not exists
    nfl_playoff_standings_rank_idx
on public.nfl_playoff_standings (
    league_id,
    season,
    current_rank
);


-- ============================================================
-- 10. LEAGUE STATE
-- ============================================================

create table if not exists public.nfl_playoff_league_state (
    league_id uuid primary key
        references public.leagues(id)
        on delete cascade,

    season integer not null,

    active_round integer not null default 1,

    status text not null default 'setup',

    champion_fantasy_team_id bigint,

    completed_at timestamptz,

    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),

    constraint nfl_playoff_league_state_round_check
        check (
            active_round between 1 and 4
        ),

    constraint nfl_playoff_league_state_status_check
        check (
            status in (
                'setup',
                'active',
                'complete'
            )
        )
);


-- ============================================================
-- 11. INITIALIZATION FUNCTION
--
-- Creates settings + the four contest rounds.
-- Does NOT generate salaries yet.
-- ============================================================

create or replace function public.initialize_nfl_playoff_league(
    p_league_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_league public.leagues%rowtype;
    v_salary_cap numeric;
begin
    select *
    into v_league
    from public.leagues
    where id = p_league_id;

    if not found then
        raise exception 'League could not be found.';
    end if;

    if v_league.league_type <> 'nfl_playoffs' then
        raise exception 'League is not an NFL Playoffs league.';
    end if;

    if v_league.player_selection_mode = 'salary' then
        v_salary_cap := 65000;
    else
        v_salary_cap := null;
    end if;


    insert into public.nfl_playoff_settings (
        league_id,
        season,
        weekly_salary_cap
    )
    values (
        p_league_id,
        v_league.season,
        v_salary_cap
    )
    on conflict (league_id)
    do update set
        season = excluded.season,
        weekly_salary_cap =
            case
                when v_league.player_selection_mode = 'salary'
                    then coalesce(
                        public.nfl_playoff_settings.weekly_salary_cap,
                        excluded.weekly_salary_cap
                    )
                else null
            end,
        updated_at = now();


    insert into public.nfl_playoff_salary_settings (
        league_id
    )
    values (
        p_league_id
    )
    on conflict (league_id)
    do nothing;


    insert into public.nfl_playoff_league_state (
        league_id,
        season,
        active_round,
        status
    )
    values (
        p_league_id,
        v_league.season,
        1,
        'setup'
    )
    on conflict (league_id)
    do update set
        season = excluded.season,
        updated_at = now();


    insert into public.nfl_playoff_rounds (
        league_id,
        season,
        round_number,
        round_key,
        round_name
    )
    values
        (
            p_league_id,
            v_league.season,
            1,
            'wild_card',
            'Wild Card'
        ),
        (
            p_league_id,
            v_league.season,
            2,
            'divisional',
            'Divisional'
        ),
        (
            p_league_id,
            v_league.season,
            3,
            'conference',
            'Conference Championships'
        ),
        (
            p_league_id,
            v_league.season,
            4,
            'super_bowl',
            'Super Bowl'
        )
    on conflict (
        league_id,
        season,
        round_number
    )
    do update set
        round_key = excluded.round_key,
        round_name = excluded.round_name,
        updated_at = now();


    return jsonb_build_object(
        'success', true,
        'leagueId', p_league_id,
        'season', v_league.season,
        'playerSelectionMode',
            v_league.player_selection_mode,
        'rounds', 4,
        'salaryCap',
            v_salary_cap
    );
end;
$$;


-- ============================================================
-- 12. ROUND NAME HELPER
-- ============================================================

create or replace function public.get_nfl_playoff_round_name(
    p_round_number integer
)
returns text
language sql
immutable
as $$
    select
        case p_round_number
            when 1 then 'Wild Card'
            when 2 then 'Divisional'
            when 3 then 'Conference Championships'
            when 4 then 'Super Bowl'
            else 'Unknown'
        end;
$$;


-- ============================================================
-- 13. BASIC STANDINGS REBUILD
-- ============================================================

create or replace function public.rebuild_nfl_playoff_standings(
    p_league_id uuid,
    p_season integer
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
    v_rows integer := 0;
begin

    insert into public.nfl_playoff_standings (
        league_id,
        fantasy_team_id,
        season,
        total_points,
        rounds_scored,
        highest_round_score,
        lowest_round_score,
        average_round_score,
        current_rank,
        updated_at
    )
    select
        s.league_id,
        s.fantasy_team_id,
        s.season,
        sum(s.fantasy_points),
        count(*) filter (
            where s.is_final
        ),
        max(s.fantasy_points),
        min(s.fantasy_points),
        case
            when count(*) > 0
                then avg(s.fantasy_points)
            else 0
        end,
        null,
        now()
    from public.nfl_playoff_round_scores s
    where s.league_id = p_league_id
      and s.season = p_season
    group by
        s.league_id,
        s.fantasy_team_id,
        s.season

    on conflict (
        league_id,
        fantasy_team_id,
        season
    )
    do update set
        total_points =
            excluded.total_points,

        rounds_scored =
            excluded.rounds_scored,

        highest_round_score =
            excluded.highest_round_score,

        lowest_round_score =
            excluded.lowest_round_score,

        average_round_score =
            excluded.average_round_score,

        updated_at =
            now();


    with ranked as (
        select
            id,
            row_number() over (
                order by
                    total_points desc,
                    highest_round_score desc,
                    fantasy_team_id asc
            ) as rank_number
        from public.nfl_playoff_standings
        where league_id = p_league_id
          and season = p_season
    )
    update public.nfl_playoff_standings s
    set
        current_rank =
            ranked.rank_number,
        updated_at =
            now()
    from ranked
    where s.id = ranked.id;


    get diagnostics
        v_rows =
            row_count;


    return jsonb_build_object(
        'success', true,
        'leagueId', p_league_id,
        'season', p_season,
        'standingsRows', v_rows
    );
end;
$$;


commit;