-- Gridiron365 / G365 NHL Pick'em league-picks visibility, recap awards,
-- trophy history, and season renewal.
-- Migration: 20260906_007_nhl_pickem_visibility_recap_trophies_renewal.sql
-- Depends on migrations 002-006.
-- Existing Football Pick'em objects are not modified.

begin;

-- ---------------------------------------------------------------------------
-- Persistent awards/trophies across renewed seasons.
-- ---------------------------------------------------------------------------

create table if not exists public.nhl_pickem_awards (
  id bigint generated by default as identity primary key,
  history_id uuid not null references public.nhl_pickem_histories(id) on delete cascade,
  franchise_id uuid not null references public.nhl_pickem_franchises(id) on delete cascade,
  league_id uuid not null references public.leagues(id) on delete cascade,
  season integer not null,
  nhl_pickem_period_id bigint references public.nhl_pickem_periods(id) on delete set null,
  award_type text not null,
  award_key text not null,
  title text not null,
  description text,
  metadata jsonb not null default '{}'::jsonb,
  awarded_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (league_id, season, award_key, franchise_id)
);

create index if not exists idx_nhl_pickem_awards_history
  on public.nhl_pickem_awards(history_id, awarded_at desc);

create index if not exists idx_nhl_pickem_awards_league_season
  on public.nhl_pickem_awards(league_id, season, awarded_at desc);

alter table public.nhl_pickem_awards enable row level security;

drop policy if exists nhl_pickem_awards_member_read
  on public.nhl_pickem_awards;

create policy nhl_pickem_awards_member_read
on public.nhl_pickem_awards
for select
to authenticated
using (
  private.is_league_member(league_id, auth.uid())
);

grant select on public.nhl_pickem_awards to authenticated;
revoke insert, update, delete on public.nhl_pickem_awards from authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'nhl_pickem_awards'
  ) then
    alter publication supabase_realtime add table public.nhl_pickem_awards;
  end if;
end
$$;

-- ---------------------------------------------------------------------------
-- League Picks visibility.
--
-- A member's own picks are always visible to that member.
-- Other entries' selections become visible pick-by-pick only after that
-- selected NHL game's puck drop/lock. This preserves privacy while allowing
-- live League Picks cards as games begin.
-- ---------------------------------------------------------------------------

create or replace function public.get_nhl_pickem_league_picks(
  p_league_id uuid,
  p_season integer,
  p_period_number integer
)
returns table (
  entry_id bigint,
  fantasy_team_id bigint,
  entry_name text,
  user_id uuid,
  pick_id bigint,
  nhl_pickem_game_id bigint,
  nhl_game_id bigint,
  market_type text,
  selected_side text,
  snapshot_home_puck_line numeric,
  snapshot_away_puck_line numeric,
  snapshot_total numeric,
  confidence_value numeric,
  locked_at timestamptz,
  result text,
  points_awarded numeric,
  kickoff_at timestamptz,
  home_team_id bigint,
  away_team_id bigint,
  home_score integer,
  away_score integer,
  game_status text,
  period integer,
  display_clock text,
  is_own_entry boolean
)
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_period_id bigint;
begin
  if v_user_id is null then
    raise exception 'Authentication is required.';
  end if;

  if not private.is_league_member(p_league_id, v_user_id) then
    raise exception 'You are not a member of this NHL Pick''em league.';
  end if;

  select p.id into v_period_id
  from public.nhl_pickem_periods p
  where p.league_id = p_league_id
    and p.season = p_season
    and p.period_number = p_period_number;

  if v_period_id is null then
    raise exception 'NHL Pick''em period could not be found.';
  end if;

  return query
  select
    e.id,
    e.fantasy_team_id,
    e.entry_name,
    e.user_id,
    pk.id,
    pg.id,
    ng.id,
    pk.market_type,
    pk.selected_side,
    pk.snapshot_home_puck_line,
    pk.snapshot_away_puck_line,
    pk.snapshot_total,
    pk.confidence_value,
    pk.locked_at,
    pk.result,
    pk.points_awarded,
    ng.kickoff_at,
    ng.home_team_id,
    ng.away_team_id,
    ng.home_score,
    ng.away_score,
    ng.status_name,
    ng.period,
    ng.display_clock,
    (e.user_id = v_user_id)
  from public.nhl_pickem_entries e
  join public.nhl_pickem_picks pk
    on pk.entry_id = e.id
   and pk.nhl_pickem_period_id = v_period_id
  join public.nhl_pickem_games pg
    on pg.id = pk.nhl_pickem_game_id
  join public.nhl_games ng
    on ng.id = pg.nhl_game_id
  where e.league_id = p_league_id
    and e.season = p_season
    and e.active = true
    and (
      e.user_id = v_user_id
      or pk.locked_at is not null
      or now() >= ng.kickoff_at
    )
  order by e.entry_name, ng.kickoff_at, pk.id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Build persistent awards for one finalized period.
-- ---------------------------------------------------------------------------

create or replace function public.build_nhl_pickem_period_awards(
  p_nhl_pickem_period_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_period public.nhl_pickem_periods%rowtype;
  v_history_id uuid;
  v_inserted integer := 0;
begin
  select * into v_period
  from public.nhl_pickem_periods
  where id = p_nhl_pickem_period_id;

  if not found then
    raise exception 'NHL Pick''em period could not be found.';
  end if;

  if v_period.status <> 'final' then
    return jsonb_build_object(
      'success', true,
      'periodId', v_period.id,
      'awardsCreated', 0,
      'reason', 'period_not_final'
    );
  end if;

  select nhl_pickem_history_id into v_history_id
  from public.leagues
  where id = v_period.league_id;

  if v_history_id is null then
    v_history_id := public.ensure_nhl_pickem_history_identity(v_period.league_id);
  end if;

  -- Period winner(s), including legitimate ties.
  with inserted as (
    insert into public.nhl_pickem_awards (
      history_id,
      franchise_id,
      league_id,
      season,
      nhl_pickem_period_id,
      award_type,
      award_key,
      title,
      description,
      metadata
    )
    select
      v_history_id,
      e.franchise_id,
      v_period.league_id,
      v_period.season,
      v_period.id,
      'period_winner',
      format('period_%s_winner', v_period.period_number),
      format('Period %s Winner', v_period.period_number),
      format(
        '%s finished first in G365 NHL Pick''em Period %s.',
        e.entry_name,
        v_period.period_number
      ),
      jsonb_build_object(
        'periodNumber', v_period.period_number,
        'wins', r.wins,
        'pushes', r.pushes,
        'losses', r.losses,
        'points', r.points
      )
    from public.nhl_pickem_period_results r
    join public.nhl_pickem_entries e on e.id = r.entry_id
    where r.nhl_pickem_period_id = v_period.id
      and r.is_period_winner = true
      and e.franchise_id is not null
    on conflict (league_id, season, award_key, franchise_id) do nothing
    returning id
  )
  select count(*) into v_inserted from inserted;

  return jsonb_build_object(
    'success', true,
    'periodId', v_period.id,
    'awardsCreated', v_inserted
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Season awards/champion. Safe to rerun.
-- ---------------------------------------------------------------------------

create or replace function public.build_nhl_pickem_season_awards(
  p_league_id uuid,
  p_season integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_history_id uuid;
  v_unfinalized integer := 0;
  v_inserted integer := 0;
begin
  perform private.assert_nhl_pickem_league(p_league_id);

  select count(*) into v_unfinalized
  from public.nhl_pickem_periods
  where league_id = p_league_id
    and season = p_season
    and status <> 'final';

  if v_unfinalized > 0 then
    return jsonb_build_object(
      'success', true,
      'leagueId', p_league_id,
      'season', p_season,
      'awardsCreated', 0,
      'reason', 'season_not_complete',
      'unfinalizedPeriods', v_unfinalized
    );
  end if;

  select nhl_pickem_history_id into v_history_id
  from public.leagues
  where id = p_league_id;

  if v_history_id is null then
    v_history_id := public.ensure_nhl_pickem_history_identity(p_league_id);
  end if;

  with inserted as (
    insert into public.nhl_pickem_awards (
      history_id,
      franchise_id,
      league_id,
      season,
      award_type,
      award_key,
      title,
      description,
      metadata
    )
    select
      v_history_id,
      e.franchise_id,
      p_league_id,
      p_season,
      'season_champion',
      'season_champion',
      'G365 NHL Pick''em Champion',
      format('%s won the %s G365 NHL Pick''em championship.', e.entry_name, p_season),
      jsonb_build_object(
        'rank', s.rank,
        'wins', s.wins,
        'pushes', s.pushes,
        'losses', s.losses,
        'points', s.points
      )
    from public.nhl_pickem_standings s
    join public.nhl_pickem_entries e on e.id = s.entry_id
    where s.league_id = p_league_id
      and s.season = p_season
      and s.rank = 1
      and e.franchise_id is not null
    on conflict (league_id, season, award_key, franchise_id) do nothing
    returning id
  )
  select count(*) into v_inserted from inserted;

  return jsonb_build_object(
    'success', true,
    'leagueId', p_league_id,
    'season', p_season,
    'awardsCreated', v_inserted
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Recap payload.
-- ---------------------------------------------------------------------------

create or replace function public.get_nhl_pickem_recap(
  p_league_id uuid,
  p_season integer,
  p_period_number integer default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_period_id bigint;
  v_period_json jsonb := null;
  v_results jsonb := '[]'::jsonb;
  v_standings jsonb := '[]'::jsonb;
  v_awards jsonb := '[]'::jsonb;
begin
  if v_user_id is null
     or not private.is_league_member(p_league_id, v_user_id)
  then
    raise exception 'You are not a member of this NHL Pick''em league.';
  end if;

  if p_period_number is not null then
    select p.id,
           jsonb_build_object(
             'id', p.id,
             'periodNumber', p.period_number,
             'startsAt', p.starts_at,
             'endsAt', p.ends_at,
             'status', p.status,
             'finalizedAt', p.finalized_at
           )
      into v_period_id, v_period_json
    from public.nhl_pickem_periods p
    where p.league_id = p_league_id
      and p.season = p_season
      and p.period_number = p_period_number;

    select coalesce(jsonb_agg(x.obj order by x.rank, x.entry_name), '[]'::jsonb)
      into v_results
    from (
      select
        r.rank,
        e.entry_name,
        jsonb_build_object(
          'entryId', e.id,
          'entryName', e.entry_name,
          'rank', r.rank,
          'winner', r.is_period_winner,
          'requiredPicks', r.required_picks,
          'submittedPicks', r.submitted_picks,
          'missingPicks', r.missing_picks,
          'wins', r.wins,
          'pushes', r.pushes,
          'losses', r.losses,
          'ungraded', r.ungraded,
          'points', r.points
        ) as obj
      from public.nhl_pickem_period_results r
      join public.nhl_pickem_entries e on e.id = r.entry_id
      where r.nhl_pickem_period_id = v_period_id
    ) x;
  end if;

  select coalesce(jsonb_agg(x.obj order by x.rank, x.entry_name), '[]'::jsonb)
    into v_standings
  from (
    select
      s.rank,
      e.entry_name,
      jsonb_build_object(
        'entryId', e.id,
        'entryName', e.entry_name,
        'rank', s.rank,
        'wins', s.wins,
        'pushes', s.pushes,
        'losses', s.losses,
        'ungraded', s.ungraded,
        'points', s.points
      ) as obj
    from public.nhl_pickem_standings s
    join public.nhl_pickem_entries e on e.id = s.entry_id
    where s.league_id = p_league_id
      and s.season = p_season
  ) x;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'awardType', a.award_type,
      'awardKey', a.award_key,
      'title', a.title,
      'description', a.description,
      'entryName', e.entry_name,
      'awardedAt', a.awarded_at,
      'metadata', a.metadata
    )
    order by a.awarded_at desc, a.id desc
  ), '[]'::jsonb)
  into v_awards
  from public.nhl_pickem_awards a
  left join public.nhl_pickem_franchises f on f.id = a.franchise_id
  left join public.nhl_pickem_entries e
    on e.franchise_id = f.id
   and e.league_id = p_league_id
   and e.season = p_season
  where a.league_id = p_league_id
    and a.season = p_season
    and (
      p_period_number is null
      or a.nhl_pickem_period_id = v_period_id
      or a.nhl_pickem_period_id is null
    );

  return jsonb_build_object(
    'success', true,
    'leagueId', p_league_id,
    'season', p_season,
    'period', v_period_json,
    'periodResults', v_results,
    'standings', v_standings,
    'awards', v_awards
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Trophy case across all seasons sharing the NHL Pick'em history identity.
-- ---------------------------------------------------------------------------

create or replace function public.get_nhl_pickem_trophy_case(
  p_league_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_history_id uuid;
  v_awards jsonb;
begin
  if v_user_id is null
     or not private.is_league_member(p_league_id, v_user_id)
  then
    raise exception 'You are not a member of this NHL Pick''em league.';
  end if;

  select nhl_pickem_history_id into v_history_id
  from public.leagues
  where id = p_league_id;

  select coalesce(jsonb_agg(
    jsonb_build_object(
      'season', a.season,
      'awardType', a.award_type,
      'awardKey', a.award_key,
      'title', a.title,
      'description', a.description,
      'franchiseId', a.franchise_id,
      'franchiseName', f.display_name,
      'awardedAt', a.awarded_at,
      'metadata', a.metadata
    )
    order by a.season desc, a.awarded_at desc, a.id desc
  ), '[]'::jsonb)
  into v_awards
  from public.nhl_pickem_awards a
  join public.nhl_pickem_franchises f on f.id = a.franchise_id
  where a.history_id = v_history_id;

  return jsonb_build_object(
    'success', true,
    'historyId', v_history_id,
    'awards', v_awards
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Renewal.
--
-- Creates the next-season league while preserving NHL Pick'em history and
-- franchise identity. Every active owner receives membership, a new season
-- fantasy team, entry, and standings row. Commissioner settings carry forward.
-- Period dates are generated separately once the new NHL schedule anchor is
-- known, avoiding guessed future season dates.
-- ---------------------------------------------------------------------------

create or replace function public.renew_nhl_pickem_league(
  p_league_id uuid,
  p_new_season integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_old public.leagues%rowtype;
  v_new_league_id uuid;
  v_history_id uuid;
  v_settings public.nhl_pickem_settings%rowtype;
  r record;
  v_new_team_id bigint;
  v_new_entry_id bigint;
  v_members integer := 0;
begin
  perform private.assert_nhl_pickem_commissioner(p_league_id, v_user_id);

  select * into v_old
  from public.leagues
  where id = p_league_id
  for update;

  if p_new_season is null or p_new_season <= v_old.season then
    raise exception 'Renewal season must be later than the current season.';
  end if;

  v_history_id := public.ensure_nhl_pickem_history_identity(p_league_id);

  if exists (
    select 1
    from public.leagues
    where nhl_pickem_history_id = v_history_id
      and season = p_new_season
  ) then
    raise exception 'This NHL Pick''em history already has a league for season %.', p_new_season;
  end if;

  select * into v_settings
  from public.nhl_pickem_settings
  where league_id = p_league_id;

  insert into public.leagues (
    name,
    league_type,
    season,
    commissioner_user_id,
    status,
    player_selection_mode,
    nhl_pickem_history_id
  )
  values (
    v_old.name,
    'nhl_pickem',
    p_new_season,
    v_old.commissioner_user_id,
    'setup',
    v_old.player_selection_mode,
    v_history_id
  )
  returning id into v_new_league_id;

  insert into public.nhl_pickem_settings (
    league_id,
    picks_per_period,
    market_mode,
    allow_same_game_multiple_markets,
    pick_lock_mode,
    minimum_source_books,
    scoring_mode,
    win_points,
    push_points,
    loss_points,
    confidence_points,
    confidence_push_multiplier,
    missing_pick_policy,
    contest_timezone,
    line_freeze_local_time
  )
  values (
    v_new_league_id,
    v_settings.picks_per_period,
    v_settings.market_mode,
    v_settings.allow_same_game_multiple_markets,
    'game',
    v_settings.minimum_source_books,
    v_settings.scoring_mode,
    v_settings.win_points,
    v_settings.push_points,
    v_settings.loss_points,
    v_settings.confidence_points,
    v_settings.confidence_push_multiplier,
    v_settings.missing_pick_policy,
    'America/New_York',
    time '11:00:00'
  );

  for r in
    select
      e.user_id,
      e.entry_name,
      e.franchise_id,
      case
        when e.user_id = v_old.commissioner_user_id then 'commissioner'
        else 'member'
      end as member_role
    from public.nhl_pickem_entries e
    where e.league_id = p_league_id
      and e.season = v_old.season
      and e.active = true
      and e.user_id is not null
      and e.franchise_id is not null
  loop
    insert into public.league_members(league_id, user_id, role)
    values(v_new_league_id, r.user_id, r.member_role)
    on conflict do nothing;

    update public.nhl_pickem_franchises
    set owner_id = r.user_id,
        display_name = r.entry_name,
        active = true,
        updated_at = now()
    where id = r.franchise_id;

    insert into public.fantasy_teams (
      league_id,
      owner_id,
      team_name,
      active,
      is_cpu,
      nhl_pickem_franchise_id
    )
    values (
      v_new_league_id,
      r.user_id,
      r.entry_name,
      true,
      false,
      r.franchise_id
    )
    returning id into v_new_team_id;

    insert into public.nhl_pickem_entries (
      league_id,
      fantasy_team_id,
      user_id,
      franchise_id,
      season,
      entry_name,
      active
    )
    values (
      v_new_league_id,
      v_new_team_id,
      r.user_id,
      r.franchise_id,
      p_new_season,
      r.entry_name,
      true
    )
    returning id into v_new_entry_id;

    insert into public.nhl_pickem_standings (
      league_id,
      season,
      entry_id,
      fantasy_team_id
    )
    values (
      v_new_league_id,
      p_new_season,
      v_new_entry_id,
      v_new_team_id
    );

    v_members := v_members + 1;
  end loop;

  return jsonb_build_object(
    'success', true,
    'oldLeagueId', p_league_id,
    'newLeagueId', v_new_league_id,
    'oldSeason', v_old.season,
    'newSeason', p_new_season,
    'historyId', v_history_id,
    'membersRenewed', v_members
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Extend lifecycle so period awards and season championship history are created
-- automatically after finalization.
-- ---------------------------------------------------------------------------

create or replace function public.advance_nhl_pickem_period_lifecycle()
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  r record;
  v_result jsonb;
  v_finalized integer := 0;
  v_waiting integer := 0;
  v_awards integer := 0;
  v_locked jsonb;
  v_graded jsonb;
begin
  v_locked := public.lock_due_nhl_pickem_picks();
  v_graded := public.grade_final_nhl_pickem_games(1000);

  update public.nhl_pickem_periods
  set status = case
        when status = 'final' then 'final'
        when now() < starts_at then 'upcoming'
        when now() < ends_at then 'open'
        else 'locked'
      end,
      updated_at = now()
  where status <> 'final';

  for r in
    select p.id, p.league_id, p.season
    from public.nhl_pickem_periods p
    join public.leagues l on l.id = p.league_id
    where l.league_type = 'nhl_pickem'
      and p.status <> 'final'
      and now() >= p.ends_at
    order by p.ends_at, p.id
  loop
    v_result := public.finalize_nhl_pickem_period(r.id);

    if coalesce((v_result ->> 'finalized')::boolean, false) then
      v_finalized := v_finalized + 1;
      v_result := public.build_nhl_pickem_period_awards(r.id);
      v_awards := v_awards + coalesce((v_result ->> 'awardsCreated')::integer,0);
      perform public.build_nhl_pickem_season_awards(r.league_id, r.season);
    else
      v_waiting := v_waiting + 1;
    end if;
  end loop;

  return jsonb_build_object(
    'success', true,
    'lockedPicks', coalesce((v_locked ->> 'lockedPicks')::integer,0),
    'gamesGraded', coalesce((v_graded ->> 'gamesGraded')::integer,0),
    'picksGraded', coalesce((v_graded ->> 'picksGraded')::integer,0),
    'periodsFinalized', v_finalized,
    'periodsWaiting', v_waiting,
    'periodAwardsCreated', v_awards
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Permissions
-- ---------------------------------------------------------------------------

grant execute on function public.get_nhl_pickem_league_picks(uuid,integer,integer)
  to authenticated;
grant execute on function public.get_nhl_pickem_recap(uuid,integer,integer)
  to authenticated;
grant execute on function public.get_nhl_pickem_trophy_case(uuid)
  to authenticated;
grant execute on function public.renew_nhl_pickem_league(uuid,integer)
  to authenticated;

revoke all on function public.build_nhl_pickem_period_awards(bigint)
  from public, anon, authenticated;
revoke all on function public.build_nhl_pickem_season_awards(uuid,integer)
  from public, anon, authenticated;

grant execute on function public.build_nhl_pickem_period_awards(bigint)
  to service_role;
grant execute on function public.build_nhl_pickem_season_awards(uuid,integer)
  to service_role;

-- Re-assert lifecycle remains backend-only after CREATE OR REPLACE.
revoke all on function public.advance_nhl_pickem_period_lifecycle()
  from public, anon, authenticated;
grant execute on function public.advance_nhl_pickem_period_lifecycle()
  to service_role;

commit;

-- ---------------------------------------------------------------------------
-- Verification
-- ---------------------------------------------------------------------------

select
  'nhl_pickem_awards_table' as check_name,
  to_regclass('public.nhl_pickem_awards') is not null as pass
union all
select
  'nhl_pickem_league_picks_visibility',
  to_regprocedure('public.get_nhl_pickem_league_picks(uuid,integer,integer)') is not null
union all
select
  'nhl_pickem_recap_function',
  to_regprocedure('public.get_nhl_pickem_recap(uuid,integer,integer)') is not null
union all
select
  'nhl_pickem_trophy_case_function',
  to_regprocedure('public.get_nhl_pickem_trophy_case(uuid)') is not null
union all
select
  'nhl_pickem_renewal_function',
  to_regprocedure('public.renew_nhl_pickem_league(uuid,integer)') is not null
union all
select
  'nhl_pickem_awards_realtime',
  exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'nhl_pickem_awards'
  )
union all
select
  'nhl_pickem_lifecycle_still_service_only',
  (
    has_function_privilege(
      'service_role',
      'public.advance_nhl_pickem_period_lifecycle()',
      'EXECUTE'
    )
    and not has_function_privilege(
      'authenticated',
      'public.advance_nhl_pickem_period_lifecycle()',
      'EXECUTE'
    )
  );
