-- Gridiron365 / G365 NHL Pick'em period finalization + standings lifecycle
-- Migration: 20260906_006_nhl_pickem_period_finalization_and_standings.sql
-- Depends on migrations 002-005.
-- Existing Football Pick'em objects are not modified.

begin;

-- Period results preserve the configured missing-pick policy without inventing
-- fake game selections. Missing required selections are summarized here.
create table if not exists public.nhl_pickem_period_results (
  id bigint generated by default as identity primary key,
  league_id uuid not null references public.leagues(id) on delete cascade,
  nhl_pickem_period_id bigint not null references public.nhl_pickem_periods(id) on delete cascade,
  entry_id bigint not null references public.nhl_pickem_entries(id) on delete cascade,
  fantasy_team_id bigint not null references public.fantasy_teams(id) on delete cascade,
  required_picks integer not null default 0,
  submitted_picks integer not null default 0,
  missing_picks integer not null default 0,
  wins integer not null default 0,
  pushes integer not null default 0,
  losses integer not null default 0,
  ungraded integer not null default 0,
  points numeric not null default 0,
  rank integer,
  is_period_winner boolean not null default false,
  finalized_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (nhl_pickem_period_id, entry_id)
);

create index if not exists idx_nhl_pickem_period_results_league_period
  on public.nhl_pickem_period_results(league_id, nhl_pickem_period_id);

create index if not exists idx_nhl_pickem_period_results_entry
  on public.nhl_pickem_period_results(entry_id, nhl_pickem_period_id);

alter table public.nhl_pickem_period_results enable row level security;

drop policy if exists nhl_pickem_period_results_member_read
  on public.nhl_pickem_period_results;

create policy nhl_pickem_period_results_member_read
on public.nhl_pickem_period_results
for select
to authenticated
using (
  private.is_league_member(league_id, auth.uid())
);

grant select on public.nhl_pickem_period_results to authenticated;
revoke insert, update, delete on public.nhl_pickem_period_results from authenticated;

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'nhl_pickem_period_results'
  ) then
    alter publication supabase_realtime
      add table public.nhl_pickem_period_results;
  end if;
end
$$;

-- Rebuild one league's cumulative standings from finalized period results.
create or replace function public.rebuild_nhl_pickem_standings(
  p_league_id uuid,
  p_season integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_rows integer := 0;
begin
  perform private.assert_nhl_pickem_league(p_league_id);

  insert into public.nhl_pickem_standings (
    league_id,
    season,
    entry_id,
    fantasy_team_id
  )
  select
    e.league_id,
    e.season,
    e.id,
    e.fantasy_team_id
  from public.nhl_pickem_entries e
  where e.league_id = p_league_id
    and e.season = p_season
    and e.active = true
  on conflict do nothing;

  with totals as (
    select
      e.id as entry_id,
      e.fantasy_team_id,
      coalesce(sum(r.wins),0)::integer as wins,
      coalesce(sum(r.pushes),0)::integer as pushes,
      coalesce(sum(r.losses),0)::integer as losses,
      coalesce(sum(r.ungraded),0)::integer as ungraded,
      coalesce(sum(r.points),0)::numeric as points
    from public.nhl_pickem_entries e
    left join public.nhl_pickem_period_results r
      on r.entry_id = e.id
     and r.finalized_at is not null
    where e.league_id = p_league_id
      and e.season = p_season
      and e.active = true
    group by e.id, e.fantasy_team_id
  ),
  ranked as (
    select
      t.*,
      rank() over (
        order by
          case
            when s.scoring_mode = 'record_only'
              then t.wins::numeric + (t.pushes::numeric * 0.5)
            else t.points
          end desc,
          t.wins desc,
          t.pushes desc,
          t.losses asc,
          t.entry_id asc
      )::integer as standing_rank
    from totals t
    cross join lateral (
      select scoring_mode
      from public.nhl_pickem_settings
      where league_id = p_league_id
    ) s
  ),
  updated as (
    update public.nhl_pickem_standings st
    set wins = r.wins,
        pushes = r.pushes,
        losses = r.losses,
        ungraded = r.ungraded,
        points = r.points,
        rank = r.standing_rank,
        updated_at = now()
    from ranked r
    where st.league_id = p_league_id
      and st.season = p_season
      and st.entry_id = r.entry_id
    returning st.id
  )
  select count(*) into v_rows from updated;

  return jsonb_build_object(
    'success', true,
    'leagueId', p_league_id,
    'season', p_season,
    'standingsRows', v_rows
  );
end;
$$;

-- Finalize one Monday-Sunday contest period only after every included NHL game
-- is administratively resolved: frozen games must be final/graded, while games
-- excluded by the line pipeline are already resolved for contest purposes.
create or replace function public.finalize_nhl_pickem_period(
  p_nhl_pickem_period_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_period public.nhl_pickem_periods%rowtype;
  v_settings public.nhl_pickem_settings%rowtype;
  v_unresolved integer := 0;
  v_rows integer := 0;
begin
  select * into v_period
  from public.nhl_pickem_periods
  where id = p_nhl_pickem_period_id
  for update;

  if not found then
    raise exception 'NHL Pick''em period could not be found.';
  end if;

  if v_period.status = 'final' then
    return jsonb_build_object(
      'success', true,
      'periodId', v_period.id,
      'alreadyFinal', true
    );
  end if;

  select * into v_settings
  from public.nhl_pickem_settings
  where league_id = v_period.league_id;

  if not found then
    raise exception 'NHL Pick''em settings could not be found.';
  end if;

  -- Never finalize before the Monday-Sunday period has ended.
  if now() < v_period.ends_at then
    return jsonb_build_object(
      'success', true,
      'periodId', v_period.id,
      'finalized', false,
      'reason', 'period_not_ended'
    );
  end if;

  -- Grade any completed frozen games first.
  perform public.grade_nhl_pickem_game(g.id)
  from public.nhl_pickem_games g
  join public.nhl_games ng on ng.id = g.nhl_game_id
  where g.nhl_pickem_period_id = v_period.id
    and g.line_status = 'frozen'
    and ng.status_completed = true
    and (
      g.graded_at is null
      or g.final_home_score is distinct from ng.home_score
      or g.final_away_score is distinct from ng.away_score
    );

  select count(*)
    into v_unresolved
  from public.nhl_pickem_games g
  join public.nhl_games ng on ng.id = g.nhl_game_id
  where g.nhl_pickem_period_id = v_period.id
    and (
      g.line_status = 'pending'
      or (
        g.line_status = 'frozen'
        and (
          ng.status_completed = false
          or g.graded_at is null
        )
      )
    );

  if v_unresolved > 0 then
    return jsonb_build_object(
      'success', true,
      'periodId', v_period.id,
      'finalized', false,
      'reason', 'games_unresolved',
      'unresolvedGames', v_unresolved
    );
  end if;

  -- Build final per-entry period totals. Missing picks are not fabricated.
  -- policy=loss: each missing required selection increments losses.
  -- policy=ungraded: each missing required selection increments ungraded.
  insert into public.nhl_pickem_period_results (
    league_id,
    nhl_pickem_period_id,
    entry_id,
    fantasy_team_id,
    required_picks,
    submitted_picks,
    missing_picks,
    wins,
    pushes,
    losses,
    ungraded,
    points,
    finalized_at
  )
  select
    e.league_id,
    v_period.id,
    e.id,
    e.fantasy_team_id,
    v_settings.picks_per_period,
    count(p.id)::integer,
    greatest(v_settings.picks_per_period - count(p.id)::integer, 0),
    count(p.id) filter (where p.result = 'win')::integer,
    count(p.id) filter (where p.result = 'push')::integer,
    (
      count(p.id) filter (where p.result = 'loss')
      + case
          when v_settings.missing_pick_policy = 'loss'
            then greatest(v_settings.picks_per_period - count(p.id)::integer, 0)
          else 0
        end
    )::integer,
    (
      count(p.id) filter (
        where p.result is null or p.result = 'ungraded'
      )
      + case
          when v_settings.missing_pick_policy = 'ungraded'
            then greatest(v_settings.picks_per_period - count(p.id)::integer, 0)
          else 0
        end
    )::integer,
    coalesce(sum(p.points_awarded),0)::numeric
      + case
          when v_settings.missing_pick_policy = 'loss'
               and v_settings.scoring_mode = 'standard'
          then
            greatest(v_settings.picks_per_period - count(p.id)::integer, 0)
            * coalesce(v_settings.loss_points,0)
          else 0
        end,
    now()
  from public.nhl_pickem_entries e
  left join public.nhl_pickem_picks p
    on p.entry_id = e.id
   and p.nhl_pickem_period_id = v_period.id
  where e.league_id = v_period.league_id
    and e.season = v_period.season
    and e.active = true
  group by e.id, e.league_id, e.fantasy_team_id
  on conflict (nhl_pickem_period_id, entry_id)
  do update
  set required_picks = excluded.required_picks,
      submitted_picks = excluded.submitted_picks,
      missing_picks = excluded.missing_picks,
      wins = excluded.wins,
      pushes = excluded.pushes,
      losses = excluded.losses,
      ungraded = excluded.ungraded,
      points = excluded.points,
      finalized_at = excluded.finalized_at,
      updated_at = now();

  -- Rank this period. Ties share rank and all rank-1 entries are winners.
  with ranked as (
    select
      r.id,
      rank() over (
        order by
          case
            when v_settings.scoring_mode = 'record_only'
              then r.wins::numeric + (r.pushes::numeric * 0.5)
            else r.points
          end desc,
          r.wins desc,
          r.pushes desc,
          r.losses asc,
          r.entry_id asc
      )::integer as period_rank
    from public.nhl_pickem_period_results r
    where r.nhl_pickem_period_id = v_period.id
  ),
  updated as (
    update public.nhl_pickem_period_results r
    set rank = ranked.period_rank,
        is_period_winner = (ranked.period_rank = 1),
        updated_at = now()
    from ranked
    where r.id = ranked.id
    returning r.id
  )
  select count(*) into v_rows from updated;

  update public.nhl_pickem_periods
  set status = 'final',
      finalized_at = now(),
      updated_at = now()
  where id = v_period.id;

  perform public.rebuild_nhl_pickem_standings(
    v_period.league_id,
    v_period.season
  );

  return jsonb_build_object(
    'success', true,
    'periodId', v_period.id,
    'leagueId', v_period.league_id,
    'season', v_period.season,
    'finalized', true,
    'resultRows', v_rows
  );
end;
$$;

-- Lifecycle runner: lock due picks, grade finals, finalize ended periods, and
-- update upcoming/open/locked period status without finalizing early.
create or replace function public.advance_nhl_pickem_period_lifecycle()
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  r record;
  v_result jsonb;
  v_finalized integer := 0;
  v_waiting integer := 0;
  v_locked jsonb;
  v_graded jsonb;
begin
  v_locked := public.lock_due_nhl_pickem_picks();
  v_graded := public.grade_final_nhl_pickem_games(1000);

  update public.nhl_pickem_periods
  set status = case
        when status = 'final' then 'final'
        when now() < starts_at then 'upcoming'
        when now() < ends_at then 'open'
        else 'locked'
      end,
      updated_at = now()
  where status <> 'final';

  for r in
    select p.id
    from public.nhl_pickem_periods p
    join public.leagues l on l.id = p.league_id
    where l.league_type = 'nhl_pickem'
      and p.status <> 'final'
      and now() >= p.ends_at
    order by p.ends_at, p.id
  loop
    v_result := public.finalize_nhl_pickem_period(r.id);

    if coalesce((v_result ->> 'finalized')::boolean, false) then
      v_finalized := v_finalized + 1;
    else
      v_waiting := v_waiting + 1;
    end if;
  end loop;

  return jsonb_build_object(
    'success', true,
    'lockedPicks', coalesce((v_locked ->> 'lockedPicks')::integer,0),
    'gamesGraded', coalesce((v_graded ->> 'gamesGraded')::integer,0),
    'picksGraded', coalesce((v_graded ->> 'picksGraded')::integer,0),
    'periodsFinalized', v_finalized,
    'periodsWaiting', v_waiting
  );
end;
$$;

-- Member-facing card status.
create or replace function public.get_nhl_pickem_my_card_status(
  p_league_id uuid,
  p_season integer,
  p_period_number integer
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_entry public.nhl_pickem_entries%rowtype;
  v_period public.nhl_pickem_periods%rowtype;
  v_settings public.nhl_pickem_settings%rowtype;
  v_selected integer := 0;
  v_locked integer := 0;
  v_confidence_assigned integer := 0;
begin
  v_entry := private.get_nhl_pickem_owned_entry(
    p_league_id,
    p_season,
    v_user_id
  );

  select * into v_period
  from public.nhl_pickem_periods
  where league_id = p_league_id
    and season = p_season
    and period_number = p_period_number;

  if not found then
    raise exception 'NHL Pick''em period could not be found.';
  end if;

  select * into v_settings
  from public.nhl_pickem_settings
  where league_id = p_league_id;

  select
    count(*)::integer,
    count(*) filter (where locked_at is not null)::integer,
    count(*) filter (where confidence_value is not null)::integer
  into
    v_selected,
    v_locked,
    v_confidence_assigned
  from public.nhl_pickem_picks
  where entry_id = v_entry.id
    and nhl_pickem_period_id = v_period.id;

  return jsonb_build_object(
    'success', true,
    'leagueId', p_league_id,
    'season', p_season,
    'periodNumber', p_period_number,
    'entryId', v_entry.id,
    'requiredPicks', v_settings.picks_per_period,
    'selectedPicks', v_selected,
    'missingPicks', greatest(v_settings.picks_per_period - v_selected,0),
    'lockedPicks', v_locked,
    'scoringMode', v_settings.scoring_mode,
    'confidenceAssigned', v_confidence_assigned,
    'isComplete',
      (
        v_selected = v_settings.picks_per_period
        and (
          v_settings.scoring_mode <> 'confidence'
          or v_confidence_assigned = v_settings.picks_per_period
        )
      ),
    'periodStatus', v_period.status
  );
end;
$$;

-- Permissions: lifecycle/finalization/rebuild are service-only.
revoke all on function public.rebuild_nhl_pickem_standings(uuid,integer)
  from public, anon, authenticated;
revoke all on function public.finalize_nhl_pickem_period(bigint)
  from public, anon, authenticated;
revoke all on function public.advance_nhl_pickem_period_lifecycle()
  from public, anon, authenticated;

grant execute on function public.rebuild_nhl_pickem_standings(uuid,integer)
  to service_role;
grant execute on function public.finalize_nhl_pickem_period(bigint)
  to service_role;
grant execute on function public.advance_nhl_pickem_period_lifecycle()
  to service_role;

grant execute on function public.get_nhl_pickem_my_card_status(uuid,integer,integer)
  to authenticated;

commit;

-- Verification
select
  'nhl_pickem_period_results_table' as check_name,
  to_regclass('public.nhl_pickem_period_results') is not null as pass
union all
select
  'nhl_pickem_period_finalize_function',
  to_regprocedure('public.finalize_nhl_pickem_period(bigint)') is not null
union all
select
  'nhl_pickem_standings_rebuild_function',
  to_regprocedure('public.rebuild_nhl_pickem_standings(uuid,integer)') is not null
union all
select
  'nhl_pickem_lifecycle_function',
  to_regprocedure('public.advance_nhl_pickem_period_lifecycle()') is not null
union all
select
  'nhl_pickem_card_status_function',
  to_regprocedure('public.get_nhl_pickem_my_card_status(uuid,integer,integer)') is not null
union all
select
  'nhl_pickem_period_results_realtime',
  exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'nhl_pickem_period_results'
  )
union all
select
  'nhl_pickem_lifecycle_service_only',
  (
    has_function_privilege(
      'service_role',
      'public.advance_nhl_pickem_period_lifecycle()',
      'EXECUTE'
    )
    and not has_function_privilege(
      'authenticated',
      'public.advance_nhl_pickem_period_lifecycle()',
      'EXECUTE'
    )
  );
